### ISSUE TITLE
ParentNotInitializedException when processing comments with -c 

### ISSUE THREAD

**Issue by giphon** [INRIA/spoon#1073]
I am aware that comments can be processed using the command "-c"  since Spoon 5.2.0. Thanks for this feature.  

When using Spoon to process comments in either code snippet below, ParentNotInitializedException will be thrown. An empty processor can be used to reproduce this issue. This happens in both Spoon 5.2 and 5.4.

public class Comment_1 {

	public void code_1()
	{
		try {		}
		// A 
		// B
		catch (Exception ex)
		{		}
	}
}

public class Comment2 {

	// C
 	@interface Code_2{} 	
}

Details of the exception are as follows.

spoon.reflect.declaration.ParentNotInitializedException: parent not initialized for class spoon.support.reflect.code.CtCommentImpl (/home/jifeng/workspace/Temp4/src/main/java/example/Comment1.java:17)
	at spoon.support.reflect.declaration.CtElementImpl.getParent(CtElementImpl.java:284)
	at spoon.support.compiler.jdt.JDTCommentBuilder.insertCommentInAST(JDTCommentBuilder.java:377)
	at spoon.support.compiler.jdt.JDTCommentBuilder.buildComment(JDTCommentBuilder.java:131)
	at spoon.support.compiler.jdt.JDTCommentBuilder.build(JDTCommentBuilder.java:96)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildSources(JDTBasedSpoonCompiler.java:387)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:116)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:99)
	at spoon.Launcher.buildModel(Launcher.java:712)
	at spoon.Launcher.run(Launcher.java:663)
	at spoon.Launcher.run(Launcher.java:106)
	at spoon.Launcher.main(Launcher.java:99)

**Comment by surli** [comment]
Thank you for the feedback, I just reproduce your bug in https://github.com/surli/spoon/commit/7082dcf803faf0f2ca0dc512f7610459fbf17c0d I will investigate for a fix. 
In the meantime, you can pass the checks in Spoon using `-a` argument in command-line.

**Comment by giphon** [comment]
Thanks a lot. Here is another example for incorrect comments for -c  . 
When processing 
```
	public void code_3()
	{
		int[] myArray = {
				3, 5	// D
		};
	}
```
The result is as follows. 
```
    public void code_3() {
        int[] myArray = new int[]{ 3 , 5 ,  //  };  
    }
```
