### ISSUE TITLE
Type Foo already defined when spooning the Spoon source code

### ISSUE THREAD

**Issue by orichalque** [INRIA/spoon#1295]
Hello,

I'm trying to instrument the source code of a Java project (The Spoon source code). But when I launch the instrumentation, Spoon will throw the following exceptions: 

```
Caused by: spoon.compiler.ModelBuildingException: The type Foo is already defined
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.reportProblem(JDTBasedSpoonCompiler.java:549)
	at spoon.support.compiler.jdt.TreeBuilderRequestor.acceptResult(TreeBuilderRequestor.java:37)
	at spoon.support.compiler.jdt.TreeBuilderCompiler.buildUnits(TreeBuilderCompiler.java:73)
	at spoon.support.compiler.jdt.JDTBatchCompiler.getUnits(JDTBatchCompiler.java:120)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildUnits(JDTBasedSpoonCompiler.java:409)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildUnitsAndModel(JDTBasedSpoonCompiler.java:371)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildSources(JDTBasedSpoonCompiler.java:347)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:118)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:101)
	at spoon.Launcher.buildModel(Launcher.java:699)
	at spoon.Launcher.run(Launcher.java:650)
	at cl2t.instrumentation.instrumenters.SpoonInstrumenter.run(SpoonInstrumenter.java:66)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:295)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
	... 37 more
```

I managed to instrument the source code of JUnit4 without this problem, but when running it on Spoon I have this exception.

My launcher configuration is the following: 

```
launcher.getEnvironment().setShouldCompile(true);
launcher.getEnvironment().setAutoImports(true);
launcher.getEnvironment().setNoClasspath(false);

launcher.getEnvironment().setSourceClasspath(/*  an array with all the jar absolute URIs   */);
launcher.addInputResource(/* the spoon src folder absolute uri*/);		

launcher.setBinaryOutputDirectory( /* an "out" folder inside of the spoon directory*/); 		
launcher.setSourceOutputDirectory(/*  a "srcOut" folder inside of the spoon directory */);

launcher.addProcessor(new InvocationProcessor()); //this processor instruments the statements
launcher.addProcessor(new ClassProcessor()); //this processor instruments the classes			
launcher.run();	
```

Is there something wrong with my configuration ? Tell me if you need more data about my code.

Thank You,

Thibault

**Comment by surli** [comment]
Hi @orichalque 

Thanks for the report: before anything, are you sure you're given the directory `src/main/java` and not just `src` to `launcher.addInputResource()`?

Spoon contains a lot of java source code inside the test resources, so it's not really surprising if you have this error when instrumenting the whole code with the resources.

**Comment by orichalque** [comment]
Hey @surli, Thank you for answering.
Indeed I added the whole /src/ folder, because I need to instrument both the source code classes and the test classes. 

Should I specify that I only want to instrument src/test/java and src/main/java ?

**Comment by surli** [comment]
>Should I specify that I only want to instrument src/test/java and src/main/java ?

Exactly

**Comment by surli** [comment]
So, I consider this one as solved. Don't hesitate if you have any other question to open back :-)

**Comment by orichalque** [comment]
Hey @surli ,
I updated the code as you advised me and this exception I had does not happen anymore.

Thank you for your help !
