### ISSUE TITLE
Module Build Exception

### ISSUE THREAD

**Issue by pavanspoon** [INRIA/spoon#1527]
Hi @surli 

we are facing below exception. If we have duplicate class name in different package we are seeing the below exception building the spoon model.  How to overcome this issue if we have different packages having same class name.

spoon.compiler.ModelBuildingException: The type AppTest is already defined
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.reportProblem(JDTBasedSpoonCompiler.java:565)
	at spoon.support.compiler.jdt.TreeBuilderRequestor.acceptResult(TreeBuilderRequestor.java:37)
	at spoon.support.compiler.jdt.TreeBuilderCompiler.buildUnits(TreeBuilderCompiler.java:73)
	at spoon.support.compiler.jdt.JDTBatchCompiler.getUnits(JDTBatchCompiler.java:168)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildUnits(JDTBasedSpoonCompiler.java:412)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildUnitsAndModel(JDTBasedSpoonCompiler.java:374)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildSources(JDTBasedSpoonCompiler.java:350)

Could you hel on this .

**Comment by tdurieux** [comment]
You  probably spoon the spoon output directory

**Comment by surli** [comment]
@pavanspoon is your problem solved here? if so can you close the issue?
