### ISSUE TITLE
The method getResourceA‌sStream(String) is undefined for the type ClassLoader

### ISSUE THREAD

**Issue by DaveJarvis** [INRIA/spoon#1626]
**Replicate**
Spoon the following source file:
``` .java
package com.company.test;

public class Test {
    public Test() {
        final ClassLoader loader = getClass().getClassLoader();
        loader.getResourceA‌sStream("filename.xsl");
    }
}
```

**Configuration Settings**
Using the following configuration settings:
``` .java
        int JDK_VERSION = 7;

        final Environment environment = launcher.getEnvironment();
        environment.setAutoImports(true);
        environment.setCommentEnabled(true);
        environment.setComplianceLevel(JDK_VERSION);
```

**Expected Results**
The source code is loaded successfully.

**Actual Results**
The `JDTBasedSpoonCompiler` cannot find `getResourceAsStream(String)`:

```
spoon.compiler.ModelBuildingException: The method getResourceA‌sStream(String) is undefined for the type ClassLoader at Test.java:5
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.report(JDTBasedSpoonCompiler.java:597)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.reportProblems(JDTBasedSpoonCompiler.java:578)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:126)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:107)
	at spoon.Launcher.buildModel(Launcher.java:705)
```

**Comment by surli** [comment]
Ok apparently it's not a bug of Spoon: you have an invisible character in your method `getResourceAsStream`, when copying it in Vi, it appears like this:

```
getResourceA<200c>sStream
```
