### ISSUE TITLE
ModelBuildingException when build a Maven project. spoon.compiler.ModelBuildingException

### ISSUE THREAD

**Issue by jiajunchen1995** [INRIA/spoon#1780]
Hi:

I am trying to do some static analysis on the spring-boot project. However, when i used the Maven Launcher to build the AST, i receives the following error.

```
Exception in thread "main" spoon.compiler.ModelBuildingException: ResourceManager cannot be resolved to a type at D:\git\spring-boot-1.5.2.RELEASE\spring-boot\src\main\java\org\springframework\boot\context\embedded\undertow\CompositeResourceManager.java:33
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.report(JDTBasedSpoonCompiler.java:581)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.reportProblems(JDTBasedSpoonCompiler.java:562)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:119)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:100)
	at spoon.Launcher.buildModel(Launcher.java:709)
	at ca.mcgill.cs.swevo.logan.coderesolver.MainClass.main(MainClass.java:36)
```
Here is my code snippts
```
String springMainPath = "./spring-boot-1.5.2.RELEASE/spring-boot";
		MavenLauncher launcher = new MavenLauncher(springMainPath, MavenLauncher.SOURCE_TYPE.APP_SOURCE);
		launcher.buildModel();

		List<LoggingInvocation> loggingInvocation = new ArrayList<>();
		CtModel model = launcher.getModel();

```
I've downloaded all the dependencies needed for the project. 

Can you please take a look and help me out? Really appreciated.

Thank you

**Comment by monperrus** [comment]
Maybe you can try in noclasspath mode?

**Comment by tdurieux** [comment]
I think it is an issue our dependency resolver, but I'm not sure if we can do much better :(.

If you don't need to compile the project with Spoon, I would suggest using the no-classpath mode.


```java
String springMainPath = "./spring-boot-1.5.2.RELEASE/spring-boot";
MavenLauncher launcher = new MavenLauncher(springMainPath, MavenLauncher.SOURCE_TYPE.APP_SOURCE);
launcher.getEnvironement().setNoClasspath(true);
CtModel model = launcher.buildModel();

List<LoggingInvocation> loggingInvocation = new ArrayList<>();
```

**Comment by jiajunchen1995** [comment]
Thank you very much for the help, it works for now 😛
