### ISSUE TITLE
Bug: JavaDoc getShortDescription

### ISSUE THREAD

**Issue by Cyclone-1337** [INRIA/spoon#1826]
I created my model with this lines:

        Launcher modelLauncher = new Launcher();
        modelLauncher.getEnvironment().setNoClasspath(true);
        modelLauncher.getEnvironment().setCommentEnabled(true);
        modelLauncher.addInputResource("C:\\spoon\\src\\main\\java\\spoon\\Launcher.java");
        CtModel model = modelLauncher.buildModel();
        JavaDocVisitor visitor = new JavaDocVisitor();
        visitor.scan(model.getRootPackage());`

When i executed this program i got the following exceptions:

> Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 54
	at java.lang.String.substring(Unknown Source)
	at spoon.support.reflect.code.CtJavaDocImpl.getShortDescription(CtJavaDocImpl.java:99)
	at uni.bremen.de.JavaDocVisitor.smellByWords(JavaDocVisitor.java:223)
	at uni.bremen.de.JavaDocVisitor.visitCtJavaDoc(JavaDocVisitor.java:134)
	at spoon.support.reflect.code.CtJavaDocImpl.accept(CtJavaDocImpl.java:113)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:165)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:157)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:141)
	at spoon.reflect.visitor.CtScanner.visitCtMethod(CtScanner.java:550)
	at spoon.support.reflect.declaration.CtMethodImpl.accept(CtMethodImpl.java:70)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:165)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:157)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:141)
	at spoon.reflect.visitor.CtScanner.visitCtClass(CtScanner.java:327)
	at spoon.support.reflect.declaration.CtClassImpl.accept(CtClassImpl.java:68)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:165)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:157)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:141)
	at spoon.reflect.visitor.CtScanner.visitCtPackage(CtScanner.java:640)
	at spoon.support.reflect.declaration.CtPackageImpl.accept(CtPackageImpl.java:56)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:165)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:157)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:141)
	at spoon.reflect.visitor.CtScanner.visitCtPackage(CtScanner.java:639)
	at spoon.support.reflect.declaration.CtPackageImpl.accept(CtPackageImpl.java:56)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:165)
	at uni.bremen.de.Modelscanner.main(Modelscanner.java:19)`

The line 223 in my JavaDocVisitor is this if condition:
`if (!javaDoc.getContent().isEmpty() && wordCounter(javaDoc.getShortDescription()) < minShortLength)`

The same thing is by the method getLongDescription.

**Comment by surli** [comment]
Hi @Cyclone-1337 thanks for reporting this one!
