### ISSUE TITLE
ModelBuildingException when spoon classes with static method calls

### ISSUE THREAD

**Issue by XuSihan** [INRIA/spoon#1933]
I am trying to analyze the source code of apache cassandra.
```java
 Launcher launcher = new Launcher();
 launcher.addInputResource("path\\to\\cassandra");
 launcher.buildModel(); <-- this crashes
```
Here's the exception:

2018-03-30 11:27:49,893 ERROR spoon.support.compiler.jdt.JDTTreeBuilder - Could not find declaration for variable Pair at (/Users/Sihan/eclipse-workspace/Test/resources/cassandra/src/java/org/apache/cassandra/schema/Schema.java:152)
2018-03-30 11:27:49,902 ERROR spoon.support.compiler.jdt.JDTTreeBuilder - Could not find declaration for variable Pair at (/Users/Sihan/eclipse-workspace/Test/resources/cassandra/src/java/org/apache/cassandra/schema/Schema.java:177)
2018-03-30 11:27:49,913 ERROR spoon.support.compiler.jdt.JDTTreeBuilder - Could not find declaration for variable Pair at (/Users/Sihan/eclipse-workspace/Test/resources/cassandra/src/java/org/apache/cassandra/schema/Schema.java:191)
2018-03-30 11:27:49,926 ERROR spoon.support.compiler.jdt.JDTTreeBuilder - Could not find declaration for variable Pair at (/Users/Sihan/eclipse-workspace/Test/resources/cassandra/src/java/org/apache/cassandra/schema/Schema.java:207)
2018-03-30 11:27:49,936 ERROR spoon.support.compiler.jdt.JDTTreeBuilder - Could not find declaration for variable Pair at (/Users/Sihan/eclipse-workspace/Test/resources/cassandra/src/java/org/apache/cassandra/schema/Schema.java:290)
2018-03-30 11:27:52,211 ERROR spoon.support.compiler.jdt.JDTTreeBuilder - Could not find declaration for variable e at (/Users/Sihan/eclipse-workspace/Test/resources/cassandra/src/java/org/apache/cassandra/metrics/ClientMetrics.java:47)
2018-03-30 11:27:52,561 ERROR spoon.support.compiler.jdt.JDTTreeBuilder - Could not find declaration for variable Metrics at (/Users/Sihan/eclipse-workspace/Test/resources/cassandra/src/java/org/apache/cassandra/metrics/MessagingMetrics.java:56)
2018-03-30 11:27:52,572 ERROR spoon.support.compiler.jdt.JDTTreeBuilder - Could not find declaration for variable Metrics at (/Users/Sihan/eclipse-workspace/Test/resources/cassandra/src/java/org/apache/cassandra/metrics/MessagingMetrics.java:71)
2018-03-30 11:27:55,732 ERROR spoon.support.compiler.jdt.JDTTreeBuilder - Could not find declaration for variable ByteBuffer at (/Users/Sihan/eclipse-workspace/Test/resources/cassandra/test/unit/org/apache/cassandra/io/util/BufferedDataOutputStreamTest.java:632)
2018-03-30 11:27:55,751 ERROR spoon.support.compiler.jdt.JDTTreeBuilder - Could not find declaration for variable e at (/Users/Sihan/eclipse-workspace/Test/resources/cassandra/test/unit/org/apache/cassandra/io/util/BufferedDataOutputStreamTest.java:640)
...
...
Exception in thread "main" spoon.compiler.ModelBuildingException: The import com.google cannot be resolved at C:\Users\Sihan\eclipse-workspace\Test\resources\cassandra\src\java\org\apache\cassandra\utils\SyncUtil.java:33
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.report(JDTBasedSpoonCompiler.java:582)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.reportProblems(JDTBasedSpoonCompiler.java:563)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:118)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:99)
	at spoon.Launcher.buildModel(Launcher.java:720)
	at processor.test3.main(test3.java:29)

**Comment by XuSihan** [comment]
Here's some of the classes that causes the crash:

```java
...
import org.apache.cassandra.utils.Pair;

    private void loadNew(KeyspaceMetadata ksm)
    {
        ksm.tablesAndViews()
           .forEach(metadata -> metadataRefs.put(metadata.id, new TableMetadataRef(metadata)));

        ksm.tables
           .indexTables()
           .forEach((name, metadata) -> indexMetadataRefs.put(Pair.create(ksm.name, name), new TableMetadataRef(metadata)));
    }
```
**Pair,create** is a static method call:

**Comment by XuSihan** [comment]
Pair,create() is a static method call:

```java
package org.apache.cassandra.utils;

import com.google.common.base.Objects;

public class Pair<T1, T2>
{
    public final T1 left;
    public final T2 right;

    protected Pair(T1 left, T2 right)
    {
        this.left = left;
        this.right = right;
    }
    public static <X, Y> Pair<X, Y> create(X x, Y y)
    {
        return new Pair<X, Y>(x, y);
    }
}
```

**Comment by pvojtechovsky** [comment]
Welcome!

> Exception in thread "main" spoon.compiler.ModelBuildingException: The import com.google cannot be resolved

It means that you are analyzing sources which imports package `com.google`, but this package is not available on class path of the Spoon compiler.
A) add that external library into class path
B) add sources of that library into to be analyze spoon sources
C) switch spoon into `no classpath` mode
```java
Launcher launcher = new Launcher();
...
launcher.getEnvironment().setNoClasspath(true);
...
```

The correct solution depends on your use case.

Or do you think there is other problem? ... it sounds like that looking at your other comments ... but I do not understand it yet ;-)

**Comment by XuSihan** [comment]
Many thanks!

My configuration of source classpath is like this:
```java
String [] str = new String [4];
str[0] = "C:\\Users\\Sihan\\eclipse-workspace\\Test\\resources\\cassandra\\lib";
str[1] = "C:\\Users\\Sihan\\eclipse-workspace\\Test\\resources\\cassandra\\build\\lib\\sources";
str[2] = "C:\\Users\\Sihan\\eclipse-workspace\\Test\\resources\\cassandra\\build\\lib\\jars";
str[3] = "C:\\Users\\Sihan\\.m2\\repository";
launcher.getEnvironment().setSourceClasspath(str);

launcher.buildModel();
```
There's slf4j-api-1.7.25.jar in the first path. However, it still gives me an exception -- "The import org.slf4j.Logger cannot be resolved".

Is there any problem with the way I configure the source classpath?

Thank you! :)
Sihan

**Comment by surli** [comment]
> str[0] = "C:\\Users\\Sihan\\eclipse-workspace\\Test\\resources\\cassandra\\lib";

You have to specify the absolute path of all jars in the classpath: Spoon won't explore a directory to get the jars. 
So you have to specify something like:

str[0] = "C:\\Users\\Sihan\\eclipse-workspace\\Test\\resources\\cassandra\\lib\\slf4j-api-1.7.25.jar";

**Comment by XuSihan** [comment]
Many thanks to you! 
My problem has been resloved. I'll close this issue. :)
