### ISSUE TITLE
NPE  with generic types

### ISSUE THREAD

**Issue by mehdi-kaytoue** [INRIA/spoon#1962]
Dear Spoon team, 

I am having a bug when building the spoon model of one of my projects.
I replicated it below with dummy names.

```
public class SpoonBug<F extends AClass>
{
    protected void aMethod()
    {
        //String s = AClass.A_FIELD; // This line alone: OK
        String s = F.A_FIELD;         // This line alone: NPE, see below
    }
}
```
What is weird, is that, the original code (without dummy names),
compile and works as expected, no problem with Ecplise editor, 
just that autocomplete on "F." returns nothing, but works with "AClass."

I manually changed all "F." in my code by their "AClass" in the meantime. 
Thanks for your help and the great API you provide!
Best regards,
Mehdi 

------
```
Exception in thread "main" java.lang.NullPointerException
	at spoon.support.compiler.jdt.JDTTreeBuilderQuery.isValidProblemBindingField(JDTTreeBuilderQuery.java:213)
	at spoon.support.compiler.jdt.JDTTreeBuilderHelper.createTargetFieldAccess(JDTTreeBuilderHelper.java:565)
	at spoon.support.compiler.jdt.JDTTreeBuilderHelper.createVariableAccess(JDTTreeBuilderHelper.java:301)
	at spoon.support.compiler.jdt.JDTTreeBuilder.visit(JDTTreeBuilder.java:1315)
	at org.eclipse.jdt.internal.compiler.ast.QualifiedNameReference.traverse(QualifiedNameReference.java:1134)
	at org.eclipse.jdt.internal.compiler.ast.LocalDeclaration.traverse(LocalDeclaration.java:314)
	at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.traverse(MethodDeclaration.java:355)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.traverse(TypeDeclaration.java:1367)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.traverse(CompilationUnitDeclaration.java:778)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.traverse(CompilationUnitDeclaration.java:739)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildModel(JDTBasedSpoonCompiler.java:414)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildUnitsAndModel(JDTBasedSpoonCompiler.java:362)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildSources(JDTBasedSpoonCompiler.java:335)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:116)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:99)
	at spoon.Launcher.buildModel(Launcher.java:720)
	at [fr.... my applic]
```

**Comment by surli** [comment]
Hi @mehdi-kaytoue 

Thanks for reporting this one, we'll have a look at it!
Just for us to know: which version of Spoon exactly do you use?

**Comment by mehdi-kaytoue** [comment]
Thanks for you replay @surli !
I am using version 6.2.0

```
<dependency>
      <groupId>fr.inria.gforge.spoon</groupId>
      <artifactId>spoon-core</artifactId>
      <version>6.2.0</version>
      <scope>compile</scope>
</dependency>
```

**Comment by monperrus** [comment]
Does the bug happen with 6.3.0-SNAPSHOT?

**Comment by mehdi-kaytoue** [comment]
I can't reproduce it now. Perfect! Thanks.
