### ISSUE TITLE
Spoon 6.3.0: NPE in spoon.support.compiler.jdt.ReferenceBuilder.getTypeReference(ReferenceBuilder.java:543)

### ISSUE THREAD

**Issue by surli** [INRIA/spoon#1994]
Steps to reproduce:
Spoon 6.3.0
Code coming from: https://github.com/runelite/runelite/pull/2844
Classpath: computed with `mvn dependency:build-classpath`
Full classpath mode. 

Stacktrace:
```
java.lang.NullPointerException: null
        at spoon.support.compiler.jdt.ReferenceBuilder.getTypeReference(ReferenceBuilder.java:543)
        at spoon.support.compiler.jdt.ReferenceBuilder.getTypeReference(ReferenceBuilder.java:482)
        at spoon.support.compiler.jdt.ReferenceBuilder.getExecutableReference(ReferenceBuilder.java:420)
        at spoon.support.compiler.jdt.JDTTreeBuilder.visit(JDTTreeBuilder.java:786)
        at org.eclipse.jdt.internal.compiler.ast.QualifiedAllocationExpression.traverse(QualifiedAllocationExpression.java:659)
        at org.eclipse.jdt.internal.compiler.ast.FieldDeclaration.traverse(FieldDeclaration.java:341)
        at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.traverse(TypeDeclaration.java:1358)
        at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.traverse(CompilationUnitDeclaration.java:778)
        at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.traverse(CompilationUnitDeclaration.java:739)
        at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildModel(JDTBasedSpoonCompiler.java:414)
        at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildUnitsAndModel(JDTBasedSpoonCompiler.java:362)
        at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildSources(JDTBasedSpoonCompiler.java:335)
        at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:116)
        at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:99)
```

**Comment by surli** [comment]
The bug is related to this file: https://github.com/iguaan/runelite/blob/slayer-infobox/runelite-client/src/main/java/net/runelite/client/plugins/farmingtracker/PatchImplementation.java

In `ReferenceBuilder#getExecutableReference(AllocationExpression allocationExpression)` the `allocationExpression` has no binding and no attached declared type, but it as an anonymousType and this one should be used.

**Comment by surli** [comment]
Apparently the NPE does not occur anymore with last snapshot.
