### ISSUE TITLE
Spoon-Gradle-Plugin : bug on windows

### ISSUE THREAD

**Issue by m3ftah** [INRIA/spoon#2062]
I got the following stacktrace when running on windows, on linux it works fine:
```
Caused by: spoon.compiler.InvalidClassPathException: C does not exist, it is not a valid folder
        at spoon.support.StandardEnvironment.verifySourceClasspath(StandardEnvironment.java:424)
        at spoon.support.StandardEnvironment.setSourceClasspath(StandardEnvironment.java:414)
        at spoon.compiler.Environment$setSourceClasspath$3.call(Unknown Source)
        at fr.inria.gforge.spoon.SpoonAndroidTask.configureEnvironment(SpoonAndroidTask.groovy:38)
        at fr.inria.gforge.spoon.SpoonAndroidCheckTask.super$4$configureEnvironment(SpoonAndroidCheckTask.groovy)
        at fr.inria.gforge.spoon.SpoonAndroidCheckTask.configureEnvironment(SpoonAndroidCheckTask.groovy:9)
        at fr.inria.gforge.spoon.SpoonAndroidCheckTask$configureEnvironment.callCurrent(Unknown Source)
        at fr.inria.gforge.spoon.SpoonAndroidTask.run(SpoonAndroidTask.groovy:52)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:784)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:751)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
        ... 103 more
```

**Comment by surli** [comment]
The bug has been fixed. I will release the plugin soon.
