### ISSUE TITLE
Question: Any windows developers here?

### ISSUE THREAD

**Issue by zielint0** [INRIA/spoon#2108]
Currently I use Windows 7 and the problem is that tests do not pass after mvn test.

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.525 s
[INFO] Finished at: 2018-06-26T20:42:24+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.21.0:test (default-test) on project spoon-core: There are test failures.
[ERROR]
[ERROR] Please refer to D:\projects\spoon\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] There was an error in the forked process
[ERROR] Test (wrong name: maven-launcher/very-simple/target/classes/Test)
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process
[ERROR] Test (wrong name: maven-launcher/very-simple/target/classes/Test)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:658)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:533)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:278)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:244)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1149)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:978)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:854)
[ERROR]         at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR]         at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR]         at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR]         at org.apache.maven.cli.MavenCli.execute(MavenCli.java:954)
[ERROR]         at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
[ERROR]         at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```

Are there any Spoon devs on Windows?

**Comment by pvojtechovsky** [comment]
yes, I am the one. But I seldom run all tests. I usually run only tests which are related to the new PR and then let CI to check everything else.

**Comment by surli** [comment]
I'll check if I can setup a slave on our jenkins CI to build on windows to assess that on the long term.

**Comment by zielint0** [comment]
@pvojtechovsky Are you able to successfully run all tests on Windows?

@surli Thank you in advance! It would be extremely useful!

**Comment by msteinbeck** [comment]
@surli If you need to install dependencies, https://chocolatey.org/ may help.

**Comment by surli** [comment]
@pvojtechovsky do you use a specific configuration?
We got indeed test failures when running `mvn test` on windows: https://ci.inria.fr/sos/job/spoon-windows/lastBuild/testReport/

**Comment by pvojtechovsky** [comment]
> Are you able to successfully run all tests on Windows?

I have not try it for long time. I am sure that all tests which fails by zielint0 will fails be me too.

> I have the feeling that most errors are coming because of the usage of a wrong line separator character in the tests.

That is good feeling. Whenever I came to some problem it was always wrong line separator.

> do you use a specific configuration?

no special configuration. I am not using maven to run tests, but Eclipse integrated junit runner ... and I am sure some tests will fail for me too.

**Comment by zielint0** [comment]
@pvojtechovsky 
Thank you for your feedback! At last I am not alone ;-)
BTW. I have added my log (first message).

**Comment by surli** [comment]
@zielint0 which JDK/Maven version are you using?
Spoon should compile and run test properly on Maven 3.5.2 and JDK 8/9/10.

**Comment by zielint0** [comment]
@surli 
I have JDK 10 (x64), MVN 3.5.4, Windows 7 64-bit.

javac --version
```
javac 10.0.1
```

java --version
```
java 10.0.1 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)
```

mvn --version
```
Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T20:33:14+02:00)
Maven home: C:\Tools\mvn\bin\..
Java version: 10.0.1, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-10.0.1
Default locale: en_US, platform encoding: Cp1250
OS name: "windows 7", version: "6.1", arch: "amd64", family: "windows"
```

**Comment by surli** [comment]
> Do you have any hint for me wht could be a reason?

It might be the version of Maven. We did not check to build it using Maven 3.5.4 yet: all our run are using 3.5.2 or 3.3.9. I'll try to use this version on a Jenkins job to see.

**Comment by surli** [comment]
So I just checked and there's no problem to build Spoon using Java 10 and Maven 3.5.4. Here's the full log of the job: https://ci.inria.fr/sos/job/spoon-jdk10-mvn354/2/consoleFull

The fact that you had 0 tests run is really weird. Maybe have a look on the `target/surefire-reports` directory to get some logs.

**Comment by zielint0** [comment]
@surli 

Hi Simon
Thank you for your time and patience!

Investigation of surefire-reports brought me to [Maven Junit tests “noClassDefFoundError”](https://stackoverflow.com/questions/13970559/maven-junit-tests-noclassdeffounderror) and conclusion that there is something wrong with paths.

I clonned a vanilla repo and to my surprise all tests without one passed.

```
[INFO] Running spoon.test.imports.ImportScannerTest
[ERROR] Tests run: 6, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 7.75 s <<< FAILURE! - in spoon.test.imports.ImportScannerTest
[ERROR] testImportOnSpoon(spoon.test.imports.ImportScannerTest)  Time elapsed: 7.495 s  <<< ERROR!
java.nio.charset.MalformedInputException: Input length = 1
        at spoon.test.imports.ImportScannerTest.testImportOnSpoon(ImportScannerTest.java:76)

[ERROR] Errors:
[ERROR]   ImportScannerTest.testImportOnSpoon:76 » MalformedInput Input length = 1
[INFO]
[ERROR] Tests run: 1526, Failures: 0, Errors: 1, Skipped: 3
```

The project has been broken because I changed default options while importing to IntelliJ IDEA IDE.

**Comment by surli** [comment]
Ok for me the general issue is fixed. 
The test failure you got is weird: it never happens on our side.
Open a new ticket if the problem persists.
