### ISSUE TITLE
isSubTypeOf on TypeReference is not robust against missing declarations

### ISSUE THREAD

**Issue by Tallic** [INRIA/spoon#2288]
`a.isSubTypeOf(b)` from `TypeReference` is not robust and throws a `NullPointerException` if the declaration of `a` is not available.

```
Caused by: java.lang.NullPointerException
	at spoon.support.reflect.reference.CtTypeParameterReferenceImpl.isSubtypeOf(CtTypeParameterReferenceImpl.java:278)
	at at.jku.isse.gradient.java.AsgRelationshipTransformer$Transformer.createElementType(AsgRelationshipTransformer.kt:393)
	at at.jku.isse.gradient.java.AsgRelationshipTransformer$Transformer.visitCtFieldReference(AsgRelationshipTransformer.kt:119)
	at spoon.support.reflect.reference.CtFieldReferenceImpl.accept(CtFieldReferenceImpl.java:58)
	at at.jku.isse.gradient.java.SpoonVisitor.scan(SpoonVisitor.kt:16)
	at at.jku.isse.gradient.java.AsgRelationshipTransformer$Transformer.scan(AsgRelationshipTransformer.kt:62)
	at at.jku.isse.gradient.java.SpoonVisitor.scan(SpoonVisitor.kt:10)
	at at.jku.isse.gradient.java.AsgRelationshipTransformer$Transformer$visitCtTypeReference$$inlined$let$lambda$1.accept(AsgRelationshipTransformer.kt:83)
	at at.jku.isse.gradient.java.AsgRelationshipTransformer$Transformer$visitCtTypeReference$$inlined$let$lambda$1.accept(AsgRelationshipTransformer.kt:26)
	at java.util.Optional.ifPresent(Optional.java:159)
	at at.jku.isse.gradient.java.AsgRelationshipTransformer$Transformer.visitCtTypeReference(AsgRelationshipTransformer.kt:73)
	at spoon.support.reflect.reference.CtTypeReferenceImpl.accept(CtTypeReferenceImpl.java:78)
	at at.jku.isse.gradient.java.SpoonVisitor.scan(SpoonVisitor.kt:16)
	at at.jku.isse.gradient.java.AsgRelationshipTransformer$Transformer.scan(AsgRelationshipTransformer.kt:62)
	at at.jku.isse.gradient.java.AsgRelationshipTransformer.transform(AsgRelationshipTransformer.kt:20)
	at at.jku.isse.gradient.java.ModelTransformer$transform$7.accept(ModelTransformer.kt:38)
	at at.jku.isse.gradient.java.ModelTransformer$transform$7.accept(ModelTransformer.kt:11)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.execLocalTasks(ForkJoinPool.java:1040)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1058)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Versions**
Spoon 7.0.0 (but also in early versions)

**Comment by surli** [comment]
Hi! Thanks for the report! Would you create a unit test for reproducing the bug: it would help us to fix it :)

**Comment by Tallic** [comment]
Hope I'll find some time on the weekend.

The concrete problem is that `CtTypeParameterreferenceImpl` uses `getTypeDeclaration()`  which in turn uses `getDeclaration()` which may return null.
The dereference to `isSubtypeOf` is then unchecked leading to the issue.
