### ISSUE TITLE
NullPointerException while building the model

### ISSUE THREAD

**Issue by leventov** [INRIA/spoon#233]
```
Caused by: java.lang.NullPointerException
        at spoon.support.compiler.jdt.JDTTreeBuilder.createExecutableReferenceExpression(JDTTreeBuilder.java:1494)
        at spoon.support.compiler.jdt.JDTTreeBuilder.visit(JDTTreeBuilder.java:1484)
        at org.eclipse.jdt.internal.compiler.ast.ReferenceExpression.traverse(ReferenceExpression.java:755)
        at spoon.support.compiler.jdt.JDTTreeBuilder.visit(JDTTreeBuilder.java:2170)
        at org.eclipse.jdt.internal.compiler.ast.MessageSend.traverse(MessageSend.java:1005)
        at spoon.support.compiler.jdt.JDTTreeBuilder.visit(JDTTreeBuilder.java:2250)
        at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.traverse(MethodDeclaration.java:317)
        at spoon.support.compiler.jdt.JDTTreeBuilder.visit(JDTTreeBuilder.java:2881)
        at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.traverse(TypeDeclaration.java:1338)
        at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.traverse(CompilationUnitDeclaration.java:745)
        at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.traverse(CompilationUnitDeclaration.java:706)
        at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildSources(JDTBasedSpoonCompiler.java:229)
        at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:505)
        at spoon.Launcher.buildModel(Launcher.java:751)
        at spoon.Launcher.run(Launcher.java:702)
```

Using Spoon 4.1.0, java version is 1.8.0_45.

This is for a unit test. Iteresting, that when I run this test within Intellij Idea, it succeds, but when I'm going through `mvn test` in command line, it fails with the above stack trace.

**Comment by GerardPaligot** [comment]
Can you show the test case and what is your OS?

**Comment by leventov** [comment]
```
package sg2;

import org.junit.Test;
import spoon.Launcher;
import spoon.reflect.declaration.CtClass;
import spoon.reflect.declaration.CtPackage;
import spoon.reflect.factory.Factory;

import java.util.List;

public class CompilerTest {
    
    static Factory getFactoryForTest() {
        Launcher spoon = new Launcher();
        spoon.getFactory().getEnvironment().setComplianceLevel(8);
        spoon.addInputResource("C:/Users/path/to/sg2/project/src/test/java");
//                new File(StageGraphCompilationTest.class
//                        .getProtectionDomain().getCodeSource()
//                        .getLocation().getPath()).getParentFile()));
        try {
            spoon.run();
            for(CtPackage p : spoon.getFactory().Package().getAll()) {
                System.out.println("package: "+p.getQualifiedName());
            }
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
        return spoon.getFactory();
    }
    
    @Test
    public void test() {
        CompilationNode root = CompilationNode.root(getFactoryForTest());
        root.addClassToMerge(PartSub.class);
        CompilationNode child = root.createChild();
        child.addClassToMerge(Part1.class);
        child.addClassToMerge(Part2.class);
        Compiler compiler = new Compiler(root);
        List<CtClass<?>> resultClasses = compiler.compile();
        resultClasses.forEach(System.out::println);
    }
}
```

OS is Windows 7.

**Comment by leventov** [comment]
Gradle also runs the test normally.

**Comment by GerardPaligot** [comment]
That's weird and, unfortunately, I can't help you if I don't have the source code concerned by this error. You seems to have a NPE when you try to build an executable reference expression but I can't guess why. 

Do you know what is the source code concerned by this error? Maybe you don't use the same maven and Java version in our IntelliJ and in command line, what's the result of `mvn -v`?

**Comment by leventov** [comment]
```
Apache Maven 3.2.2 (45f7c06d68e745d05611f7fd14efb6594181933e; 2014-06-17T14:51:42+01:00)
Maven home: C:\Program Files\Maven
Java version: 1.8.0_45, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8\jre
Default locale: ru_RU, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "dos"
```

I suspect some classes from maven classpath shade some spoon dependencies. Fortunately this issue is not pressing now, because I'm able to build and install project via gradle.

**Comment by leventov** [comment]
This is for 99% some issue with JDT compiler, but since I managed to workaround it by executing gradle and nobody have time and effort to dig into this issue, I think it is not constructive to keep this issue open.
