### ISSUE TITLE
cannot load class: spoon.reflect.annotations.PropertySetter; When try to build a pattern from a specific method

### ISSUE THREAD

**Issue by Jianwei-Wu-1** [INRIA/spoon#2637]
Hi everyone,

I meet a problem when I try to build a pattern from a method that contains "try-catch" statements.

My code:
`        Pattern try_catch_model = PatternBuilder.
                create(new PatternBuilderHelper(first_try_catch_class).
                        setBodyOfMethod(first_try_catch.getSimpleName()).
                        getPatternElements()).
                configurePatternParameters().
                build();
        System.out.println("First try catch block: " + try_catch_model.toString());
`
I checked the CtType and the CtMethod for the pattern builder, and they are actually OK.
And I add spoon from the Maven central. 
The IDE I'm using is IntelliJ Idea 2017.3.
I also tried "TemplateMacther", it didn't work, too.
However, when I run it, it keeps giving me the following fatal error:

`cannot load class: spoon.reflect.annotations.PropertySetter
spoon.support.SpoonClassNotFoundException: cannot load class: spoon.reflect.annotations.PropertySetter
	at spoon.support.reflect.reference.CtTypeReferenceImpl.findClass(CtTypeReferenceImpl.java:159)
	at spoon.support.reflect.reference.CtTypeReferenceImpl.getActualClass(CtTypeReferenceImpl.java:141)
	at spoon.support.reflect.declaration.CtAnnotationImpl.getActualAnnotation(CtAnnotationImpl.java:523)
	at spoon.metamodel.Metamodel.getRoleOfMethod(Metamodel.java:367)
	at spoon.metamodel.Metamodel.lambda$addFieldsOfType$5(Metamodel.java:463)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1080)
	at spoon.metamodel.Metamodel.addFieldsOfType(Metamodel.java:460)
	at spoon.metamodel.Metamodel.initializeConcept(Metamodel.java:443)
	at spoon.metamodel.Metamodel.lambda$getOrCreateConcept$3(Metamodel.java:418)
	at spoon.metamodel.Metamodel.getOrCreate(Metamodel.java:523)
	at spoon.metamodel.Metamodel.getOrCreateConcept(Metamodel.java:416)
	at spoon.metamodel.Metamodel.<init>(Metamodel.java:271)
	at spoon.metamodel.Metamodel.getInstance(Metamodel.java:222)
	at spoon.pattern.internal.node.ElementNode.create(ElementNode.java:61)
	at spoon.pattern.internal.node.ElementNode.create(ElementNode.java:152)
	at spoon.pattern.internal.node.ElementNode.lambda$create$0(ElementNode.java:88)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at spoon.pattern.internal.node.ElementNode.create(ElementNode.java:88)
	at spoon.pattern.PatternBuilder.<init>(PatternBuilder.java:122)
	at spoon.pattern.PatternBuilder.create(PatternBuilder.java:73)
	at TestPattern.TryCatchPattern.fetchAllModels(TryCatchPattern.java:108)`

Could someone point out what I did wrong there? 
Thank you in advance!

**Comment by Jianwei-Wu-1** [comment]
Thank you for your reply in such a short time!

The complete stack trace is the following part:

`cannot load class: spoon.reflect.annotations.PropertySetter
spoon.support.SpoonClassNotFoundException: cannot load class: spoon.reflect.annotations.PropertySetter
	at spoon.support.reflect.reference.CtTypeReferenceImpl.findClass(CtTypeReferenceImpl.java:159)
	at spoon.support.reflect.reference.CtTypeReferenceImpl.getActualClass(CtTypeReferenceImpl.java:141)
	at spoon.support.reflect.declaration.CtAnnotationImpl.getActualAnnotation(CtAnnotationImpl.java:523)
	at spoon.metamodel.Metamodel.getRoleOfMethod(Metamodel.java:367)
	at spoon.metamodel.Metamodel.lambda$addFieldsOfType$5(Metamodel.java:463)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1080)
	at spoon.metamodel.Metamodel.addFieldsOfType(Metamodel.java:460)
	at spoon.metamodel.Metamodel.initializeConcept(Metamodel.java:443)
	at spoon.metamodel.Metamodel.lambda$getOrCreateConcept$3(Metamodel.java:418)
	at spoon.metamodel.Metamodel.getOrCreate(Metamodel.java:523)
	at spoon.metamodel.Metamodel.getOrCreateConcept(Metamodel.java:416)
	at spoon.metamodel.Metamodel.<init>(Metamodel.java:271)
	at spoon.metamodel.Metamodel.getInstance(Metamodel.java:222)
	at spoon.pattern.internal.node.ElementNode.create(ElementNode.java:61)
	at spoon.pattern.internal.node.ElementNode.create(ElementNode.java:152)
	at spoon.pattern.internal.node.ElementNode.lambda$create$0(ElementNode.java:88)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at spoon.pattern.internal.node.ElementNode.create(ElementNode.java:88)
	at spoon.pattern.PatternBuilder.<init>(PatternBuilder.java:122)
	at spoon.template.TemplateBuilder$PatternBuilder.<init>(TemplateBuilder.java:58)
	at spoon.template.TemplateBuilder.createPattern(TemplateBuilder.java:110)
	at spoon.template.TemplateMatcher.<init>(TemplateMatcher.java:72)
	at spoon.template.TemplateMatcher.<init>(TemplateMatcher.java:62)
	at TestPattern.TryCatchPattern.fetchModel(TryCatchPattern.java:96)
	at TestPattern.TestPatternFinder.fetchTestWithTryCatch(TestPatternFinder.java:31)
	at evaluate_bad_test_names.EvaluateBadTestNames.actionPerformed(EvaluateBadTestNames.java:159)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:220)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:237)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:321)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:911)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:136)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:311)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:130)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:111)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:120)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:122)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:130)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.JToggleButton$ToggleButtonModel.setPressed(JToggleButton.java:308)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at com.apple.laf.ScreenMenuItemCheckbox.itemStateChanged(ScreenMenuItemCheckbox.java:193)
	at java.awt.CheckboxMenuItem.processItemEvent(CheckboxMenuItem.java:389)
	at java.awt.CheckboxMenuItem.processEvent(CheckboxMenuItem.java:357)
	at java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:351)
	at java.awt.MenuComponent.dispatchEvent(MenuComponent.java:339)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:761)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: spoon.reflect.annotations.PropertySetter
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at spoon.support.reflect.reference.CtTypeReferenceImpl.findClass(CtTypeReferenceImpl.java:157)
	... 75 more`

In the console, there is only the following part, and they are showing the correct class and method name:

`
Class: DepositAccountTest
First Name: testForBankException
log4j:WARN No appenders could be found for logger (spoon.Launcher).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
`

This project is for an IntelliJ Plugin, and the template I tried to use is like this, a JUnit test case:

<img width="425" alt="1" src="https://user-images.githubusercontent.com/27785828/46619302-c7083b00-caef-11e8-859f-0b3c97b03e9a.png">

However, when I run the plugin, this window pops out and it shows an error, which contains the detailed information mentioned above:

<img width="988" alt="2" src="https://user-images.githubusercontent.com/27785828/46619374-f7e87000-caef-11e8-966d-2fcbfca05f2c.png">

Here is how I import Spoon, from maven central:

<img width="576" alt="3" src="https://user-images.githubusercontent.com/27785828/46619669-ae4c5500-caf0-11e8-8a78-ab732fd55d81.png">

I double-check the project setup, and I think there is no custom class loader, except I give JVM more memory to run the project. 
Here is the code I wrote to get the CtType and CtMethod, which is very similar to the examples from your website.

`
for (every CtType from the whole project){
for (every CtMethod from each CtType){                            
for (CtStatement statement : method.getBody().getStatements()){
                                if (statement.getClass().equals(CtTryImpl.class)){
                                    first_try_catch = method;
                                    first_try_catch_class = type;
                                }
...
` 

Thanks again for your help!
Jianwei Wu

**Comment by pvojtechovsky** [comment]
Hi Jianwei,

I suggest to put breakpoint to `/spoon-core/src/main/java/spoon/support/StandardEnvironment.java` method `getInputClassLoader()` and to check it there.
* What value is in `Thread.currentThread().getContextClassLoader()` ?
* What value is in `this.getClass().getClassLoader()`?

Note:  we need a class loader which can load spoon classes ... but in your case when you run the code somehow directly from intelij, there is probably different class loader.

you can also try to replace
```java
inputClassloader = new URLClassLoader(urlClasspath(), Thread.currentThread().getContextClassLoader());
//by
inputClassloader = new URLClassLoader(urlClasspath(), this.getClass().getClassLoader());
```

Pavel

**Comment by Jianwei-Wu-1** [comment]
> Hi Jianwei,
> 
> I suggest to put breakpoint to `/spoon-core/src/main/java/spoon/support/StandardEnvironment.java` method `getInputClassLoader()` and to check it there.
> 
> * What value is in `Thread.currentThread().getContextClassLoader()` ?
> * What value is in `this.getClass().getClassLoader()`?
> 
> Note: we need a class loader which can load spoon classes ... but in your case when you run the code somehow directly from intelij, there is probably different class loader.
> 
> you can also try to replace
> 
> ```java
> inputClassloader = new URLClassLoader(urlClasspath(), Thread.currentThread().getContextClassLoader());
> //by
> inputClassloader = new URLClassLoader(urlClasspath(), this.getClass().getClassLoader());
> ```
> 
> Pavel

Hi Pavel:
@pvojtechovsky 

Thanks a lot for your help! 
I changed the `inputClassloader`, and it works!
Now I can use the generated pattern to build other staff.

Jianwei Wu
