### ISSUE TITLE
feat: add support for ${java.version} in pom.xml

### ISSUE THREAD

**Issue by lodart** [INRIA/spoon#2714]
Hi ! 
I have an issue creating a MavenLauncher for projects that have `${java.version}` in their `POM.xml`.

```
Exception in thread "main" java.lang.NumberFormatException: For input string: ""
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:662)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at spoon.support.compiler.SpoonPom.getSourceVersion(SpoonPom.java:259)
	at spoon.MavenLauncher.init(MavenLauncher.java:171)
	at spoon.MavenLauncher.<init>(MavenLauncher.java:119)
	at spoon.MavenLauncher.<init>(MavenLauncher.java:60)
	at org.rlebouc.Main.main(Main.java:21)
```
Replacing it with `1.8` for example seems to work around.

Thank you for your help !

**Comment by monperrus** [comment]
Do you use the spoon-maven-plugin or the java class MavenLauncher?

**Comment by lodart** [comment]
Sorry, I got confused : I use the MavenLauncher java class. I'll edit the title of the issue.

**Comment by monperrus** [comment]
That's probably not to hard to support. Would you try your first pull request?

**Comment by lodart** [comment]
Yes, absolutely, but I'm not sure I can do it. I'll have a look.

**Comment by surli** [comment]
@lodart as a first move, I'd check what happens in this method: https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/support/compiler/SpoonPom.java#L202-L211 with a breakpoint on the return.

**Comment by lodart** [comment]
The problem seems to come from here : 
https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/support/compiler/SpoonPom.java#L259
If `${java.version}` is set to `1.X` it works well, the first chars `1.` being removed, it remains only the version number. But if it is set to `11` then it remains only an empty string.

**Comment by nharrand** [comment]
Or just check if it contains a ".".
