### ISSUE TITLE
Questions working on examples of using Spoon

### ISSUE THREAD

**Issue by ftomassetti** [INRIA/spoon#2761]
1. To use Spoon I need to have all dependencies, right? I cannot just process my source code if I do not have all JARs, correct?
2. I am trying to use Spoon on a module of javaparser, which has zero dependencies, but I get an error

```kotlin
import spoon.Launcher

fun main(args: Array<String>) {
    val launcher = Launcher()
    launcher.addInputResource("codebases/jp/javaparser-core")
    launcher.environment.noClasspath = true
    val model = launcher.buildModel()
}
```

I get this:
```
Exception in thread "main" spoon.compiler.ModelBuildingException: The type JavaParserBuild is already defined
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.reportProblem(JDTBasedSpoonCompiler.java:609)
	at spoon.support.compiler.jdt.TreeBuilderRequestor.acceptResult(TreeBuilderRequestor.java:38)
	at spoon.support.compiler.jdt.TreeBuilderCompiler.buildUnits(TreeBuilderCompiler.java:97)
	at spoon.support.compiler.jdt.JDTBatchCompiler.getUnits(JDTBatchCompiler.java:266)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildUnits(JDTBasedSpoonCompiler.java:443)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildUnitsAndModel(JDTBasedSpoonCompiler.java:387)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildSources(JDTBasedSpoonCompiler.java:339)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:122)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:105)
	at spoon.Launcher.buildModel(Launcher.java:767)
	at SimpleAnalysisKt.main(SimpleAnalysis.kt:7)
```

Any idea about the reson for this?

**Comment by pvojtechovsky** [comment]
> To use Spoon I need to have all dependencies, right? I cannot just process my source code if I do not have all JARs, correct?

Spoon has two modes:
* normal - all dependencies are needed
* noClasspath - dependencies can be missing

In your example there is already defined noclasspath - OK

>  The type JavaParserBuild is already defined

looks like the JDK compiler found JavaParserBuild type twice in your sources. But I never seen that error so it is just guess

**Comment by ftomassetti** [comment]
Regarding 1, I tried that on a module with dependencies and I got a ton of errors.

Regarding 2, I am not sure, but this is the module of javaparser-core, which has zero dependencies and which can we obviously compile so I am not sure how to fix that :(

**Comment by pvojtechovsky** [comment]
try to replace
```java
launcher.addInputResource("codebases/jp/javaparser-core")
```
by
```java
launcher.addInputResource("codebases/jp/javaparser-core/src/main/java")
```
because the second occurrence of `JavaParserBuild` is here `javaparser-core\src\main\java-templates\com\github\javaparser`

**Comment by pvojtechovsky** [comment]
By the way Spoon has `MavenLauncher`, which might help you configure your source path and dependencies automatically.

**Comment by ftomassetti** [comment]
Yes, I know about the MavenLauncher, but I wanted to try this other approach. By the way, is there support for Gradle too?

Yes, adding the `src/main/java` works

**Comment by pvojtechovsky** [comment]
I know there is https://github.com/SpoonLabs/spoon-gradle-plugin but I do not know what features it has ...

**Comment by monperrus** [comment]
spoon-gradle-plugin is for doing source-to-source transformations as part of the build, prior to compiling.

there is no GradleLauncher, see #2773

**Comment by monperrus** [comment]
cleaning pass, don't hesitate to comment or reopen.
