### ISSUE TITLE
Sniper: spoon.support.reflect.code.CtForEachImpl does not have CtRole.STATEMENT

### ISSUE THREAD

**Issue by plcarmel** [INRIA/spoon#2838]
I try to run the Sniper pretty printer on a medium-sized project that works with the default pretty printer.

Here is what I do:
```
    public static void main(String[] args) {
        final Launcher launcher = new Launcher();
        final Environment environment = launcher.getEnvironment();
        environment.setLevel(Level.INFO.toString());
        launcher.setArgs(args);
        environment.setNoClasspath(false);
        environment.setAutoImports(true);
        launcher
            .getEnvironment()
            .setPrettyPrinterCreator(() -> new SniperJavaPrettyPrinter(launcher.getEnvironment()));
        launcher.buildModel();
        launcher.prettyprint();
    }
```

Using 7.3.0-SNAPSHOT (commit 0f5c2058bc87516a507fb3cb16b3dd9c58085786).

```
2018-12-11 23:45:20 ERROR Launcher:589 - The element of class class spoon.support.reflect.code.CtForEachImpl does not have CtRole.STATEMENT
spoon.SpoonException: The element of class class spoon.support.reflect.code.CtForEachImpl does not have CtRole.STATEMENT
	at spoon.reflect.meta.impl.RoleHandlerHelper.getRoleHandler(RoleHandlerHelper.java:66)
	at spoon.support.sniper.internal.ElementSourceFragment.getRoleHandler(ElementSourceFragment.java:248)
	at spoon.support.sniper.internal.ElementSourceFragment.addChild(ElementSourceFragment.java:185)
	at spoon.support.sniper.internal.ElementSourceFragment.access$000(ElementSourceFragment.java:54)
	at spoon.support.sniper.internal.ElementSourceFragment$1.enter(ElementSourceFragment.java:154)
	at spoon.reflect.visitor.CtScanner.visitCtForEach(CtScanner.java:472)
	at spoon.support.reflect.code.CtForEachImpl.accept(CtForEachImpl.java:39)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:181)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:173)
	at spoon.support.sniper.internal.ElementSourceFragment$1.scan(ElementSourceFragment.java:150)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:147)
	at spoon.reflect.visitor.CtScanner.visitCtBlock(CtScanner.java:302)
	at spoon.support.reflect.code.CtBlockImpl.accept(CtBlockImpl.java:67)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:181)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:173)
	at spoon.support.sniper.internal.ElementSourceFragment$1.scan(ElementSourceFragment.java:150)
	at spoon.reflect.visitor.CtScanner.visitCtForEach(CtScanner.java:476)
	at spoon.support.reflect.code.CtForEachImpl.accept(CtForEachImpl.java:39)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:181)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:173)
	at spoon.support.sniper.internal.ElementSourceFragment$1.scan(ElementSourceFragment.java:150)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:147)
	at spoon.reflect.visitor.CtScanner.visitCtBlock(CtScanner.java:302)
	at spoon.support.reflect.code.CtBlockImpl.accept(CtBlockImpl.java:67)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:181)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:173)
	at spoon.support.sniper.internal.ElementSourceFragment$1.scan(ElementSourceFragment.java:150)
	at spoon.reflect.visitor.CtScanner.visitCtMethod(CtScanner.java:559)
	at spoon.support.reflect.declaration.CtMethodImpl.accept(CtMethodImpl.java:67)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:181)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:173)
	at spoon.support.sniper.internal.ElementSourceFragment$1.scan(ElementSourceFragment.java:150)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:147)
	at spoon.reflect.visitor.CtScanner.visitCtClass(CtScanner.java:338)
	at spoon.support.reflect.declaration.CtClassImpl.accept(CtClassImpl.java:67)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:181)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:173)
	at spoon.support.sniper.internal.ElementSourceFragment$1.scan(ElementSourceFragment.java:150)
	at spoon.support.sniper.internal.ElementSourceFragment.addTreeOfSourceFragmentsOfElement(ElementSourceFragment.java:173)
	at spoon.support.reflect.cu.CompilationUnitImpl.getOriginalSourceFragment(CompilationUnitImpl.java:322)
	at spoon.support.sniper.SniperJavaPrettyPrinter.printTypes(SniperJavaPrettyPrinter.java:156)
	at spoon.reflect.visitor.DefaultJavaPrettyPrinter.calculate(DefaultJavaPrettyPrinter.java:1985)
	at spoon.support.sniper.SniperJavaPrettyPrinter.calculate(SniperJavaPrettyPrinter.java:116)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.getCompilationUnitInputStream(JDTBasedSpoonCompiler.java:673)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.generateProcessedSourceFilesUsingCUs(JDTBasedSpoonCompiler.java:578)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.generateProcessedSourceFiles(JDTBasedSpoonCompiler.java:213)
	at spoon.Launcher.prettyprint(Launcher.java:784)
```

**Comment by pvojtechovsky** [comment]
You found a problem in source position of elements. I am working on these fixes, but it will probably need some weeks.
To be able to fix exactly this problem, I need a failing test. Or at least a source code fragment which causes that problem.

**Comment by plcarmel** [comment]
Unfortunately, I cannot provide the source code I am working on. I could try to fix the problem myself with some guidance from you. Maybe you can point me some fixes you did on similar issues.

**Comment by pvojtechovsky** [comment]
> I cannot provide the source code I am working on.

we really do not want your code. We need very simple code fragment, which causes the problem.

> I could try to fix the problem myself

I will gladly support you. First I suggest to localize the problem - part of your source code which fails in Spoon. Then simplify that source code as much as possible. But it must still fail. Then make a PR with failing test case. Then we can see which part of Spoon sources has to be changed and we can suggest a solution, which can be then implemented by you or me.

> Am I correct ?

Your understanding is correct. In some cases it is like this. There are also cases when problem is in code which maps Eclipse compiler source position values to Spoon model element.

**Comment by monperrus** [comment]
cleaning pass, don't hesitate to comment or reopen.
