### ISSUE TITLE
ClassNotFoundException in DefaultJavaPrettyPrinter#printCtFieldAccess no classpath 

### ISSUE THREAD

**Issue by tdurieux** [INRIA/spoon#2844]
I face this exception when I try to print a ct field access in no classpath mode:
Apparently, it happens when the field is declared in an anonymous class (I see this pattern in several projects).

```java
Exception in thread "main" spoon.support.SpoonClassNotFoundException: cannot load class: org.apache.jackrabbit.mk.model.CommitBuilder$CopyNode
	at spoon.support.reflect.reference.CtTypeReferenceImpl.findClass(CtTypeReferenceImpl.java:164)
	at spoon.support.reflect.reference.CtTypeReferenceImpl.getActualClass(CtTypeReferenceImpl.java:146)
	at spoon.support.reflect.reference.CtTypeReferenceImpl.getTypeDeclaration(CtTypeReferenceImpl.java:190)
	at spoon.support.reflect.reference.CtFieldReferenceImpl.getFieldDeclaration(CtFieldReferenceImpl.java:159)
	at spoon.reflect.visitor.DefaultJavaPrettyPrinter.printCtFieldAccess(DefaultJavaPrettyPrinter.java:850)
	at spoon.reflect.visitor.DefaultJavaPrettyPrinter.visitCtFieldRead(DefaultJavaPrettyPrinter.java:799)
	at spoon.support.reflect.code.CtFieldReadImpl.accept(CtFieldReadImpl.java:27)
	at spoon.reflect.visitor.DefaultJavaPrettyPrinter.scan(DefaultJavaPrettyPrinter.java:345)
	at add.features.detector.repairpatterns.CopyPasteDetector$1.scan(CopyPasteDetector.java:59)
	at spoon.reflect.visitor.DefaultJavaPrettyPrinter.visitCtInvocation(DefaultJavaPrettyPrinter.java:1302)
	at spoon.support.reflect.code.CtInvocationImpl.accept(CtInvocationImpl.java:56)
	at spoon.reflect.visitor.DefaultJavaPrettyPrinter.scan(DefaultJavaPrettyPrinter.java:345)
	at add.features.detector.repairpatterns.CopyPasteDetector$1.scan(CopyPasteDetector.java:67)
	at spoon.reflect.visitor.DefaultJavaPrettyPrinter.visitCtInvocation(DefaultJavaPrettyPrinter.java:1287)
	at spoon.support.reflect.code.CtInvocationImpl.accept(CtInvocationImpl.java:56)
	at spoon.reflect.visitor.DefaultJavaPrettyPrinter.scan(DefaultJavaPrettyPrinter.java:345)
	at add.features.detector.repairpatterns.CopyPasteDetector$1.scan(CopyPasteDetector.java:67)
	at spoon.reflect.visitor.DefaultJavaPrettyPrinter.visitCtInvocation(DefaultJavaPrettyPrinter.java:1287)
	at spoon.support.reflect.code.CtInvocationImpl.accept(CtInvocationImpl.java:56)
	at spoon.reflect.visitor.DefaultJavaPrettyPrinter.scan(DefaultJavaPrettyPrinter.java:345)
	at add.features.detector.repairpatterns.CopyPasteDetector$1.scan(CopyPasteDetector.java:67)
	at spoon.reflect.visitor.DefaultJavaPrettyPrinter.visitCtInvocation(DefaultJavaPrettyPrinter.java:1287)
	at spoon.support.reflect.code.CtInvocationImpl.accept(CtInvocationImpl.java:56)
	at spoon.reflect.visitor.DefaultJavaPrettyPrinter.scan(DefaultJavaPrettyPrinter.java:345)
	at add.features.detector.repairpatterns.CopyPasteDetector$1.scan(CopyPasteDetector.java:67)
	at spoon.reflect.visitor.ElementPrinterHelper.writeStatement(ElementPrinterHelper.java:182)
	at spoon.reflect.visitor.DefaultJavaPrettyPrinter.visitCtBlock(DefaultJavaPrettyPrinter.java:526)
	at spoon.support.reflect.code.CtBlockImpl.accept(CtBlockImpl.java:48)
	at spoon.reflect.visitor.DefaultJavaPrettyPrinter.scan(DefaultJavaPrettyPrinter.java:345)
	at add.features.detector.repairpatterns.CopyPasteDetector$1.scan(CopyPasteDetector.java:67)
	at spoon.reflect.visitor.DefaultJavaPrettyPrinter.visitCtMethod(DefaultJavaPrettyPrinter.java:1377)
	at spoon.support.reflect.declaration.CtMethodImpl.accept(CtMethodImpl.java:73)
	at spoon.reflect.visitor.DefaultJavaPrettyPrinter.scan(DefaultJavaPrettyPrinter.java:345)
	at add.features.detector.repairpatterns.CopyPasteDetector$1.scan(CopyPasteDetector.java:67)
	at spoon.reflect.visitor.ElementPrinterHelper.writeElementList(ElementPrinterHelper.java:196)
	at spoon.reflect.visitor.DefaultJavaPrettyPrinter.visitCtClass(DefaultJavaPrettyPrinter.java:622)
	at spoon.support.reflect.declaration.CtClassImpl.accept(CtClassImpl.java:68)
	at spoon.reflect.visitor.DefaultJavaPrettyPrinter.scan(DefaultJavaPrettyPrinter.java:345)
	at add.features.detector.repairpatterns.CopyPasteDetector$1.scan(CopyPasteDetector.java:67)
	at add.features.detector.repairpatterns.CopyPasteDetector.detect(CopyPasteDetector.java:75)
	at add.features.detector.repairpatterns.RepairPatternDetector.analyze(RepairPatternDetector.java:45)
	at add.features.detector.repairpatterns.RepairPatternDetector.analyze(RepairPatternDetector.java:15)
	at add.main.Launcher.execute(Launcher.java:154)
	at add.main.Launcher.main(Launcher.java:167)
Caused by: java.lang.ClassNotFoundException: org.apache.jackrabbit.mk.model.CommitBuilder$CopyNode
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at spoon.support.reflect.reference.CtTypeReferenceImpl.findClass(CtTypeReferenceImpl.java:162)
	... 43 more
```

**Comment by nharrand** [comment]
With current SNAPSHOT?

**Comment by tdurieux** [comment]
no 7.2, did you change this in the snapshot?

**Comment by nharrand** [comment]
Not personally, but the problem in 7.2.0 does ring a bell. Would you try with current SNAPSHOT?

**Comment by tdurieux** [comment]
It was also the case in 7.0, I will try the snapshot.

**Comment by tdurieux** [comment]
I am unable to reproduce it in the SNAPSHOT, perfect thanks @nharrand
