### ISSUE TITLE
NoSuchMethodError when compiling code

### ISSUE THREAD

**Issue by djuelg** [INRIA/spoon#2850]
I tried to run the following code (from the examples) using the newest version of spoon (7.2.0):
```
Launcher l = new Launcher();
		l.getEnvironment().setNoClasspath(true);
		l.addInputResource("src/main/java");
		l.addProcessor(new HelloWorldProcessor());
		l.run();
```
Up until 7.1.0 this was working fine. Furthermore there is no error in the IDE. Only during compilation it fails with the following exception:

```
Running fr.inria.gforge.spoon.HelloWorldProcessorTest
"hello world"
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.16 sec <<< FAILURE! - in fr.inria.gforge.spoon.HelloWorldProcessorTest
testName(fr.inria.gforge.spoon.HelloWorldProcessorTest)  Time elapsed: 0.159 sec  <<< ERROR!
java.lang.NoSuchMethodError: spoon.reflect.declaration.CtCompilationUnit.getImports()Ljava/util/List;
        at spoon.reflect.visitor.DefaultJavaPrettyPrinter.calculate(DefaultJavaPrettyPrinter.java:2005)
        at spoon.support.JavaOutputProcessor.createJavaFile(JavaOutputProcessor.java:125)
        at spoon.support.JavaOutputProcessor.process(JavaOutputProcessor.java:161)
        at spoon.support.JavaOutputProcessor.process(JavaOutputProcessor.java:46)
        at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:74)
        at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:176)
        at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:150)
        at spoon.reflect.visitor.CtScanner.visitCtPackage(CtScanner.java:652)
        at spoon.support.reflect.declaration.CtPackageImpl.accept(CtPackageImpl.java:97)
        at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:184)
        at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:77)
        at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:176)
        at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:150)
        at spoon.reflect.visitor.CtScanner.visitCtPackage(CtScanner.java:651)
        at spoon.support.reflect.declaration.CtPackageImpl.accept(CtPackageImpl.java:97)
        at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:184)
        at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:77)
        at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:176)
        at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:150)
        at spoon.reflect.visitor.CtScanner.visitCtPackage(CtScanner.java:651)
        at spoon.support.reflect.declaration.CtPackageImpl.accept(CtPackageImpl.java:97)
        at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:184)
        at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:77)
        at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:176)
        at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:150)
        at spoon.reflect.visitor.CtScanner.visitCtPackage(CtScanner.java:651)
        at spoon.support.reflect.declaration.CtPackageImpl.accept(CtPackageImpl.java:97)
        at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:184)
        at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:77)
        at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:176)
        at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:150)
        at spoon.reflect.visitor.CtScanner.visitCtPackage(CtScanner.java:651)
        at spoon.support.reflect.declaration.CtPackageImpl.accept(CtPackageImpl.java:97)
        at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:184)
        at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:77)
        at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:176)
        at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:150)
        at spoon.reflect.visitor.CtScanner.visitCtPackage(CtScanner.java:651)
        at spoon.support.reflect.declaration.CtPackageImpl.accept(CtPackageImpl.java:97)
        at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:184)
        at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:77)
        at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:176)
        at spoon.reflect.visitor.CtScanner.visitCtModule(CtScanner.java:926)
        at spoon.reflect.factory.ModuleFactory$CtUnnamedModule.accept(ModuleFactory.java:105)
        at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:184)
        at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:77)
        at spoon.support.QueueProcessingManager.process(QueueProcessingManager.java:129)
        at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.generateProcessedSourceFilesUsingTypes(JDTBasedSpoonCompiler.java:487)
        at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.generateProcessedSourceFiles(JDTBasedSpoonCompiler.java:211)
        at spoon.Launcher.prettyprint(Launcher.java:789)
        at spoon.Launcher.run(Launcher.java:727)
        at fr.inria.gforge.spoon.HelloWorldProcessorTest.testName(HelloWorldProcessorTest.java:14)

```

**Comment by akalankapagoda** [comment]
Getting the same. Using 7.2.0.

**Comment by monperrus** [comment]
I can reproduce with 7.2.0 but not with 7.3.0-SNAPSHOT

Do you confirm that the bug is gone on master?

**Comment by monperrus** [comment]
Do you confirm that the bug is gone on master?

**Comment by Ahmedfir** [comment]
I am getting the same issue do you have any other alternative? Is the version 7.3.0 released?

**Comment by monperrus** [comment]
Soon, see #2869
