### ISSUE TITLE
Get java.lang.NullPointerException in spoon.support.compiler.jdt.ContextBuilder.enter

### ISSUE THREAD

**Issue by bzEq** [INRIA/spoon#2860]
Hi,
  I got NPD when run spoon on this snippet of code
```java
public class Foo {
  public static void foo() {
    ExecutorService executor = Executors.newSingleThreadExecutor();
    executor.submit(
        () -> {
          try {
          } catch (java.io.IOException | InterruptedException e) {
          }
        });
  }
}
```
with command `java -classpath ~/repos/spoon/target/spoon-core-7.3.0-SNAPSHOT-jar-with-dependencies.jar spoon.Launcher --gui --noclasspath -i  Foo.java`
Stack dump
```
Exception in thread "main" java.lang.NullPointerException
	at spoon.support.compiler.jdt.ContextBuilder.enter(ContextBuilder.java:99)
	at spoon.support.compiler.jdt.JDTTreeBuilder.visit(JDTTreeBuilder.java:1470)
	at org.eclipse.jdt.internal.compiler.ast.QualifiedTypeReference.traverse(QualifiedTypeReference.java:212)
	at org.eclipse.jdt.internal.compiler.ast.UnionTypeReference.traverse(UnionTypeReference.java:116)
	at org.eclipse.jdt.internal.compiler.ast.Argument.traverse(Argument.java:245)
	at org.eclipse.jdt.internal.compiler.ast.TryStatement.traverse(TryStatement.java:1237)
	at org.eclipse.jdt.internal.compiler.ast.Block.traverse(Block.java:148)
	at org.eclipse.jdt.internal.compiler.ast.LambdaExpression.traverse(LambdaExpression.java:768)
	at org.eclipse.jdt.internal.compiler.ast.MessageSend.traverse(MessageSend.java:1105)
	at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.traverse(MethodDeclaration.java:365)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.traverse(TypeDeclaration.java:1414)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.traverse(CompilationUnitDeclaration.java:816)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.traverse(CompilationUnitDeclaration.java:777)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.lambda$buildModel$0(JDTBasedSpoonCompiler.java:433)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.forEachCompilationUnit(JDTBasedSpoonCompiler.java:457)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildModel(JDTBasedSpoonCompiler.java:431)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildUnitsAndModel(JDTBasedSpoonCompiler.java:375)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildSources(JDTBasedSpoonCompiler.java:340)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:123)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:106)
	at spoon.Launcher.buildModel(Launcher.java:772)
	at spoon.Launcher.run(Launcher.java:723)
	at spoon.Launcher.run(Launcher.java:118)
	at spoon.Launcher.main(Launcher.java:111)
```

**Comment by bzEq** [comment]
Done. #2862
