### ISSUE TITLE
If module-info.java exists, compliance level should be >=9 otherwise stop with clear message

### ISSUE THREAD

**Issue by SvyatoslavRazmyslov** [INRIA/spoon#2861]
Hello,

To reproduce the problem it is needed to create a project with the following structure:

- D:\\untitled\\SomeModule
    - src
        - api
            - api.java
            - module-info.java

A new `module-info.java` has appeared in Java 9.

If you add a comment (any one in any place) in `module-info.java`, for example:

```
module SomeModule {
  /*some exports*/
}
```
and execute the following code:

```
Launcher launcher = new Launcher();
launcher.addInputResource("D:\\untitled\\SomeModule");
launcher.buildModel();
```

We'll get:

```
Exception in thread "main" spoon.SpoonException: Unexpected lineSeparatorPositions
     at spoon.support.reflect.cu.position.SourcePositionImpl.<init>(SourcePositionImpl.java:123)
     at spoon.support.DefaultCoreFactory.createSourcePosition(DefaultCoreFactory.java:762)
     at spoon.support.compiler.jdt.JDTCommentBuilder.buildComment(JDTCommentBuilder.java:144)
     at spoon.support.compiler.jdt.JDTCommentBuilder.build(JDTCommentBuilder.java:111)
     at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.lambda$buildModel$2(JDTBasedSpoonCompiler.java:443)
     at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.forEachCompilationUnit(JDTBasedSpoonCompiler.java:457)
     at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildModel(JDTBasedSpoonCompiler.java:442)
     at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildUnitsAndModel(JDTBasedSpoonCompiler.java:375)
     at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildSources(JDTBasedSpoonCompiler.java:340)
     at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:123)
     at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:106)
     at spoon.Launcher.buildModel(Launcher.java:772)
```

If you delete all comments from the `module-info.java`, the method `launcher.buildModel()` will be executed without any exceptions.

**Comment by monperrus** [comment]
Thanks a lot for the bug report. Could you create a pull-request with a failing test case?

**Comment by SvyatoslavRazmyslov** [comment]
Hello, @monperrus 

Such a call helped to solve my problem:

`launcher.getEnvironment().setComplianceLevel(9); // Java 9`

Tell me, please, if it's not the right way.

**Comment by monperrus** [comment]
That's the right way. But we should have a better exception. I'm renaming the issue.

**Comment by SvyatoslavRazmyslov** [comment]
Hello @monperrus,

Do I need to reopen the issue?

**Comment by monperrus** [comment]
Yes! And would you propose a patch? it is probably relatively easy :-)
