### ISSUE TITLE
Replace local var ref with field ref fails

### ISSUE THREAD

**Issue by ftomassetti** [INRIA/spoon#2876]
I am running this code:

```
            CtIterator(it).forEach {
                if (it is CtParameterReference<*> && it.simpleName == paramName) {
                    it.replace(qualifiedFieldAccess(paramName, clazz.qualifiedName))
                }
            }
```

Where qualifiedFieldAccess looks like this:
```
fun qualifiedFieldAccess(name: String, className: String) : CtFieldAccess<Any> {
    return fieldRef(name).let {
        val target = CtThisAccessImpl<Any>().let {
            it.setTarget<CtTargetedExpression<Any, CtExpression<*>>>(CtTypeAccessImpl<Any>().let {
                it.setAccessedType<CtTypeAccess<Any>>(createTypeReference(className))
                it
            })
            it
        }
        it.setTarget<CtTargetedExpression<Any, CtExpression<*>>>(target)
        it
    }
}
```

And I get this exception:
```
Exception in thread "main" java.lang.ClassCastException: spoon.support.reflect.code.CtFieldReadImpl cannot be cast to spoon.reflect.reference.CtVariableReference
	at spoon.support.visitor.replace.ReplacementVisitor$CtVariableAccessVariableReplaceListener.set(ReplacementVisitor.java:1077)
	at spoon.support.visitor.replace.ReplacementVisitor.replaceElementIfExist(ReplacementVisitor.java:1375)
	at spoon.support.visitor.replace.ReplacementVisitor.visitCtVariableRead(ReplacementVisitor.java:1961)
	at spoon.support.reflect.code.CtVariableReadImpl.accept(CtVariableReadImpl.java:27)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:181)
	at spoon.support.visitor.replace.ReplacementVisitor.replace(ReplacementVisitor.java:1260)
	at spoon.support.reflect.declaration.CtElementImpl.replace(CtElementImpl.java:474)
	at com.strumenta.spoonexamples.ParamToFieldRefactoring.refactor(CodeTransformation.kt:65)
	at com.strumenta.spoonexamples.CodeTransformationKt.main(CodeTransformation.kt:102)
```

I am not sure: am I using replace in the wrong way? Is there another way to replace a parameter reference with a field reference?

**Comment by monperrus** [comment]
Yes, what you want is to replace a reference by another reference (in Spoon the world is split in
two the elements and the references, see http://spoon.gforge.inria.fr/references.html).

Two solutions:
- you replace another element which is not a reference by the CtFieldRead you create
- you replace the reference by a CtFieldReference instead (AFAIU, you create a |CtFieldReadImpl in
method fieldRef(?))
|

**Comment by monperrus** [comment]
works for you?
