### ISSUE TITLE
ArrayIndexOutOfBoundsException in PositionBuilder

### ISSUE THREAD

**Issue by rolve** [INRIA/spoon#2888]
This code in `spoon.support.compiler.jdt.PositionBuilder.buildPositionCtElement()`:

    if (contents[bodyStart - 1] == '{') {
        bodyStart--;
        if (contents[bodyEnd + 1] == '}') {
            bodyEnd++;
        } else {
            ...
        }
    }

crashes for a source file that misses braces at the end.

Stack trace:

    java.lang.ArrayIndexOutOfBoundsException: 5736
        at spoon.support.compiler.jdt.PositionBuilder.buildPositionCtElement(PositionBuilder.java:354)
        at spoon.support.compiler.jdt.ContextBuilder.enter(ContextBuilder.java:100)
        at spoon.support.compiler.jdt.JDTTreeBuilder.visit(JDTTreeBuilder.java:1059)
        at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.traverse(MethodDeclaration.java:335)
        at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.traverse(TypeDeclaration.java:1414)
        at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.traverse(CompilationUnitDeclaration.java:816)
        at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.traverse(CompilationUnitDeclaration.java:777)
        at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.lambda$buildModel$0(JDTBasedSpoonCompiler.java:433)
        at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.forEachCompilationUnit(JDTBasedSpoonCompiler.java:457)
        at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildModel(JDTBasedSpoonCompiler.java:431)
        at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildUnitsAndModel(JDTBasedSpoonCompiler.java:375)
        at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildSources(JDTBasedSpoonCompiler.java:340)
        at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:123)
        at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:106)
        at spoon.Launcher.buildModel(Launcher.java:772)

**Comment by monperrus** [comment]
Thanks, could you create a pull request with a failing test case?

**Comment by monperrus** [comment]
> crashes for a source file that misses braces at the end.

Do you mean that the file does not compile in the first place?

**Comment by rolve** [comment]
Yes, here is an example that crashes:

    import spoon.Launcher;
    
    public class Crash {
        public static void main(String[] args) {
            Launcher.parseClass("class A { void foo() {");
        }
    }
