### ISSUE TITLE
Bug SniperJavaPrettyPrinter and loops with no block

### ISSUE THREAD

**Issue by edouard-gillet** [INRIA/spoon#2938]
Hi,

When using SniperJavaPrettyPrinter over loops that are not using braces, this issue occurs (for while, foreach, or for loops):

`spoon.SpoonException: The element of class class spoon.support.reflect.code.CtWhileImpl does not have CtRole.STATEMENT
	at spoon.reflect.meta.impl.RoleHandlerHelper.getRoleHandler(RoleHandlerHelper.java:66)
	at spoon.support.sniper.internal.ElementSourceFragment.getRoleHandler(ElementSourceFragment.java:248)
	at spoon.support.sniper.internal.ElementSourceFragment.addChild(ElementSourceFragment.java:188)
	at spoon.support.sniper.internal.ElementSourceFragment.access$000(ElementSourceFragment.java:55)
	at spoon.support.sniper.internal.ElementSourceFragment$1.enter(ElementSourceFragment.java:152)
	at spoon.reflect.visitor.CtScanner.visitCtInvocation(CtScanner.java:505)
	at spoon.support.reflect.code.CtInvocationImpl.accept(CtInvocationImpl.java:55)
	at spoon.reflect.visitor.EarlyTerminatingScanner.doScan(EarlyTerminatingScanner.java:154)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:130)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:176)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:115)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:92)
	at spoon.reflect.visitor.CtScanner.visitCtBlock(CtScanner.java:305)
	at spoon.support.reflect.code.CtBlockImpl.accept(CtBlockImpl.java:67)
	at spoon.reflect.visitor.EarlyTerminatingScanner.doScan(EarlyTerminatingScanner.java:154)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:130)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:176)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:115)
	at spoon.reflect.visitor.CtScanner.visitCtWhile(CtScanner.java:826)
	at spoon.support.reflect.code.CtWhileImpl.accept(CtWhileImpl.java:34)
	at spoon.reflect.visitor.EarlyTerminatingScanner.doScan(EarlyTerminatingScanner.java:154)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:130)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:176)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:115)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:92)
	at spoon.reflect.visitor.CtScanner.visitCtBlock(CtScanner.java:305)
	at spoon.support.reflect.code.CtBlockImpl.accept(CtBlockImpl.java:67)
	at spoon.reflect.visitor.EarlyTerminatingScanner.doScan(EarlyTerminatingScanner.java:154)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:130)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:176)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:115)
	at spoon.reflect.visitor.CtScanner.visitCtMethod(CtScanner.java:562)
	at spoon.support.reflect.declaration.CtMethodImpl.accept(CtMethodImpl.java:67)
	at spoon.reflect.visitor.EarlyTerminatingScanner.doScan(EarlyTerminatingScanner.java:154)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:130)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:176)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:115)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:92)
	at spoon.reflect.visitor.CtScanner.visitCtClass(CtScanner.java:341)
	at spoon.support.reflect.declaration.CtClassImpl.accept(CtClassImpl.java:67)
	at spoon.reflect.visitor.EarlyTerminatingScanner.doScan(EarlyTerminatingScanner.java:154)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:130)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:176)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:115)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:92)
	at spoon.reflect.visitor.EarlyTerminatingScanner.visitCtCompilationUnit(EarlyTerminatingScanner.java:169)
	at spoon.support.reflect.declaration.CtCompilationUnitImpl.accept(CtCompilationUnitImpl.java:417)
	at spoon.reflect.visitor.EarlyTerminatingScanner.doScan(EarlyTerminatingScanner.java:154)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:130)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:176)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:115)
	at spoon.support.sniper.internal.ElementSourceFragment.addTreeOfSourceFragmentsOfElement(ElementSourceFragment.java:176)
	at spoon.support.reflect.declaration.CtCompilationUnitImpl.getOriginalSourceFragment(CtCompilationUnitImpl.java:369)
	at spoon.support.sniper.SniperJavaPrettyPrinter.printTypes(SniperJavaPrettyPrinter.java:156)
	at spoon.reflect.visitor.DefaultJavaPrettyPrinter.calculate(DefaultJavaPrettyPrinter.java:2018)
	at spoon.support.sniper.SniperJavaPrettyPrinter.calculate(SniperJavaPrettyPrinter.java:116)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.getCompilationUnitInputStream(JDTBasedSpoonCompiler.java:647)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.generateProcessedSourceFilesUsingCUs(JDTBasedSpoonCompiler.java:550)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.generateProcessedSourceFiles(JDTBasedSpoonCompiler.java:214)
	at spoon.Launcher.prettyprint(Launcher.java:789)
	at spoon.Launcher.run(Launcher.java:727)
	at bugreport.LoopSniperJavaPrettyPrinterTest.runSniperJavaPrettyPrinter(LoopSniperJavaPrettyPrinterTest.java:54)
	at bugreport.LoopSniperJavaPrettyPrinterTest.whileNoBraces(LoopSniperJavaPrettyPrinterTest.java:42)
...`

I wrote a quick test to reproduce:

```java
package bugreport;

import static org.junit.Assert.assertThat;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

import org.apache.commons.io.FileUtils;
import org.hamcrest.CoreMatchers;
import org.junit.BeforeClass;
import org.junit.Test;

import spoon.Launcher;
import spoon.compiler.Environment;
import spoon.support.sniper.SniperJavaPrettyPrinter;

public class LoopSniperJavaPrettyPrinterTest {

    private static final Path INPUT_PATH = Paths.get("src/test/resources/");
    private static final Path OUTPUT_PATH = Paths.get("test-output");

    @BeforeClass
    public static void setup() throws IOException {
        FileUtils.deleteDirectory(OUTPUT_PATH.toFile());
    }

    @Test
    public void forNoBraces() throws IOException {
        runSniperJavaPrettyPrinter("bugreport/examples/ForNoBraces.java");
    }

    @Test
    public void forEachBraces() throws IOException {
        runSniperJavaPrettyPrinter("bugreport/examples/ForEachNoBraces.java");
    }

    @Test
    public void whileNoBraces() throws IOException {
        runSniperJavaPrettyPrinter("bugreport/examples/WhileNoBraces.java");
    }

    private void runSniperJavaPrettyPrinter(String path) throws IOException {
        final Launcher launcher = new Launcher();
        final Environment e = launcher.getEnvironment();
        e.setLevel("INFO");
        e.setPrettyPrinterCreator(() -> new SniperJavaPrettyPrinter(e));

        launcher.addInputResource(INPUT_PATH.resolve(path).toString());
        launcher.setSourceOutputDirectory(OUTPUT_PATH.toString());

        launcher.run();

        // Verify result file exist and is not empty
        assertThat("Output file for " + path + " should exist",
                OUTPUT_PATH.resolve(path).toFile().exists(), CoreMatchers.equalTo(true));

        String content = new String(Files.readAllBytes(OUTPUT_PATH.resolve(path)),
                StandardCharsets.UTF_8);

        assertThat(content, CoreMatchers.notNullValue());
        assertThat("Result class should not be empty", content.trim(),
                CoreMatchers.not(CoreMatchers.equalTo("")));
    }

}
```
With examples:
```java
package bugreport.examples;

import java.util.Arrays;

public class ForEachNoBraces {

    public void example() {
        for (int i : Arrays.asList(1, 2, 3, 4, 5))
            System.out.println(i);
    }

}
```
```java
package bugreport.examples;

public class ForNoBraces {

    public void example() {

        for (int i = 0; i < 10; i++)
            System.out.println(i);

    }

}
```
```java
package bugreport.examples;

public class WhileNoBraces {

    public void test() {
        while(true)
            System.out.println("Test");
    }
    
}
```

**Comment by monperrus** [comment]
@nharrand are we ready to unWIP #2942 and merge?
