### ISSUE TITLE
bug: spoon.SpoonException: Declaring type of field result isn't defined

### ISSUE THREAD

**Issue by trexsatya** [INRIA/spoon#3065]
I am trying to process Java classes from ElasticSearch. There is a certain class which if added to Launcher.
Here's my code to process the file.

```java

public static void analyze(String path) throws IOException, InterruptedException {
        Launcher launcher = new Launcher();

        Thread.setDefaultUncaughtExceptionHandler((x,y) -> {
            y.printStackTrace();
        });

        launcher.addInputResource("/home/satyendra/IdeaProjects/elasticsearch/modules/elasticsearch/src/main/java/org/elasticsearch/http/Utf8HttpResponse.java");

        launcher.getEnvironment().setAutoImports(true); // optional

        launcher.getEnvironment().setNoClasspath(true); // optional

        launcher.run();
        final Factory factory = launcher.getFactory();
        final ProcessingManager processingManager = new QueueProcessingManager(factory);
        final ClassProcessor processor = new ClassProcessor();
        processingManager.addProcessor(processor);
        processingManager.process(factory.Class().getAll());

        System.out.println(factory.Class().getAll());

        CtType s = new TypeFactory().get(String.class);
//        s.getFields().forEach(System.out::println);
    }
```
The class that fails is [UtfHttpResponse](https://gist.github.com/trexsatya/6d9f15dc2a25c4cd9f1caa116b58ffd1)

I did a little digging and find that the problem is due to multi-line static block.

**Comment by surli** [comment]
I just tried locally and I indeed got the following stacktrace:
```
Exception in thread "main" spoon.SpoonException: Declaring type of field result isn't defined
	at spoon.support.reflect.reference.CtFieldReferenceImpl.getActualField(CtFieldReferenceImpl.java:57)
	at spoon.support.reflect.reference.CtFieldReferenceImpl.getModifiers(CtFieldReferenceImpl.java:238)
	at spoon.reflect.visitor.DefaultJavaPrettyPrinter.isInitializeStaticFinalField(DefaultJavaPrettyPrinter.java:850)
	at spoon.reflect.visitor.DefaultJavaPrettyPrinter.printCtFieldAccess(DefaultJavaPrettyPrinter.java:797)
	at spoon.reflect.visitor.DefaultJavaPrettyPrinter.visitCtFieldWrite(DefaultJavaPrettyPrinter.java:756)
	at spoon.support.reflect.code.CtFieldWriteImpl.accept(CtFieldWriteImpl.java:16)
	at spoon.reflect.visitor.DefaultJavaPrettyPrinter.scan(DefaultJavaPrettyPrinter.java:350)
	at spoon.reflect.visitor.DefaultJavaPrettyPrinter.visitCtAssignment(DefaultJavaPrettyPrinter.java:465)
	at spoon.support.reflect.code.CtAssignmentImpl.accept(CtAssignmentImpl.java:43)
	at spoon.reflect.visitor.DefaultJavaPrettyPrinter.scan(DefaultJavaPrettyPrinter.java:350)
	at spoon.reflect.visitor.ElementPrinterHelper.writeStatement(ElementPrinterHelper.java:168)
	at spoon.reflect.visitor.DefaultJavaPrettyPrinter.visitCtBlock(DefaultJavaPrettyPrinter.java:498)
	at spoon.support.reflect.code.CtBlockImpl.accept(CtBlockImpl.java:55)
	at spoon.reflect.visitor.DefaultJavaPrettyPrinter.scan(DefaultJavaPrettyPrinter.java:350)
	at spoon.reflect.visitor.DefaultJavaPrettyPrinter.visitCtAnonymousExecutable(DefaultJavaPrettyPrinter.java:416)
	at spoon.support.reflect.declaration.CtAnonymousExecutableImpl.accept(CtAnonymousExecutableImpl.java:35)
	at spoon.reflect.visitor.DefaultJavaPrettyPrinter.scan(DefaultJavaPrettyPrinter.java:350)
	at spoon.reflect.visitor.ElementPrinterHelper.writeElementList(ElementPrinterHelper.java:178)
	at spoon.reflect.visitor.DefaultJavaPrettyPrinter.visitCtClass(DefaultJavaPrettyPrinter.java:592)
	at spoon.support.reflect.declaration.CtClassImpl.accept(CtClassImpl.java:56)
	at spoon.reflect.visitor.DefaultJavaPrettyPrinter.scan(DefaultJavaPrettyPrinter.java:350)
	at spoon.support.reflect.declaration.CtElementImpl.toString(CtElementImpl.java:289)
	at Main.main(Main.java:38)

```

**Comment by trexsatya** [comment]
But why doesn't this exception propagate though? Why not able to see what went wrong?

**Comment by surli** [comment]
I don't follow. It's actually a bug :) You cannot see anything because it breaks the `toString` call.
