### ISSUE TITLE
NPE within the JDTTreeBuilder#createExecutableReferenceExpression method

### ISSUE THREAD

**Issue by boeserwolf91** [INRIA/spoon#308]
I used spoon to build the model of a bigger project using java 8 features. Unfortunately I got an NPE within the method createExecutableReferenceExpression from the JDTTreeBuilder class. 

Here is the exact stacktrace: 

```
Caused by: java.lang.NullPointerException
	at spoon.support.compiler.jdt.JDTTreeBuilder.createExecutableReferenceExpression(JDTTreeBuilder.java:1505)
	at spoon.support.compiler.jdt.JDTTreeBuilder.visit(JDTTreeBuilder.java:1495)
	at org.eclipse.jdt.internal.compiler.ast.ReferenceExpression.traverse(ReferenceExpression.java:755)
	at spoon.support.compiler.jdt.JDTTreeBuilder.visit(JDTTreeBuilder.java:2192)
	at org.eclipse.jdt.internal.compiler.ast.MessageSend.traverse(MessageSend.java:1005)
	at spoon.support.compiler.jdt.JDTTreeBuilder.visit(JDTTreeBuilder.java:2188)
	at org.eclipse.jdt.internal.compiler.ast.MessageSend.traverse(MessageSend.java:1005)
	at org.eclipse.jdt.internal.compiler.ast.ReturnStatement.traverse(ReturnStatement.java:373)
	at spoon.support.compiler.jdt.JDTTreeBuilder.visit(JDTTreeBuilder.java:2272)
	at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.traverse(MethodDeclaration.java:317)
	at spoon.support.compiler.jdt.JDTTreeBuilder.visit(JDTTreeBuilder.java:2946)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.traverse(TypeDeclaration.java:1338)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.traverse(CompilationUnitDeclaration.java:745)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.traverse(CompilationUnitDeclaration.java:706)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildSources(JDTBasedSpoonCompiler.java:229)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:505)
	at org.cubeengine.pericopist.extractor.java.JavaMessageExtractor.extract(JavaMessageExtractor.java:93)
```

I can't say which line of the project causes this exception. 

But I know it from the Spoon side. The ResourceBuilder#getExecutableReference returns null if the referenceExpression.binding value is null. This case isn't handled here.

**Comment by GerardPaligot** [comment]
Have you an idea to reproduce this bug? Because it is weird that an executable reference ... don't have an executable to reference.

**Comment by boeserwolf91** [comment]
No I don't have an idea yet. I'll try to reproduce it tomorrow or Tuesday. I just wanted to report the bug today, because I didn't want to forget it. It occurs with building the model of the [sponge branch of the CubeEngine-Core project](https://github.com/CubeEngine/core/tree/sponge).

**Comment by GerardPaligot** [comment]
Cool, I will be able to test too (and add your project on our Jenkins :)).

**Comment by boeserwolf91** [comment]
Great. The debugger will be our best friend I guess :+1: But I don't know whether I'll find time tomorrow. I've a meeting after work and sports to do in the evening. I'll try to do it tomorrow, but I bet Tuesday is going to be my day.
If you're faster as I'm, you've to install the [parent project](https://github.com/CubeEngine/parent) of the CubeEngine-core to compile it.
