### ISSUE TITLE
sniper: unable to rename class

### ISSUE THREAD

**Issue by tdurieux** [INRIA/spoon#3097]
Using this code:

```java
final CtClass<?> ctClass = f.Class().get("spoon.test.prettyprinter.testclasses.Validation");
ctClass.setSimpleName("Test");
```

The model is correctly changed, but the sniper mode does not succeed to generate the correct output.

**Comment by monperrus** [comment]
Do you mean 

* only rename the class 
* or rename the class and all references (full-fledged refactoring)

**Comment by tdurieux** [comment]
A full refactoring could be nice but here the problem is the the sniper mode does not change the name of the class. In the output the old name is still uses.

**Comment by ITWOI** [comment]
Hi, I have a similar problem. But it leads to NPE.

I use Spoon 8.1.0-beta-9. 

Here is the code, note that if I remove `launcher.getEnvironment().setPrettyPrinterCreator(() -> new SniperJavaPrettyPrinter(launcher.getEnvironment()));`, then every thing works fine.

```
public class ClassRename extends AbstractProcessor<CtClass> {
    int renameIndex;
    public ClassRename(int renameIndex) {
        this.renameIndex = renameIndex;
    }
    @Override
    public void process(CtClass arg0) {
        String newMethodName = arg0.getSimpleName() + renameIndex;
        arg0.setSimpleName(newMethodName);
    }
}
```

```
   void entry(List<StmtTrace> ele, int index) {
        final Launcher launcher = retLauncher();
        launcher.addProcessor(new ClassRename(index));
        launcher.run();
    }
    Launcher retLauncher(){
        final Launcher launcher = new Launcher();
        launcher.setArgs(arg);
        launcher.getEnvironment().setPrettyPrinterCreator(() -> new SniperJavaPrettyPrinter(launcher.getEnvironment()));
        return launcher;
    }
```

```
Exception in thread "main" spoon.SpoonException: java.lang.NullPointerException
	at spoon.Launcher.prettyprint(Launcher.java:789)
	at spoon.Launcher.run(Launcher.java:725)
	at MutManager.callMut(MutManager.java:307)
	at MutManager.doMutate(MutManager.java:297)
	at MutManager.executeMutation(MutManager.java:184)
	at MutManager.runManager(MutManager.java:227)
	at Main.main(Main.java:71)
Caused by: java.lang.NullPointerException
	at spoon.support.reflect.declaration.CtCompilationUnitImpl.getMainType(CtCompilationUnitImpl.java:148)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.generateProcessedSourceFilesUsingCUs(JDTBasedSpoonCompiler.java:517)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.generateProcessedSourceFiles(JDTBasedSpoonCompiler.java:204)
	at spoon.Launcher.prettyprint(Launcher.java:787)
```

What I want to do is to remove some statements and rename the class, but I found that the generated code will have additional parentheses.

Here is an example, 

```
 public class Main {
     public static int m1(int arr[], int n) {
         for (int i = 0; i < n-1; i++) {
             for (int j = 0; j < n-i-1; j++) {
                 if (arr[j] > arr[j+1])
                 {
                     int temp = arr[j];
                     arr[j] = arr[j+1];
                     arr[j+1] = temp;
                 }
             }
         }
         return 0;
     }
 }
```

The generated code is:

```
 public class Main2 {
     public static int m1(int[] arr, int n) {
         for (int i = 0; i < (n - 1); i++) {
             for (int j = 0; j < ((n - i) - 1); j++) {
                 if (arr[j] > arr[j + 1]) {
                     int temp = arr[j];
                     arr[j] = arr[j + 1];
                     arr[j + 1] = temp;
                 }
             }
         }
         return 0;
     }
 }
```

Is there any way to avoid introducing parentheses?

Thank you very much.
