### ISSUE TITLE
ModelBuildingException: The type MapEntryNode is already defined

### ISSUE THREAD

**Issue by lsafina** [INRIA/spoon#3150]
Hi, I do not know if spoon supposes to react in this way, so just in case I report this.
When trying to run the example from documentation on spoon itself it raises exception:

```
Exception in thread "main" spoon.compiler.ModelBuildingException: The type MapEntryNode is already defined
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.reportProblem(JDTBasedSpoonCompiler.java:575)
	at spoon.support.compiler.jdt.TreeBuilderRequestor.acceptResult(TreeBuilderRequestor.java:27)
	at spoon.support.compiler.jdt.TreeBuilderCompiler.buildUnits(TreeBuilderCompiler.java:86)
	at spoon.support.compiler.jdt.JDTBatchCompiler.getUnits(JDTBatchCompiler.java:255)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildUnits(JDTBasedSpoonCompiler.java:403)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildUnitsAndModel(JDTBasedSpoonCompiler.java:362)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildSources(JDTBasedSpoonCompiler.java:330)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:113)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:96)
	at spoon.Launcher.buildModel(Launcher.java:766)

```

I'm running it from

```
fun main(args : Array<String>) {
    val launcher = Launcher()
    launcher.addInputResource("../spoon")
    launcher.buildModel()
    val model = launcher.model
}
```

I'm using spoon-core:7.5.0 throw gradle-5.2.1 
IntelliJ IDEA 2019.2.3 Build #IC-192.6817.14, java 11.0.4, Kotlin 1.3.50

UPD: I got the similar error (with different type already defined) for other sources. As far as I understood looking in previous issues, it is the normal behaviour and I need to narrow the scope of the sources?

**Comment by nharrand** [comment]
I am not super familiar with kotlin, but can you try with 

```kotlin
fun main(args : Array<String>) {
    val launcher = Launcher()
    launcher.addInputResource("../spoon")
    launcher.buildModel()
    val model = launcher.getModel()
}
```

**Comment by lsafina** [comment]
Yep, with src/main/java only it works fine. Thank you, I will apply the same strategy to the project I need.

**Comment by djaekim** [comment]
Hi, is there a work around for case as shown below?

https://github.com/apache/kafka/search?q=StreamsUpgradeToCooperativeRebalanceTest

There are multiple StreamsUpgradeToCooperativeRebalanceTest.java in different folder.

Thank you in advance
