### ISSUE TITLE
Bug: Crash when modifying code with double for initializer and using sniper

### ISSUE THREAD

**Issue by woutersmeenk** [INRIA/spoon#3222]
When using sniper to modify this code:

```java
public class DoubleForInitializer {
  public void test() {
    for (int i = 0, y = 0; y < 10; y++) {

    }
  }
}
```

I get this exception:
spoon.SpoonException: Inconsistent child fragment class spoon.support.reflect.code.CtLocalVariableImpl has unexpected parent class spoon.support.reflect.code.CtLocalVariableImpl
	at spoon.support.sniper.internal.ElementSourceFragment.addChild(ElementSourceFragment.java:313)
	at spoon.support.sniper.internal.ElementSourceFragment.add(ElementSourceFragment.java:279)
	at spoon.support.sniper.internal.ElementSourceFragment.merge(ElementSourceFragment.java:294)
	at spoon.support.sniper.internal.ElementSourceFragment.add(ElementSourceFragment.java:283)

**Comment by monperrus** [comment]
closed per #3223
