### ISSUE TITLE
Bug: Crash when modifying code with double type bound and using sniper

### ISSUE THREAD

**Issue by woutersmeenk** [INRIA/spoon#3224]
When using sniper to modify this code:

```java
import java.io.*;

public class DoubleBound<T extends Writer & Readable>
{
}
```

I get this stacktrace:
spoon.SpoonException: The element of class class spoon.support.reflect.declaration.CtTypeParameterImpl does not have CtRole.BOUND
	at spoon.reflect.meta.impl.RoleHandlerHelper.getRoleHandler(RoleHandlerHelper.java:55)
	at spoon.support.sniper.internal.ElementSourceFragment.getRoleHandler(ElementSourceFragment.java:251)
	at spoon.support.sniper.internal.ElementSourceFragment.addChild(ElementSourceFragment.java:191)
	at spoon.support.sniper.internal.ElementSourceFragment.access$0(ElementSourceFragment.java:187)
	at spoon.support.sniper.internal.ElementSourceFragment$1.enter(ElementSourceFragment.java:155)
	at spoon.reflect.visitor.CtScanner.visitCtTypeReference(CtScanner.java:762)

**Comment by monperrus** [comment]
closed per #3225
