### ISSUE TITLE
question on message: spoon.SpoonException: The default behavior has changed, a new check has been added!

### ISSUE THREAD

**Issue by LuckyboyYu** [INRIA/spoon#3340]
Exception in thread "main" spoon.SpoonException: The default behavior has changed, a new check has been added! Don't worry, you can disable this check
with one of the following options:
 - by configuring Spoon with getEnvironment().setSelfChecks(true)
 - by removing the node from its previous parent (element.delete())
 - by cloning the node before adding it here (element.clone())

	at spoon.support.util.ModelList.linkToParent(ModelList.java:87)

I just can't figure the possible reason.

**Comment by monperrus** [comment]
Thanks for the bug report.

Could you paste the full stack trace?

**Comment by LuckyboyYu** [comment]
> Thanks for the bug report.
> 
> Could you paste the full stack trace?

Of course.
Exception in thread "main" spoon.SpoonException: The default behavior has changed, a new check has been added! Don't worry, you can disable this check
with one of the following options:
 - by configuring Spoon with getEnvironment().setSelfChecks(true)
 - by removing the node from its previous parent (element.delete())
 - by cloning the node before adding it here (element.clone())

	at spoon.support.util.ModelList.linkToParent(ModelList.java:87)
	at spoon.support.util.ModelList.add(ModelList.java:123)
	at spoon.support.util.ModelList.add(ModelList.java:30)
	at java.util.AbstractCollection.addAll(AbstractCollection.java:344)
	at spoon.support.util.ModelList.set(ModelList.java:57)
	at spoon.support.reflect.code.CtBlockImpl.setStatements(CtBlockImpl.java:163)
	at spoon.support.reflect.code.CtStatementImpl$InsertType$2.insertFromFirstStatement(CtStatementImpl.java:214)
	at spoon.support.reflect.code.CtStatementImpl$InsertVisitor.visitCtBlock(CtStatementImpl.java:94)
	at spoon.support.reflect.code.CtBlockImpl.accept(CtBlockImpl.java:57)
	at spoon.reflect.visitor.CtInheritanceScanner.scan(CtInheritanceScanner.java:177)
	at spoon.support.reflect.code.CtStatementImpl.insertAfter(CtStatementImpl.java:49)
	at spoon.support.reflect.code.CtStatementImpl.insertAfter(CtStatementImpl.java:39)
	at spoon.support.reflect.code.CtStatementImpl.insertAfter(CtStatementImpl.java:261)
	at code.core.staticchecking.analyzer.efficiency.ObjectReferenceProcessor.process(ObjectReferenceProcessor.java:72)
	at code.core.staticchecking.analyzer.efficiency.ObjectReferenceProcessor.process(ObjectReferenceProcessor.java:37)
	at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:72)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:168)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:142)
	at spoon.reflect.visitor.CtScanner.visitCtBlock(CtScanner.java:297)
	at spoon.support.reflect.code.CtBlockImpl.accept(CtBlockImpl.java:57)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:176)
	at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:68)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:168)
	at spoon.reflect.visitor.CtScanner.visitCtMethod(CtScanner.java:555)
	at spoon.support.reflect.declaration.CtMethodImpl.accept(CtMethodImpl.java:58)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:176)
	at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:68)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:168)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:142)
	at spoon.reflect.visitor.CtScanner.visitCtClass(CtScanner.java:334)
	at spoon.support.reflect.declaration.CtClassImpl.accept(CtClassImpl.java:58)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:176)
	at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:68)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:168)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:142)
	at spoon.reflect.visitor.CtScanner.visitCtPackage(CtScanner.java:645)
	at spoon.support.reflect.declaration.CtPackageImpl.accept(CtPackageImpl.java:89)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:176)
	at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:68)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:168)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:142)
	at spoon.reflect.visitor.CtScanner.visitCtPackage(CtScanner.java:644)
	at spoon.support.reflect.declaration.CtPackageImpl.accept(CtPackageImpl.java:89)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:176)
	at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:68)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:168)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:142)
	at spoon.reflect.visitor.CtScanner.visitCtPackage(CtScanner.java:644)
	at spoon.support.reflect.declaration.CtPackageImpl.accept(CtPackageImpl.java:89)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:176)
	at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:68)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:168)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:142)
	at spoon.reflect.visitor.CtScanner.visitCtPackage(CtScanner.java:644)
	at spoon.support.reflect.declaration.CtPackageImpl.accept(CtPackageImpl.java:89)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:176)
	at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:68)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:168)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:142)
	at spoon.reflect.visitor.CtScanner.visitCtPackage(CtScanner.java:644)
	at spoon.support.reflect.declaration.CtPackageImpl.accept(CtPackageImpl.java:89)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:176)
	at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:68)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:168)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:142)
	at spoon.reflect.visitor.CtScanner.visitCtPackage(CtScanner.java:644)
	at spoon.support.reflect.declaration.CtPackageImpl.accept(CtPackageImpl.java:89)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:176)
	at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:68)
	at spoon.support.QueueProcessingManager.process(QueueProcessingManager.java:120)
	at spoon.support.QueueProcessingManager.process(QueueProcessingManager.java:139)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.instantiateAndProcess(JDTBasedSpoonCompiler.java:181)
	at spoon.Launcher.process(Launcher.java:763)
	at code.Starter.main(Starter.java:35)

**Comment by LuckyboyYu** [comment]
ObjectReferenceProcessor.java and Starter.java are defined myself.

`public void process(CtLoop oneLoop) {
        CtStatement loopBody = oneLoop.getBody();
        List<CtLocalVariable<?>> localVariables = loopBody.filterChildren(new AbstractFilter<CtLocalVariable<?>>() {
            @Override
            public boolean matches(CtLocalVariable variable) {
                return (null != variable.getDefaultExpression());
            }
        }).list();
        if (null == localVariables) {
            localVariables = new ArrayList<>();
        }
        int localVariablesSize = localVariables.size() - 1;
        CtLocalVariable<?> localVariable;
        CtLocalVariable<?> tmpLocalVariable;
        CtCodeSnippetStatement snippet;
        String snippetValue;
        CtExpression<?> localVariableDefaultExpression;

        for (int i = localVariablesSize; i >= 0; i--) {
            localVariable = localVariables.get(i);
            tmpLocalVariable = localVariable.clone();
            localVariableDefaultExpression = tmpLocalVariable.getDefaultExpression();
            localVariableDefaultExpression.delete();
            oneLoop.insertBefore(tmpLocalVariable);
            localVariableDefaultExpression = localVariable.getDefaultExpression();
            if (localVariableDefaultExpression != null) {
                snippet = this.getFactory().Core().createCodeSnippetStatement();
                snippetValue = String.format("%s = %s", localVariable.getSimpleName(), localVariableDefaultExpression.toString());
                snippet.setValue(snippetValue);
                // statement one
                localVariable.insertAfter(snippet);
            }
            // statement two
            localVariable.delete();
        }
    }`

Both statement one and statement two will cause this Exception.

**Comment by monperrus** [comment]
AFAIU, you cannot call `localVariable.insertAfter` because it's already in the AST.

either you call `localVariable.delete` first or maybe you mean `snippet.insertAfter(localVariable)` instead?

**Comment by LuckyboyYu** [comment]
> AFAIU, you cannot call `localVariable.insertAfter` because it's already in the AST.
> 
> either you call `localVariable.delete` first or maybe you mean `snippet.insertAfter(localVariable)` instead?

I want to insert snippet after the variable then delete this variable.

**Comment by LuckyboyYu** [comment]
I ran my program just now and I found that it worked, maybe it's because I had done some changes to the input source code.
Anyway, Martin, thanks for your suggestion!
