### ISSUE TITLE
NPE in the recent addition in JDTTreeBuilder class

### ISSUE THREAD

**Issue by leventov** [INRIA/spoon#347]
I try to compile some of my sources and get NPE:

```
Caused by: java.lang.NullPointerException
        at spoon.support.compiler.jdt.JDTTreeBuilder.visit(JDTTreeBuilder.java:2255)
        at org.eclipse.jdt.internal.compiler.ast.MessageSend.traverse(MessageSend.java:1008)
        at org.eclipse.jdt.internal.compiler.ast.Block.traverse(Block.java:136)
        at org.eclipse.jdt.internal.compiler.ast.IfStatement.traverse(IfStatement.java:281)
        at org.eclipse.jdt.internal.compiler.ast.Block.traverse(Block.java:136)
        at spoon.support.compiler.jdt.JDTTreeBuilder.visit(JDTTreeBuilder.java:1579)
        at org.eclipse.jdt.internal.compiler.ast.LambdaExpression.traverse(LambdaExpression.java:665)
        at spoon.support.compiler.jdt.JDTTreeBuilder.visit(JDTTreeBuilder.java:2279)
        at org.eclipse.jdt.internal.compiler.ast.MessageSend.traverse(MessageSend.java:1008)
        at org.eclipse.jdt.internal.compiler.ast.Block.traverse(Block.java:136)
        at spoon.support.compiler.jdt.JDTTreeBuilder.visit(JDTTreeBuilder.java:2134)
        at org.eclipse.jdt.internal.compiler.ast.ForStatement.traverse(ForStatement.java:409)
        at org.eclipse.jdt.internal.compiler.ast.Block.traverse(Block.java:136)
        at spoon.support.compiler.jdt.JDTTreeBuilder.visit(JDTTreeBuilder.java:2855)
        at org.eclipse.jdt.internal.compiler.ast.TryStatement.traverse(TryStatement.java:1124)
        at spoon.support.compiler.jdt.JDTTreeBuilder.visit(JDTTreeBuilder.java:2360)
        at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.traverse(MethodDeclaration.java:317)
        at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.traverse(TypeDeclaration.java:1490)
        at spoon.support.compiler.jdt.JDTTreeBuilder.visit(JDTTreeBuilder.java:2991)
        at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.traverse(TypeDeclaration.java:1338)
        at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.traverse(CompilationUnitDeclaration.java:748)
        at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.traverse(CompilationUnitDeclaration.java:709)
        at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildSources(JDTBasedSpoonCompiler.java:227)
        at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:480)
        at spoon.Launcher.buildModel(Launcher.java:748)
...
```

Seems the NPE in the source that was added recently:
https://github.com/INRIA/spoon/commit/287f4c77e9ff845c193e09adc2bd6589cd551ad7

**Comment by GerardPaligot** [comment]
Do you have a snippet to get this NullPointerException? That will be hard for me to reproduce without it.

**Comment by leventov** [comment]
It occurs when compiling this line: https://github.com/OpenHFT/Chronicle-Map/blob/master/src/main/java/net/openhft/chronicle/map/ReplicatedChronicleMap.java#L832

In this line: https://github.com/INRIA/spoon/blob/5a20172ed48e74f03e13a20f893b9a0a8e157ba9/src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java#L2255 `messageSend` represents `LOG.debug(...)` token, `reciever` - `LOG`, and it's `binding` field is `null`, that's why `binding.readableName()` throws NPE.

I thought this is because static field is accessed within a lambda, but small test created:

```
package spoon.test.my;

import java.util.logging.Logger;

public class MyClass {
    private static final Logger LOG = Logger.getGlobal();

    public void foo() {
        Runnable r = () -> {
            LOG.info("bla");
        };
    }
}
```

and the test:

```
package spoon.test.my;

import org.junit.Test;
import spoon.Launcher;
import spoon.compiler.SpoonResourceHelper;
import spoon.reflect.factory.Factory;

import java.io.FileNotFoundException;

public class MyTest {

    @Test
    public void test() throws FileNotFoundException {
        Launcher spoon = new Launcher();
        Factory factory = spoon.createFactory();
        factory.getEnvironment().setComplianceLevel(8);
        spoon.createCompiler(
                factory,
                SpoonResourceHelper
                        .resources("./src/test/java/spoon/test/my/MyClass.java"))
                .build();
    }
}
```

work fine.

**Comment by GerardPaligot** [comment]
PR done (https://github.com/INRIA/spoon/pull/365) but I didn't get a NPE. I think this PR (https://github.com/INRIA/spoon/pull/350/files) has corrected your bug.

**Comment by leventov** [comment]
Thanks, will give it a try.

**Comment by leventov** [comment]
Yes, the test from my previous comment passed too, but the real code thrown NPE. I wrote that failed to extract some "small" test to identify the bug.

**Comment by leventov** [comment]
@monperrus probably there is a misunderstanding: the test I suggested was never failing. I haven't yet tried to compile the real code, which was failing, with the latest spoon master branch version.

**Comment by GerardPaligot** [comment]
> I haven't yet tried to compile the real code, which was failing, with the latest spoon master branch version.

Can you try? We don't call anymore `readableName()` method so everything should be fine.

**Comment by leventov** [comment]
@GerardPaligot yes, I will (I wrote "will give it a try"), but probably not today. BTW it's ok if this issue stay closed; if my testing will show the issue has not gone, it could be always reopened.

**Comment by GerardPaligot** [comment]
> if my testing will show the issue has not gone, it could be always reopened.

I encourage you to do that. :)

**Comment by leventov** [comment]
Well, it works without NPE now on the real code. The question is closed.
