### ISSUE TITLE
Spoon Core-8.0.0 : SpoonPom throw NullPoinerException because BuildBase may be null

### ISSUE THREAD

**Issue by Scemoon** [INRIA/spoon#3508]
Method:
private String getSourceVersion(BuildBase build) {
}

show:
Exception in thread "main" java.lang.NullPointerException
	at spoon.support.compiler.SpoonPom.getSourceVersion(SpoonPom.java:284)
	at spoon.support.compiler.SpoonPom.getSourceVersion(SpoonPom.java:252)
	at spoon.MavenLauncher.init(MavenLauncher.java:135)
	at spoon.MavenLauncher.<init>(MavenLauncher.java:83)
	at spoon.MavenLauncher.<init>(MavenLauncher.java:61)

**Comment by monperrus** [comment]
Thanks for the bug report. Could you try with version 8.2.0?

**Comment by monperrus** [comment]
That was fixed by #3346
