### ISSUE TITLE
Analyzing project creates a NullPointerException

### ISSUE THREAD

**Issue by layornos** [INRIA/spoon#3514]
Hi @ll,

when I try analyzing the project [1] I am getting the following exception
```
[main] INFO spoon.Launcher - Running in NOCLASSPATH mode (doc: http://spoon.gforge.inria.fr/launcher.html).
[main] DEBUG spoon.support.compiler.jdt.JDTTreeBuilder - Could not find declaration for variable StereotypeAPI at (./Palladio-Analyzer-SimuLizar/bundles/org.palladiosimulator.simulizar.action.repository/src/org/palladiosimulator/simulizar/action/repository/black/ProfilesLibrary.java:76).
[main] DEBUG spoon.support.compiler.jdt.JDTTreeBuilder - Could not find declaration for variable LOGGER at (./Palladio-Analyzer-SimuLizar/bundles/org.palladiosimulator.simulizar.action/src-man/org/palladiosimulator/simulizar/action/interpreter/TransientEffectInterpreter.java:371).
[main] DEBUG spoon.support.compiler.jdt.JDTTreeBuilder - Could not find declaration for variable state at (./Palladio-Analyzer-SimuLizar/bundles/org.palladiosimulator.simulizar.action/src-man/org/palladiosimulator/simulizar/action/interpreter/TransientEffectInterpreter.java:373).
[main] DEBUG spoon.support.compiler.jdt.JDTTreeBuilder - Could not find declaration for variable LOGGER at (./Palladio-Analyzer-SimuLizar/bundles/org.palladiosimulator.simulizar.action/src-man/org/palladiosimulator/simulizar/action/interpreter/TransientEffectInterpreter.java:396).
[main] DEBUG spoon.support.compiler.jdt.JDTTreeBuilder - Could not find declaration for variable MetricDescriptionUtility at (./Palladio-Analyzer-SimuLizar/bundles/org.palladiosimulator.simulizar.slidingwindow/src/org/palladiosimulator/simulizar/slidingwindow/probeframework/SlidingWindowProbeFrameWorkListenerDecorator.java:100).
[main] DEBUG spoon.support.compiler.jdt.JDTTreeBuilder - Could not find declaration for variable MetricDescriptionUtility at (./Palladio-Analyzer-SimuLizar/bundles/org.palladiosimulator.simulizar.slidingwindow/src/org/palladiosimulator/simulizar/slidingwindow/runtimemeasurement/SlidingWindowRuntimeMeasurementsRecorder.java:88).
[main] DEBUG spoon.support.compiler.jdt.JDTTreeBuilder - Could not find declaration for variable MetricDescriptionUtility at (./Palladio-Analyzer-SimuLizar/bundles/org.palladiosimulator.simulizar/src/org/palladiosimulator/simulizar/interpreter/listener/DeferredMeasurementInitialization.java:66).
[main] DEBUG spoon.support.compiler.jdt.JDTTreeBuilder - Could not find declaration for variable Supplier at (./Palladio-Analyzer-SimuLizar/bundles/org.palladiosimulator.simulizar/src/org/palladiosimulator/simulizar/interpreter/listener/DeferredMeasurementInitialization.java:70).
[main] DEBUG spoon.support.compiler.jdt.JDTTreeBuilder - Could not find declaration for variable MetricDescriptionUtility at (./Palladio-Analyzer-SimuLizar/bundles/org.palladiosimulator.simulizar/src/org/palladiosimulator/simulizar/interpreter/listener/DeferredMeasurementInitialization.java:122).
[main] DEBUG spoon.support.compiler.jdt.JDTTreeBuilder - Could not find declaration for variable String at (./Palladio-Analyzer-SimuLizar/bundles/org.palladiosimulator.simulizar/src/org/palladiosimulator/simulizar/modelobserver/ResourceEnvironmentSyncer.java:289).
[main] DEBUG spoon.support.compiler.jdt.JDTTreeBuilder - Could not find declaration for variable MetricDescriptionUtility at (./Palladio-Analyzer-SimuLizar/bundles/org.palladiosimulator.simulizar/src/org/palladiosimulator/simulizar/utils/MonitorRepositoryUtil.java:72).
[main] DEBUG spoon.support.compiler.jdt.JDTTreeBuilder - Could not find declaration for variable MonitorRepositoryUtil at (./Palladio-Analyzer-SimuLizar/bundles/org.palladiosimulator.simulizar/src/org/palladiosimulator/simulizar/utils/MonitorRepositoryUtil.java:200).
[main] DEBUG spoon.support.compiler.jdt.JDTTreeBuilder - Could not find declaration for variable SimuLizarMockUtils at (./Palladio-Analyzer-SimuLizar/tests/org.palladiosimulator.simulizar.tests/src/org/palladiosimulator/simulizar/test/SimuLizarTestExtension.java:73).
[main] DEBUG spoon.support.compiler.jdt.JDTTreeBuilder - Could not find declaration for variable e at (./Palladio-Analyzer-SimuLizar/tests/org.palladiosimulator.simulizar.tests/src/org/palladiosimulator/simulizar/test/SimuLizarTestExtension.java:100).
[main] DEBUG spoon.support.compiler.jdt.JDTTreeBuilder - Could not find declaration for variable Streams at (./Palladio-Analyzer-SimuLizar/tests/org.palladiosimulator.simulizar.tests/src/org/palladiosimulator/simulizar/test/SimuLizarTestExtension.java:142).
[main] DEBUG spoon.support.compiler.jdt.JDTTreeBuilder - Could not find declaration for variable EcoreUtil at (./Palladio-Analyzer-SimuLizar/tests/org.palladiosimulator.simulizar.tests/src/org/palladiosimulator/simulizar/test/SimuLizarTestExtension.java:142).
[main] DEBUG spoon.support.compiler.jdt.JDTTreeBuilder - Could not find declaration for variable e at (./Palladio-Analyzer-SimuLizar/tests/org.palladiosimulator.simulizar.tests/src/org/palladiosimulator/simulizar/test/SimuLizarTestExtension.java:165).
Exception in thread "main" java.lang.NullPointerException
	at spoon.support.reflect.declaration.CtTypeImpl.getPackageReference(CtTypeImpl.java:312)
	at spoon.support.reflect.declaration.CtTypeImpl.shouldIncludeSamePackage(CtTypeImpl.java:286)
	at spoon.support.reflect.declaration.CtTypeImpl.getUsedTypes(CtTypeImpl.java:278)
	at App.lambda$main$1(App.java:13)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
	at App.main(App.java:12)

Process finished with exit code 1

```

The minimal example to reproduce the exception looks as follows:
```
import spoon.Launcher;
import spoon.reflect.CtModel;

public class App {
    public static void main(String[] args) {
        // https://github.com/PalladioSimulator/Palladio-Analyzer-SimuLizar
        String path = "./Palladio-Analyzer-SimuLizar";
        Launcher launcher = new Launcher();
        launcher.addInputResource(path);
        launcher.getEnvironment().setNoClasspath(true);
        CtModel model = launcher.buildModel();

        model.getAllTypes().forEach(type -> {
            type.getUsedTypes(false).forEach(usedType -> {
                System.out.println(usedType.getSimpleName());
            });
        });
    }
}
```

I am new to Spoon, thus I have no idea whether it is my fault or if there might be a bug.

Regards,
Sandro

[1] https://github.com/PalladioSimulator/Palladio-Analyzer-SimuLizar

**Comment by monperrus** [comment]
Thanks a lot for the bug report, which version are you using?

**Comment by MartinWitt** [comment]
I can reproduce the bug with version 8.2.

**Comment by layornos** [comment]
> Thanks a lot for the bug report, which version are you using?

8.3.0-beta-1

**Comment by MartinWitt** [comment]
#3515  fixes the bug.

**Comment by monperrus** [comment]
@layornos do you confirm that #3515 fixes the bug?

**Comment by layornos** [comment]
The NPE no longer occurs, but now I get the following exception:
```
Exception in thread "main" java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.base/java.util.TimSort.mergeHi(TimSort.java:903)
	at java.base/java.util.TimSort.mergeAt(TimSort.java:520)
	at java.base/java.util.TimSort.mergeCollapse(TimSort.java:448)
	at java.base/java.util.TimSort.sort(TimSort.java:245)
	at java.base/java.util.Arrays.sort(Arrays.java:1516)
	at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:353)
	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:210)
	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:161)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:300)
	at java.base/java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
	at java.base/java.lang.Iterable.forEach(Iterable.java:74)
	at App.lambda$main$1(App.java:13)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at App.main(App.java:13)
```
I've tried it with Java 11 and 13 on a Mac.

**Comment by monperrus** [comment]
>     I've added the minimal example to my current spring project, there I get the following exception: `Exception in thread "main" java.lang.IllegalArgumentException: Comparison method violates its general contract!`

That's a different error. Would you create a new issue or PR with a failing test case? That would be super useful!

**Comment by MartinWitt** [comment]
After  a short slack chat, I found the reason for his bug. Try to formulate the bugfix in a real PR later.
