### ISSUE TITLE
Not allowed javaletter or symbol found

### ISSUE THREAD

**Issue by darius-sas** [INRIA/spoon#3564]
Hi,
I am using spoon for my PhD research and I am encountering the following exception while analysing several projects.

```
Caused by: spoon.SpoonException: Not allowed javaletter or keyword in identifier found. See JLS for correct identifier. Identifier: ?
	at spoon.support.reflect.reference.CtReferenceImpl.checkIdentiferForJLSCorrectness(CtReferenceImpl.java:108)
	at spoon.support.reflect.reference.CtReferenceImpl.setSimpleName(CtReferenceImpl.java:52)
	at spoon.reflect.factory.TypeFactory.createIntersectionTypeReferenceWithBounds(TypeFactory.java:703)
	at spoon.support.compiler.jdt.ReferenceBuilder.getTypeReference(ReferenceBuilder.java:983)
	at spoon.support.compiler.jdt.ReferenceBuilder.getTypeReference(ReferenceBuilder.java:745)
	at spoon.support.compiler.jdt.ReferenceBuilder.getTypeReference(ReferenceBuilder.java:790)
	at spoon.support.compiler.jdt.ReferenceBuilder.getExecutableReference(ReferenceBuilder.java:402)
	at spoon.support.compiler.jdt.ReferenceBuilder.getExecutableReference(ReferenceBuilder.java:473)
	at spoon.support.compiler.jdt.JDTTreeBuilder.visit(JDTTreeBuilder.java:1398)
	at org.eclipse.jdt.internal.compiler.ast.MessageSend.traverse(MessageSend.java:1109)
	at org.eclipse.jdt.internal.compiler.ast.MessageSend.traverse(MessageSend.java:1119)
	at spoon.support.compiler.jdt.JDTTreeBuilder.visit(JDTTreeBuilder.java:1057)
	at org.eclipse.jdt.internal.compiler.ast.CastExpression.traverse(CastExpression.java:705)
	at org.eclipse.jdt.internal.compiler.ast.ReturnStatement.traverse(ReturnStatement.java:379)
	at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.traverse(MethodDeclaration.java:365)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.traverse(TypeDeclaration.java:1479)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.traverse(CompilationUnitDeclaration.java:826)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.traverse(CompilationUnitDeclaration.java:787)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.lambda$buildModel$0(JDTBasedSpoonCompiler.java:437)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.forEachCompilationUnit(JDTBasedSpoonCompiler.java:466)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildModel(JDTBasedSpoonCompiler.java:435)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildUnitsAndModel(JDTBasedSpoonCompiler.java:372)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildSources(JDTBasedSpoonCompiler.java:337)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:114)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:97)
	at spoon.Launcher.buildModel(Launcher.java:755)
	at com.arcan.parser.java.JavaSourceGraphBuilder.init(JavaSourceGraphBuilder.java:69)
	... 17 more
```
The project I was analysing in this particular case is Byte-buddy, but there were no logging details on what file and where in the file this is happening (even setting debug level to ALL using `Environment#setlevel()`)

Any hints on how to avoid it? I leave more details about my environment below.

Thank you very much for your help!

Java:
```
openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment (build 11.0.5+10-post-Ubuntu-0ubuntu1.119.04)
OpenJDK 64-Bit Server VM (build 11.0.5+10-post-Ubuntu-0ubuntu1.119.04, mixed mode, sharing)
```
Spoon 8.2.0 (used as a library) with the following settings
```
environment.setEncoding(StandardCharsets.UTF_8);
environment.disableConsistencyChecks();
environment.setComplianceLevel(9);
environment.setIgnoreDuplicateDeclarations(true);
environment.setCommentEnabled(false);
environment.setNoClasspath(true);
environment.setShouldCompile(false);
```
I tried with both a `MavenLauncher` and a normal `Launcher`.

**Comment by darius-sas** [comment]
Thanks for the info.
The hash is this one, in case anyone else needs it: 
`6b1bc2a5e07db2597969af274b4eca3ed31fb5bd`

**Comment by MartinWitt** [comment]
Just a small info i found the bug and created a testcase. Bugfix should be created in the next days.
