### ISSUE TITLE
"spoon.support.SpoonClassNotFoundException: cannot create shadow class: liquibase.snapshot.DatabaseSnapshot" exception with dropwizard repo

### ISSUE THREAD

**Issue by Strum355** [INRIA/spoon#3579]
I've created a runnable test that reproduces the issue @ https://github.com/Strum355/spoon/tree/nsc/dropwizard-bug with `./gradlew test --tests spoon.support.compiler.jdt.JDTBasedSpoonCompilerTest.dropwizardClassIssue`

<details>
<summary>Stacktrace</summary>

```
spoon.support.compiler.jdt.JDTBasedSpoonCompilerTest > dropwizardClassIssue FAILED
    spoon.support.SpoonClassNotFoundException: cannot create shadow class: liquibase.snapshot.DatabaseSnapshot
        at spoon.reflect.factory.TypeFactory.get(TypeFactory.java:566)
        at spoon.support.compiler.jdt.JDTImportBuilder.getOrLoadClass(JDTImportBuilder.java:153)
        at spoon.support.compiler.jdt.JDTImportBuilder.build(JDTImportBuilder.java:78)
        at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.lambda$buildModel$1(JDTBasedSpoonCompiler.java:441)
        at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.forEachCompilationUnit(JDTBasedSpoonCompiler.java:466)
        at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildModel(JDTBasedSpoonCompiler.java:440)
        at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildUnitsAndModel(JDTBasedSpoonCompiler.java:372)
        at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildSources(JDTBasedSpoonCompiler.java:337)
        at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:114)
        at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:97)
        at spoon.Launcher.buildModel(Launcher.java:755)
        at spoon.support.compiler.jdt.JDTBasedSpoonCompilerTest.dropwizardClassIssue(JDTBasedSpoonCompilerTest.java:58)

        Caused by:
        java.lang.ExceptionInInitializerError
            at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
            at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1140)
            at java.base/jdk.internal.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)
            at java.base/jdk.internal.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:184)
            at java.base/java.lang.reflect.Field.acquireFieldAccessor(Field.java:1103)
            at java.base/java.lang.reflect.Field.getFieldAccessor(Field.java:1084)
            at java.base/java.lang.reflect.Field.get(Field.java:416)
            at spoon.support.visitor.java.JavaReflectionTreeBuilder.visitField(JavaReflectionTreeBuilder.java:296)
            at spoon.support.visitor.java.JavaReflectionVisitorImpl.visitClass(JavaReflectionVisitorImpl.java:92)
            at spoon.support.visitor.java.JavaReflectionTreeBuilder.visitClass(JavaReflectionTreeBuilder.java:152)
            at spoon.support.visitor.java.JavaReflectionTreeBuilder.scan(JavaReflectionTreeBuilder.java:109)
            at spoon.reflect.factory.TypeFactory.get(TypeFactory.java:564)
            ... 11 more

            Caused by:
            liquibase.exception.UnexpectedLiquibaseException: Cannot find default log service
                at liquibase.Scope.getCurrentScope(Scope.java:70)
                at liquibase.snapshot.DatabaseSnapshot.<clinit>(DatabaseSnapshot.java:33)
                ... 23 more
```

</details>

**Comment by LakshyAAAgrawal** [comment]
On executing ```mvn -e test -D test=spoon/support/compiler/jdt/JDTBasedSpoonCompilerTest.java``` on the repo mentioned, I get the following:
```
[INFO] Running spoon.support.compiler.jdt.JDTBasedSpoonCompilerTest
20:16:10.797 [main] INFO spoon.Launcher - Running in NOCLASSPATH mode (doc: http://spoon.gforge.inria.fr/launcher.html).
20:16:17.890 [main] INFO spoon.Launcher - Running in NOCLASSPATH mode (doc: http://spoon.gforge.inria.fr/launcher.html).
20:16:20.355 [Thread-2] DEBUG spoon.Launcher - [INFO] Scanning for projects...
20:16:20.477 [Thread-2] DEBUG spoon.Launcher - [ERROR] [ERROR] Some problems were encountered while processing the POMs:
20:16:20.482 [Thread-2] DEBUG spoon.Launcher - [FATAL] Non-resolvable parent POM for io.dropwizard:dropwizard-migrations:2.1.0-SNAPSHOT: Could not find artifact io.dropwizard:dropwizard-parent:pom:2.1.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 5, column 13
20:16:20.482 [Thread-2] DEBUG spoon.Launcher -  @ 
20:16:20.484 [Thread-2] DEBUG spoon.Launcher - [ERROR] The build could not read 1 project -> [Help 1]
20:16:20.485 [Thread-2] DEBUG spoon.Launcher - [ERROR]   
20:16:20.489 [Thread-2] DEBUG spoon.Launcher - [ERROR]   The project io.dropwizard:dropwizard-migrations:2.1.0-SNAPSHOT (./src/test/resources/dropwizardtest/dropwizard/dropwizard-migrations/pom.xml) has 1 error
20:16:20.493 [Thread-2] DEBUG spoon.Launcher - [ERROR]     Non-resolvable parent POM for io.dropwizard:dropwizard-migrations:2.1.0-SNAPSHOT: Could not find artifact io.dropwizard:dropwizard-parent:pom:2.1.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 5, column 13 -> [Help 2]
20:16:20.494 [Thread-2] DEBUG spoon.Launcher - [ERROR] 
20:16:20.497 [Thread-2] DEBUG spoon.Launcher - [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
20:16:20.498 [Thread-2] DEBUG spoon.Launcher - [ERROR] Re-run Maven using the -X switch to enable full debug logging.
20:16:20.498 [Thread-2] DEBUG spoon.Launcher - [ERROR] 
20:16:20.499 [Thread-2] DEBUG spoon.Launcher - [ERROR] For more information about the errors and possible solutions, please read the following articles:
20:16:20.500 [Thread-2] DEBUG spoon.Launcher - [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
20:16:20.501 [Thread-2] DEBUG spoon.Launcher - [ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
20:16:21.876 [main] DEBUG spoon.support.compiler.jdt.JDTTreeBuilder - Could not find declaration for variable Maps at (src/test/resources/dropwizardtest/dropwizard/dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbLocksCommandTest.java:47).
20:16:21.893 [main] DEBUG spoon.support.compiler.jdt.JDTTreeBuilder - Could not find declaration for variable Maps at (src/test/resources/dropwizardtest/dropwizard/dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbLocksCommandTest.java:56).
20:16:21.939 [main] DEBUG spoon.support.compiler.jdt.JDTTreeBuilder - Could not find declaration for variable Maps at (src/test/resources/dropwizardtest/dropwizard/dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbMigrateCustomSchemaTest.java:38).
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 12.45 s - in spoon.support.compiler.jdt.JDTBasedSpoonCompilerTest
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  19.059 s
[INFO] Finished at: 2020-09-27T20:16:23+05:30
[INFO] ------------------------------------------------------------------------
```

**Comment by MartinWitt** [comment]
Has someone else tested it and can confirm the existence of the bug?
