### ISSUE TITLE
CtMethodImpl does not have CtRole.STATEMENT when add a clone statement to a new method body

### ISSUE THREAD

**Issue by peroksid90** [INRIA/spoon#3659]
Here is a snipped to reproduce the issue

` 
        Launcher launcher = new Launcher();
        launcher.addInputResource("/home/user/TestClass2.java");
        launcher.buildModel();
        CtModel model = launcher.getModel();
        List<CtMethod> methods = model.getElements(new TypeFilter(CtMethod.class));
        CtMethod m = methods.get(0);
        CtStatement stmt = m.getBody().getStatement(0);

        CtBlock b = launcher.getFactory().Core().createBlock();
        
        //If you comment the next line - everything will work.
        b.addStatement(stmt.clone()); //if you replace 'stmt.clone()' to 'launcher.getFactory().Core().createBlock()' - it will work.
        m.setBody(b);
     
        System.out.println(m); //It works OK!
        System.out.println(m.getOriginalSourceFragment().getSourceCode()); //The error is here , Tester.java:32
`

TestClass2.java

`
public class TestClass {
    int a = 0;
    void f() {
        a++;
    }
}
`

`
Exception in thread "main" spoon.SpoonException: The element of class class spoon.support.reflect.declaration.CtMethodImpl does not have CtRole.STATEMENT
	at spoon.reflect.meta.impl.RoleHandlerHelper.getRoleHandler(RoleHandlerHelper.java:57)
	at spoon.support.sniper.internal.ElementSourceFragment.getRoleHandler(ElementSourceFragment.java:257)
	at spoon.support.sniper.internal.ElementSourceFragment.addChild(ElementSourceFragment.java:240)
	at spoon.support.sniper.internal.ElementSourceFragment.access$000(ElementSourceFragment.java:51)
	at spoon.support.sniper.internal.ElementSourceFragment$1.enter(ElementSourceFragment.java:200)
	at spoon.reflect.visitor.CtScanner.visitCtUnaryOperator(CtScanner.java:798)
	at spoon.support.reflect.code.CtUnaryOperatorImpl.accept(CtUnaryOperatorImpl.java:36)
	at spoon.reflect.visitor.EarlyTerminatingScanner.doScan(EarlyTerminatingScanner.java:145)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:121)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:169)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:106)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:83)
	at spoon.reflect.visitor.CtScanner.visitCtBlock(CtScanner.java:299)
	at spoon.support.reflect.code.CtBlockImpl.accept(CtBlockImpl.java:58)
	at spoon.reflect.visitor.EarlyTerminatingScanner.doScan(EarlyTerminatingScanner.java:145)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:121)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:169)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:106)
	at spoon.reflect.visitor.CtScanner.visitCtMethod(CtScanner.java:556)
	at spoon.support.reflect.declaration.CtMethodImpl.accept(CtMethodImpl.java:58)
	at spoon.reflect.visitor.EarlyTerminatingScanner.doScan(EarlyTerminatingScanner.java:145)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:121)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:169)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:106)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:83)
	at spoon.reflect.visitor.CtScanner.visitCtClass(CtScanner.java:335)
	at spoon.support.reflect.declaration.CtClassImpl.accept(CtClassImpl.java:58)
	at spoon.reflect.visitor.EarlyTerminatingScanner.doScan(EarlyTerminatingScanner.java:145)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:121)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:169)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:106)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:83)
	at spoon.reflect.visitor.EarlyTerminatingScanner.visitCtCompilationUnit(EarlyTerminatingScanner.java:160)
	at spoon.support.reflect.declaration.CtCompilationUnitImpl.accept(CtCompilationUnitImpl.java:407)
	at spoon.reflect.visitor.EarlyTerminatingScanner.doScan(EarlyTerminatingScanner.java:145)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:121)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:169)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:106)
	at spoon.support.sniper.internal.ElementSourceFragment.createSourceFragmentsFrom(ElementSourceFragment.java:228)
	at spoon.support.reflect.declaration.CtCompilationUnitImpl.getOriginalSourceFragment(CtCompilationUnitImpl.java:359)
	at spoon.support.reflect.declaration.CtElementImpl.getOriginalSourceFragment(CtElementImpl.java:601)
	at com.licel.testspoon.Tester.main(Tester.java:32)
`

**Comment by slarse** [comment]
The root cause of this issue is that the added body does not have a source position. Therefore, when getting here with the `CtBlock b` that was created in the snippet: https://github.com/INRIA/spoon/blob/4ccbf0a1e7cc092d2b75aac767d3797eb10c0399/src/main/java/spoon/support/sniper/internal/ElementSourceFragment.java#L200-L202

`currentFragment` becomes `null`. Therefore, the `CtBlock` is not pushed to the `parents` stack, making the method itself the most recent parent. When `a++` is then scanned as a statement shortly thereafter, the most recent parent is still the containing method, which causes the crash.

This problem applies to _any_ use of `getOriginalSourceFragment` when one has inserted an element _with_ child elements (that part is important, it's fine to add a new element that does not have child elements) and without a source position. It seems to me like the current implementation that builds the source fragments simply does not support building them after the AST has been modified.

There's a fairly simple workaround for this, and that is to get any source fragment before making modifications. That way, the root fragment will be built and stored, and any subsequent calls to `getOriginalSourceFragment` will not actually traverse the AST. For example, adding this statement before modifying the AST solves the issue:

```java
        // side effect: builds the root fragment for the compilation unit
        model.getAllTypes().stream().findFirst().get().getOriginalSourceFragment();
```

This is obviously very unintuitive. Perhaps we can add a check in `getOriginalSourceFragment` that simply throws an exception with an informative message, if the AST has been modified?
