### ISSUE TITLE
parameter.getReference() would set parent of parameter type, and Spoon cannot get declaration of generic method by reference.

### ISSUE THREAD

**Issue by QifanWang** [INRIA/spoon#3671]
I'm working with Spoon 8.3.0, and I want to analyze some Java8 code.

Here is a snippet to reproduce the issue

```
        SpoonAPI spoon = new Launcher();
        spoon.addInputResource("/home/usr/TestGeneric.java");
        spoon.buildModel();

        Map<CtExecutableReference<?>, List<CtParameterReference<?>>> exe2Parameter =
                new HashMap<>();
        for (CtExecutable<?> cm : spoon.getModel().getRootPackage()
               .getElements(new TypeFilter<>(CtExecutable.class))) {

            List<CtParameterReference<?>> pList = new ArrayList<>();
            for(CtParameter<?> parameter : cm.getParameters()) {
                //getReference() change the parameter.getType().getParent()
                pList.add(parameter.getReference());
            }
            exe2Parameter.put(cm.getReference(), pList);
        }
        for (CtExecutableReference<?> exeRef : exe2Parameter.keySet()) {
            //Getting declaration of generic method would throw exception.
            System.out.println(exeRef.getExecutableDeclaration());
        }
```
TestGeneric.java
```
public class TestGeneric {
    public static class Cell<T> {
        public T val;
        public T getVal() { return val; }
        public void setVal(T val) { this.val = val;}
    }

    public static class Day {
        public int day;
        public Day() { }
        public Day(int val) {this.day = val;}
    }

    public void bar() {
        Cell<Day> c = new Cell<>();
        Day e = new Day();
        c.setVal(e);
    }
}
```

```
Exception in thread "main" spoon.SpoonException: Cannot resolve type erasure of the type parameter reference, which is not able to found it's declaration.
	at spoon.support.reflect.reference.CtTypeParameterReferenceImpl.getTypeErasure(CtTypeParameterReferenceImpl.java:180)
	at spoon.support.reflect.declaration.CtTypeImpl.isSameParameter(CtTypeImpl.java:752)
	at spoon.support.reflect.declaration.CtTypeImpl.hasSameParameters(CtTypeImpl.java:744)
	at spoon.support.reflect.declaration.CtTypeImpl.getMethod(CtTypeImpl.java:718)
	at spoon.support.reflect.reference.CtExecutableReferenceImpl.getCtExecutable(CtExecutableReferenceImpl.java:121)
	at spoon.support.reflect.reference.CtExecutableReferenceImpl.getExecutableDeclaration(CtExecutableReferenceImpl.java:113)
	at GetInvocation2.main(GetInvocation2.java:30)

```

Is this a bug, or I just need to avoid getting reference of method parameter before getting method declaration?

**Comment by andrewbwogi** [comment]
Hi @QifanWang, I'll look into this problem.

**Comment by QifanWang** [comment]
@andrewbwogi THX!
I found getRefence() would set parent of parameter type.

Before parameter.getReference(), 
![before_getReference](https://user-images.githubusercontent.com/32841123/97832395-a1b97b80-1d0d-11eb-8336-ddab5bc086b5.png)

After parameter.getReference(),
![after_getReference](https://user-images.githubusercontent.com/32841123/97832510-f4933300-1d0d-11eb-95c2-47da7b43e8ef.png)

When getExecutableDeclaration() method try to compare parameter, calling getTypeErasure() would get null typeParam for handling parent of CtTypeParameterReferenceImpl. 
![2020-11-02 13-33-06 的屏幕截图](https://user-images.githubusercontent.com/32841123/97833269-fb22aa00-1d0f-11eb-9415-8aa2d6b64ded.png)
