### ISSUE TITLE
ParentNotInitializedException when using Java 14 switch expressions with cases which have multiple values

### ISSUE THREAD

**Issue by davidog23** [INRIA/spoon#3680]
spoon-core version: 8.3.0
Code to reproduce the bug:
```java
import spoon.Launcher;
import spoon.reflect.declaration.CtClass;
import spoon.reflect.declaration.CtElement;

public class A {
    public static void main(String[] args) {
        CtClass l = Launcher.parseClass("class A { { int x = switch(1) { case 1, 3 -> 0; default -> 1}; } }");
        for (CtElement a : l.asIterable()) {
            a.getParent();
        }
    }
}
```
```
Exception in thread "main" spoon.reflect.declaration.ParentNotInitializedException: parent not initialized for class spoon.support.reflect.code.CtLiteralImpl (unknown file)
	at spoon.support.reflect.declaration.CtElementImpl.getParent(CtElementImpl.java:366)
	at A.main(A.java:9)
```
The CtLiteralImpl which represents the number 3 throws a ParentNotInitializedException when getting its parent. I guess that is not intended behaviour.

**Comment by MartinWitt** [comment]
Fixed by #3689
