### ISSUE TITLE
bug: Crash when parsing RDF4J with "ignore duplicate declarations"

### ISSUE THREAD

**Issue by slarse** [INRIA/spoon#3707]
Hi,

When parsing [RDF4J](https://github.com/eclipse/rdf4j) with `env.setIgnoreDuplicateDeclarations(true)`, there's a crash with a null pointer dereference, as reported in SpoonLabs/sorald#124. The stacktrace looks like so:

```
Exception in thread "main" java.lang.NullPointerException
	at spoon.support.compiler.jdt.JDTTreeBuilderQuery.searchTypeBinding(JDTTreeBuilderQuery.java:78)
	at spoon.support.compiler.jdt.ReferenceBuilder.getQualifiedTypeReference(ReferenceBuilder.java:285)
	at spoon.support.compiler.jdt.JDTTreeBuilderHelper.createTypeAccess(JDTTreeBuilderHelper.java:449)
	at spoon.support.compiler.jdt.JDTTreeBuilderHelper.createTargetFieldAccess(JDTTreeBuilderHelper.java:667)
	at spoon.support.compiler.jdt.JDTTreeBuilderHelper.createVariableAccess(JDTTreeBuilderHelper.java:271)
	at spoon.support.compiler.jdt.JDTTreeBuilder.visit(JDTTreeBuilder.java:1471)
	at org.eclipse.jdt.internal.compiler.ast.QualifiedNameReference.traverse(QualifiedNameReference.java:1170)
	at org.eclipse.jdt.internal.compiler.ast.EqualExpression.traverse(EqualExpression.java:995)
	at org.eclipse.jdt.internal.compiler.ast.IfStatement.traverse(IfStatement.java:292)
	at org.eclipse.jdt.internal.compiler.ast.Block.traverse(Block.java:154)
	at org.eclipse.jdt.internal.compiler.ast.IfStatement.traverse(IfStatement.java:296)
	at org.eclipse.jdt.internal.compiler.ast.ConstructorDeclaration.traverse(ConstructorDeclaration.java:704)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.traverse(TypeDeclaration.java:1681)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.traverse(CompilationUnitDeclaration.java:822)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.traverse(CompilationUnitDeclaration.java:783)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.traverseUnitDeclaration(JDTBasedSpoonCompiler.java:480)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.lambda$buildModel$0(JDTBasedSpoonCompiler.java:437)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.forEachCompilationUnit(JDTBasedSpoonCompiler.java:464)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildModel(JDTBasedSpoonCompiler.java:435)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildUnitsAndModel(JDTBasedSpoonCompiler.java:372)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildSources(JDTBasedSpoonCompiler.java:335)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:116)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:99)
	at spoon.Launcher.buildModel(Launcher.java:766)
	at spoon.Main.main(Main.java:12)

Process finished with exit code 1
```

If instead `setIgnoreDuplicateDeclarations` is set to `false`, we get the following.

```
Exception in thread "main" spoon.compiler.ModelBuildingException: The type N3ParserTest is already defined
[... trace omitted ...]
```

The cause is duplication in the `compliance` submodule of RDF4J. If this submodule is removed, everything is spiffy. I'm looking into the crash and trying to recreate it with a minimal example.

**Comment by slarse** [comment]
I suspect that this is caused by the type declarations being duplicated but non-identical.

**Comment by slarse** [comment]
I've figured out why it happens and how to fix it, but not how to test it. What goes wrong here is when trying to create a qualified reference that involves a type access (e.g. `SomeTypeName.SOME_STATIC_VARIABLE`), and the type `SomeTypeName` is not available. Then, Spoon jumps through some hoops to search for it, and in particular trying to find the accessed type here:

https://github.com/INRIA/spoon/blob/fbac8078c77065a2b2c7ad24c62ae82053e76c95/src/main/java/spoon/support/compiler/jdt/ReferenceBuilder.java#L285

`units` are _all_ compilation unit declarations. When duplicate declarations are present, they will both be in there, and for one of them the type declaration will have a null binding. When searching for the type in the compilation units, `searchTypeBinding` simply iterates over all of them and accesses their bindings without checking if they are null:

https://github.com/INRIA/spoon/blob/f3d1677b725f88078812a4d61c5d8eb252a339da/src/main/java/spoon/support/compiler/jdt/JDTTreeBuilderQuery.java#L71-L92

If the "nulled" duplicated type declaration is encountered before a match is found, there's a crash.

The fix is trivial, just check if the binding is non-null before accessing it. Since this is dependent on iteration order, I haven't yet been able to reproduce it with a minimal example, and so testing it is a bit fiddly. I'd prefer doing it without mocking.
