### ISSUE TITLE
NullPointerException when calling getParent().getParent() on CtInvocation

### ISSUE THREAD

**Issue by shuchi03** [INRIA/spoon#3880]
I am calling getParent().getParent() on CtInvocation since I want to narrow down my searches and even though I am checking if getParent().getParent() is not null, I am still getting a nullpointerexception - 

```
Exception in thread "main" java.lang.NullPointerException
	at spoon.reflect.visitor.OperatorHelper.isSufixOperator(OperatorHelper.java:30)
	at spoon.reflect.visitor.OperatorHelper.isPrefixOperator(OperatorHelper.java:27)
	at spoon.reflect.visitor.DefaultJavaPrettyPrinter.visitCtUnaryOperator(DefaultJavaPrettyPrinter.java:1939)
	at spoon.support.reflect.code.CtUnaryOperatorImpl.accept(CtUnaryOperatorImpl.java:36)
	at spoon.reflect.visitor.DefaultJavaPrettyPrinter.scan(DefaultJavaPrettyPrinter.java:388)
	at spoon.reflect.visitor.DefaultJavaPrettyPrinter.printElement(DefaultJavaPrettyPrinter.java:274)
	at spoon.support.reflect.declaration.CtElementImpl.toString(CtElementImpl.java:300)
	at java.base/java.lang.String.valueOf(String.java:3352)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:166)
	at spoon.processes.classes.SessionProcessor.process(SessionProcessor.java:31)
	at spoon.processes.classes.SessionProcessor.process(SessionProcessor.java:1)
	at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:72)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:170)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:143)
	at spoon.reflect.visitor.CtScanner.visitCtInvocation(CtScanner.java:505)
	at spoon.support.reflect.code.CtInvocationImpl.accept(CtInvocationImpl.java:46)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:178)
	at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:68)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:170)
	at spoon.reflect.visitor.CtScanner.visitCtUnaryOperator(CtScanner.java:812)
	at spoon.support.reflect.code.CtUnaryOperatorImpl.accept(CtUnaryOperatorImpl.java:36)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:178)
	at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:68)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:170)
	at spoon.reflect.visitor.CtScanner.visitCtIf(CtScanner.java:482)
	at spoon.support.reflect.code.CtIfImpl.accept(CtIfImpl.java:36)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:178)
	at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:68)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:170)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:143)
	at spoon.reflect.visitor.CtScanner.visitCtBlock(CtScanner.java:300)
	at spoon.support.reflect.code.CtBlockImpl.accept(CtBlockImpl.java:58)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:178)
	at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:68)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:170)
	at spoon.reflect.visitor.CtScanner.visitCtForEach(CtScanner.java:474)
	at spoon.support.reflect.code.CtForEachImpl.accept(CtForEachImpl.java:30)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:178)
	at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:68)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:170)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:143)
	at spoon.reflect.visitor.CtScanner.visitCtBlock(CtScanner.java:300)
	at spoon.support.reflect.code.CtBlockImpl.accept(CtBlockImpl.java:58)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:178)
	at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:68)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:170)
	at spoon.reflect.visitor.CtScanner.visitCtIf(CtScanner.java:483)
	at spoon.support.reflect.code.CtIfImpl.accept(CtIfImpl.java:36)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:178)
	at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:68)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:170)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:143)
	at spoon.reflect.visitor.CtScanner.visitCtBlock(CtScanner.java:300)
	at spoon.support.reflect.code.CtBlockImpl.accept(CtBlockImpl.java:58)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:178)
	at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:68)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:170)
	at spoon.reflect.visitor.CtScanner.visitCtMethod(CtScanner.java:566)
	at spoon.support.reflect.declaration.CtMethodImpl.accept(CtMethodImpl.java:58)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:178)
	at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:68)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:170)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:143)
	at spoon.reflect.visitor.CtScanner.visitCtClass(CtScanner.java:336)
	at spoon.support.reflect.declaration.CtClassImpl.accept(CtClassImpl.java:58)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:178)
	at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:68)
	at spoon.support.QueueProcessingManager.process(QueueProcessingManager.java:118)
	at spoon.processes.classes.MainClass.main(MainClass.java:34)
```

Can someone please help me to resolve this issue?

**Comment by slarse** [comment]
Looks like the crash occurs during pretty-printing. Could you provide a test case that reproduces this issue?

**Comment by shuchi03** [comment]
I tried a lot to reproduce the issue, but I am not able to do that. I am working in a project, so when I produce the same code separately, it works fine. I found out that the issue is due to the following lines of the class in that project -

```
List<String> collect = set1.getElements().stream().map(Element::getName).collect(Collectors.toList());
if (!collect.contains(enum1.toString())) {
```

I am applying getParent().getParent() on enum1.toString(). The first getParent() returns collect.contains(enum1.toString()), but the second one returns error. If I remove the unary operator (!), then it works fine. 

I tried to reproduce this issue in an independent class, but I was not able to. I am also getting this warning when I launch spoon in my project - 

```
2021-04-14 17:40:39,327 [THREAD ID=main] WARN  spoon.reflect.factory.TypeFactory:566 - cannot create shadow class: quickfix.JdbcUtil
java.lang.TypeNotPresentException: Type org.logicalcobwebs.proxool.ProxoolDataSource not present
	at java.base/sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:117)
	at java.base/sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:125)
	at java.base/sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
	at java.base/sun.reflect.generics.visitor.Reifier.reifyTypeArguments(Reifier.java:68)
	at java.base/sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:138)
	at java.base/sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
	at java.base/sun.reflect.generics.repository.FieldRepository.computeGenericType(FieldRepository.java:90)
	at java.base/sun.reflect.generics.repository.FieldRepository.getGenericType(FieldRepository.java:82)
	at java.base/java.lang.reflect.Field.getGenericType(Field.java:268)
	at spoon.support.visitor.java.JavaReflectionVisitorImpl.visitField(JavaReflectionVisitorImpl.java:362)
	at spoon.support.visitor.java.JavaReflectionTreeBuilder.visitField(JavaReflectionTreeBuilder.java:304)
	at spoon.support.visitor.java.JavaReflectionVisitorImpl.visitClass(JavaReflectionVisitorImpl.java:92)
	at spoon.support.visitor.java.JavaReflectionTreeBuilder.visitClass(JavaReflectionTreeBuilder.java:152)
	at spoon.support.visitor.java.JavaReflectionTreeBuilder.scan(JavaReflectionTreeBuilder.java:109)
	at spoon.reflect.factory.TypeFactory.get(TypeFactory.java:564)
	at spoon.support.compiler.jdt.JDTImportBuilder.getOrLoadClass(JDTImportBuilder.java:150)
	at spoon.support.compiler.jdt.JDTImportBuilder.build(JDTImportBuilder.java:89)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.lambda$buildModel$1(JDTBasedSpoonCompiler.java:441)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.forEachCompilationUnit(JDTBasedSpoonCompiler.java:464)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildModel(JDTBasedSpoonCompiler.java:440)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildUnitsAndModel(JDTBasedSpoonCompiler.java:372)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildSources(JDTBasedSpoonCompiler.java:335)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:116)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:99)
	at spoon.Launcher.buildModel(Launcher.java:772)
	at spoon.processes.classes.MainClass.main(MainClass.java:17)
Caused by: java.lang.ClassNotFoundException: org.logicalcobwebs.proxool.ProxoolDataSource
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:416)
	at java.base/sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:114)
	... 25 more
```

Is the issue related to this warning? Because I don't get this warning when I launch spoon on an independent class.

**Comment by slarse** [comment]
I don't think that error is related. It's caused by Spoon being unable to build a shadow class through runtime reflection, and so instead it just creates a placeholder class (essentially an empty class with the correct name) instead. That crash may or may not be a bug, I'd like to look at that as well. But as the fatal crash seems to be cause by a unary operator not having its kind set, I can't see how the two would be related.

Is there any chance you can provide the source you are analyzing, and the Spoon code that does the analysis? Unfortunately, without seeing this happen for myself, I can't even guess at what the problem might be :(

**Comment by shuchi03** [comment]
I am sorry to say that I will not be able to send the whole source code because of company policy. But I can send the snippet of codes which I am analyzing. 

The spoon code which I have written is as follows - 

```
public class SessionProcessor extends AbstractProcessor<CtInvocation<?>> {

	@Override
	public boolean isToBeProcessed(CtInvocation<?> candidate) {
		for (CtTypeReference type : candidate.getReferencedTypes()) {
			if (type.isEnum() && candidate.getExecutable().getSimpleName().equalsIgnoreCase("toString")
					&& candidate.getExecutable().getDeclaringType().getSimpleName().equalsIgnoreCase("Enum")
					&& candidate.getParent().getParent().toString().contains("createQuery")) {
				return true;
			}
		}
		return false;
	}

	@Override
	public void process(CtInvocation<?> element) {
		System.out
		.println("Invocation element: " + element + " , " + element.getType() + " , " + element.getPosition().toString());

		System.out.println("----------------------------------------------------------------------------------------------------------");

		System.out.println(
				element.getExecutable().getDeclaringType().getSimpleName() + " , "
						+ element.getParent()
						+ " , "
						+ (element.getParent().getParent() != null ? element.getParent().getParent() : "null"));

		System.out.println("----------------------------------------------------------------------------------------------------------");

		element.getReferencedTypes().forEach(System.out::println);

		System.out.println("--------------------------------------------------END--------------------------------------------------------");

	}

}
```

I have written this to find lines which uses setString and Enum.toString while creating a query using a hibernate session. I wanted to modify this to use setParameter and without Enum.toString since that was causing other issues in the project.

The line which is reporting the issue that I have sent is -  **candidate.getParent().getParent()**

The code snippet that I am analyzing through this line is - 

```
public static List<Element> getMissingElements(DefinitionSet definitionSet) {
		List<Element> missingElements = new ArrayList<>();
		if (definitionSet.getName().contains("factor") && definitionSet.getElements().size() != 8) {
			List<Factor> factors = Arrays.asList(Factor.values());

			for (Factor factor : factors) {
				List<String> collect = 
                                             definitionSet.getElements().stream().map(Element::getFactorName).collect(Collectors.toList());
				if (!collect.contains(factor.toString())) {
					ElementmissingElement = new Element();
					missingElement.setFactorName(factor.toString());
					missingElements.add(missingElement);
					System.out.println("Missing " + factor.toString() + " in " + definitionSet.getName());
				}
			}

		}
		return missingElements;
	}
```

In this code snippet, the line - **if (!collect.contains(factor.toString())) {** is giving the error in which it shows that the parent of parent is a UnaryOperatorImpl (as you had mentioned). 

Also, the class Element extends **PersistentObject** class which has **@MappedSuperclass, @Broadcast()** annotations.

I hope this helps you to understand the issue better. Let me know if you need more information.

**Comment by slarse** [comment]
> I am sorry to say that I will not be able to send the whole source code because of company policy. But I can send the snippet of codes which I am analyzing.

I figured it was something like that, and I understand. I'll do my best to help based on the snippets and information you provided here, hopefully I can reproduce the problem! I'll get back to you once I've had a chance to look this over.

**Comment by slarse** [comment]
So, I've had some time to look this over now. The bad news is that I can't reproduce the crash. The good news is that I've an inkling as to what the problem might be. I think that it's here: https://github.com/INRIA/spoon/blob/e8a1596aa29d8d34f84087fb0dbce1d032b2259f/src/main/java/spoon/support/compiler/jdt/JDTTreeBuilderQuery.java#L244-L256

For some reason, this method is allowed to return null. I can't see any good reason for why we'd want to allow a failure to resolve an operator, so I'll see to amending these methods to throw instead.

Anyway, the only feasible way it could return null is if the argument to it does not match what we expect. Therefore, I have the following follow-up questions:

* What version of `spoon-core` are you using?
* What version of `org.eclipse.jdt.core` are you using?
* If you have an IDE that supports bytecode decompilation or dependency source download, could you put a breakpoint on the line that returns `null` in Spoon and check if that actually happens? If it does, we can be fairly confident that's the problem, and we can move on from there.

**Comment by slarse** [comment]
Follow-up to the previous comment: Most likely, the call to `getUnaryOperator` is from here: https://github.com/INRIA/spoon/blob/e8a1596aa29d8d34f84087fb0dbce1d032b2259f/src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java#L1759

If you're able to determine that `getUnaryOperator()` does indeed return `null`, it'd be great if you could check the values of `unaryExpression.bits`, `ASTNode.OperatorMASK` and `ASTNode.OperatorSHIFT`.

**Comment by slarse** [comment]
Looks like the shiftwidth and mask changed recently. https://github.com/eclipse/eclipse.jdt.core/commit/9295bf84c9d#diff-ef63a9e47d7749fd5654358b0f66887df86d8ed7821efed9a8d87981017d3188R167-R168

It might be related.

**Comment by shuchi03** [comment]
Thank you for looking into it. The answers to your questions - 

- What version of spoon-core are you using? -> ** latest one (9.0.0)**

- What version of org.eclipse.jdt.core are you using? -> **3.25.0.v20210223-0522**

- What JDK (distribution and version) are you using? **OpenJDK15U-jdk_x64_windows_hotspot_15.0.1_9**

I added break points in the lines that you mentioned. But while debugging, it did not go to those lines, infact a null value **(UnaryOperatorKind was null)** was received in **OperatorHelper** class in line 29 - 
```
	public static boolean isSufixOperator(UnaryOperatorKind o) {
		return o.name().startsWith("POST");
	}
```

**Comment by slarse** [comment]
> I added break points in the lines that you mentioned. But while debugging, it did not go to those lines

Bummer, I thought I was onto something.

> infact a null value (UnaryOperatorKind was null) was received in OperatorHelper class in line 29

Well, `null` is _passed_ to that method (i.e. `o == null`). We can see that from the original stack trace you supplied, here:

```
	at spoon.reflect.visitor.OperatorHelper.isSufixOperator(OperatorHelper.java:30)
	at spoon.reflect.visitor.OperatorHelper.isPrefixOperator(OperatorHelper.java:27)
	at spoon.reflect.visitor.DefaultJavaPrettyPrinter.visitCtUnaryOperator(DefaultJavaPrettyPrinter.java:1939)
	at spoon.support.reflect.code.CtUnaryOperatorImpl.accept(CtUnaryOperatorImpl.java:36)
	at spoon.reflect.visitor.DefaultJavaPrettyPrinter.scan(DefaultJavaPrettyPrinter.java:388)
```

I'm trying to figure out how it can be that `o` is `null`, and the only thing I could think of was the part I outlined before. But if that's not the source of this error, then I'll have to dive back in and see if I can find something else.

**Comment by shuchi03** [comment]
yes Sure. Let me know if you need any more information. Thank you very much.

**Comment by shuchi03** [comment]
Hi, 
I wanted to know if you had any luck recreating the issue and finding a bug. If you need any more information, kindly let me know. 
Thank you.

**Comment by slarse** [comment]
Hi @shuchi03,

Unfortunately, I've not been able to reproduce the problem, it just doesn't appear for me. While it would be easy to avoid the NPE, that doesn't solve the problem that the operator kind is missing for some reason.

There are some more things I can investigate, I've just been very busy with other responsibilities lately and haven't had the time to. It's unfortunately very time consuming to debug these things without having access to the code that's causing the problem.

**Comment by shuchi03** [comment]
Okay. No worries. You can investigate whenever you have less responsibilities. Meanwhile, I will check if some other way can be applied to check such statements. Thank you.

**Comment by slarse** [comment]
I've put this on my Monday TODO list. An unsolved mystery does not jive well with me, so I want to dive back in :)

I'll try to figure out what additional information you can provide me with to fix it. In the meantime, have a nice weekend!

**Comment by slarse** [comment]
> So while building model, the JDTTreeBuilder.java and DefaultCoreFactory.java lines (which you mentioned) were implemented.

You mean that they were executed? If that's the case, could you debug to line 1759 of `JDTTreeBuilder` and evaluate the expression `getUnaryOperator((unaryExpression.bits & ASTNode.OperatorMASK) >> ASTNode.OperatorSHIFT)`?

Also, what are the values of:

* `unaryExpression.bits`
* `ASTNode.OperatorMASK`
* `ASTNode.OperatorSHIFT`

**Comment by shuchi03** [comment]
Yes, Those lines are being implemented. I am very sorry I missed them in the previous posts. The values are - 

- `getUnaryOperator((unaryExpression.bits & ASTNode.OperatorMASK) >> ASTNode.OperatorSHIFT)` : **NOT**
- `unaryExpression.bits` : **-2147482939**
- `ASTNode.OperatorMASK` : **4032**
- `ASTNode.OperatorSHIFT` : **6**

**Comment by slarse** [comment]
All of those values check out. Unless that's some other operator being created (i.e. not the one causing the crash), I don't see any problem.

I'm sorry to say that debugging this without having a reproducible scenario is proving beyond my skills. If you can figure out when and how the operator's operator kind becomes `null` (i.e. where does the , then maybe I can do something.

**Comment by shuchi03** [comment]
Thank you for the reply. I will try to figure it out and will let you know if I find something.

**Comment by shuchi03** [comment]
So I was debugging and I found out that in the below code - 
```
	static UnaryOperatorKind getUnaryOperator(int operator) {
		switch (operator) {
		case OperatorIds.PLUS:
			return UnaryOperatorKind.POS;
		case OperatorIds.MINUS:
			return UnaryOperatorKind.NEG;
		case OperatorIds.NOT:
			return UnaryOperatorKind.NOT;
		case OperatorIds.TWIDDLE:
			return UnaryOperatorKind.COMPL;
		}
		return null;
	}
```
Its getting operator as 2 which is not in the switch cases. Thus, it is getting an null from this code - 

![image](https://user-images.githubusercontent.com/10210774/118507454-273ecf00-b726-11eb-8a83-c5042eb8e93f.png)

and it is setting the kind as null. But the strangest thing is when I try to see this line - 

`getUnaryOperator((unaryExpression.bits & ASTNode.OperatorMASK) >> ASTNode.OperatorSHIFT)`

then it is giving me a NOT. I am not sure why this odd behaviour.

Also I noticed that I get this error in the following code (in class DefaultCoreFactory) - 

```
	@Override
	public <T> CtUnaryOperator<T> createUnaryOperator() {
		CtUnaryOperator<T> e = new CtUnaryOperatorImpl<>();
		e.setFactory(getMainFactory());
		return e;
	}
```
![image](https://user-images.githubusercontent.com/10210774/118522688-42184000-b734-11eb-988e-891dd0c429c2.png)

So before I check below line, I get this error - 

`op.setKind(getUnaryOperator((unaryExpression.bits & ASTNode.OperatorMASK) >> ASTNode.OperatorSHIFT));`

![image](https://user-images.githubusercontent.com/10210774/118522978-94f1f780-b734-11eb-9a79-4ba35aef57bb.png)

And when I try to check this line without going inside the function, I get this result -

![image](https://user-images.githubusercontent.com/10210774/118523070-b0f59900-b734-11eb-9288-635f42145090.png)

I am not sure why it is giving such different results. Let me know if you need any more information.

**Comment by slarse** [comment]
@shuchi03 Nice detective work, now we have something to work with! Looks like my original suspicion in https://github.com/INRIA/spoon/issues/3880#issuecomment-821178859 was correct after all (I am redeemed!!).

First, of all, I don't think the `com.sun.jdi.InvocationException` is anything to worry about. It's most likely being thrown when the debugger is trying to evaluate the `toString()` method of the operator with a `null` operator kind (which throws an NPE).

> Its getting operator as 2 which is not in the switch cases. Thus, it is getting an null from this code -

[Operator ID 2 corresponds to `&&`](https://github.com/eclipse/eclipse.jdt.core/blob/519b64d75e8faf9ba579b362d36f4058f587cec9/org.eclipse.jdt.core/compiler/org/eclipse/jdt/internal/compiler/ast/OperatorIds.java#L19), so that's not right ...

> and it is setting the kind as null. But the strangest thing is when I try to see this line -
>
> getUnaryOperator((unaryExpression.bits & ASTNode.OperatorMASK) >> ASTNode.OperatorSHIFT)
>
> then it is giving me a NOT. I am not sure why this odd behaviour.

Unless something is seriously wrong with the JVM you're running, the only way this is possible is if you're invoking the two methods at different states. When you're at the `null` return value in the debugger inside `getUnaryOperator`, try backing up the the previous stack frame and invoke `getUnaryOperator` with those values, it should return `null`.

I'll have a closer look at the execution path and let you know what additional info I need. I'm starting to think that this is a bug in JDT rather than in Spoon.

**Comment by shuchi03** [comment]
Thank you for your time. I will also try to reproduce it. Thank you so much for helping me till this point. I will let you know if I have something to share.

**Comment by shuchi03** [comment]
I am really sorry to inform you that my senior colleague also tried to reproduce the issue, but he couldn't. So he modified the files which were causing the issue by removing the unary operator.

**Comment by slarse** [comment]
Ah, that's a super unsatisfying end to this saga, but it's totally understandable. It seems to me like this problem requires incredibly specific circumstances to appear. I'm sorry we couldn't resolve it.

Hopefully the problem resurfaces in a more easily reproducible scenario at some point.

As this problem wasn't actually solved, we'll leave this issue open for future reference. Thanks for your time and patience.
