### ISSUE TITLE
bug: Exception in thread "main" spoon.compiler.ModelBuildingException: The type package-info is already defined

### ISSUE THREAD

**Issue by djaekim** [INRIA/spoon#3948]
Exception in thread "main" spoon.compiler.ModelBuildingException: The type package-info is already defined

	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.reportProblem(JDTBasedSpoonCompiler.java:600)
	at spoon.support.compiler.jdt.TreeBuilderRequestor.acceptResult(TreeBuilderRequestor.java:29)
	at spoon.support.compiler.jdt.TreeBuilderCompiler.buildUnits(TreeBuilderCompiler.java:87)
	at spoon.support.compiler.jdt.JDTBatchCompiler.getUnits(JDTBatchCompiler.java:256)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildUnits(JDTBasedSpoonCompiler.java:417)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildUnitsAndModel(JDTBasedSpoonCompiler.java:369)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildSources(JDTBasedSpoonCompiler.java:335)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:116)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:99)
	at spoon.Launcher.buildModel(Launcher.java:772)
	at main.app.main(app.java:570)

Same issue when `launcher_test.getEnvironment().setIgnoreDuplicateDeclarations(true);`

Same issue when using `https://mvnrepository.com/artifact/fr.inria.gforge.spoon/spoon-core/9.0.0`

I got this error when running on Apache Hadoop.

**Comment by djaekim** [comment]
It was a silly error on my part. Please ignore this issue, thank you!

**Comment by slarse** [comment]
May I ask what the silly error was? Perhaps we can provide a better error message.

**Comment by djaekim** [comment]
> May I ask what the silly error was? Perhaps we can provide a better error message.
Thank you for the quick response!

I had 3 `buildModel` for instrumenting different folders. I only set  `setIgnoreDuplicateDeclarations`, on 2/3 modules.

**Comment by slarse** [comment]
> I had 3 buildModel for instrumenting different folders. I only set setIgnoreDuplicateDeclarations, on 2/3 modules.

Ah, I see. Were there actually duplicated `package-info.java` files? I.e. there were duplicated packages across those directories containing `package-info.java` files?

In any case, I think the error message isn't great, it would better read something like `the type <TYPE> is already defined in package <PACKAGE>`. `package-info` also isn't a type, so that makes it even more confusing.
