### ISSUE TITLE
Bug: Exception in thread "main" java.lang.RuntimeException: Invalid package name $packageName

### ISSUE THREAD

**Issue by djaekim** [INRIA/spoon#3952]
```
Exception in thread "main" java.lang.RuntimeException: Invalid package name $packageName
	at spoon.reflect.factory.PackageFactory.get(PackageFactory.java:159)
	at spoon.support.reflect.reference.CtPackageReferenceImpl.getDeclaration(CtPackageReferenceImpl.java:24)
	at spoon.support.reflect.declaration.CtCompilationUnitImpl.getDeclaredPackage(CtCompilationUnitImpl.java:230)
	at spoon.support.compiler.jdt.ReferenceBuilder.setPackageOrDeclaringType(ReferenceBuilder.java:1113)
	at spoon.support.compiler.jdt.ReferenceBuilder.getTypeReference(ReferenceBuilder.java:976)
	at spoon.support.compiler.jdt.ReferenceBuilder.getTypeReference(ReferenceBuilder.java:748)
	at spoon.support.compiler.jdt.ReferenceBuilder.getTypeReference(ReferenceBuilder.java:515)
	at spoon.support.compiler.jdt.ReferenceBuilder.buildTypeReference(ReferenceBuilder.java:136)
	at spoon.support.compiler.jdt.ReferenceBuilder.buildTypeReference(ReferenceBuilder.java:130)
	at spoon.support.compiler.jdt.JDTTreeBuilder.visit(JDTTreeBuilder.java:1625)
	at org.eclipse.jdt.internal.compiler.ast.SingleTypeReference.traverse(SingleTypeReference.java:137)
	at org.eclipse.jdt.internal.compiler.ast.Argument.traverse(Argument.java:274)
	at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.traverse(MethodDeclaration.java:401)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.traverse(TypeDeclaration.java:1689)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.traverse(CompilationUnitDeclaration.java:822)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.traverse(CompilationUnitDeclaration.java:783)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.traverseUnitDeclaration(JDTBasedSpoonCompiler.java:480)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.lambda$buildModel$0(JDTBasedSpoonCompiler.java:437)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.forEachCompilationUnit(JDTBasedSpoonCompiler.java:464)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildModel(JDTBasedSpoonCompiler.java:435)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildUnitsAndModel(JDTBasedSpoonCompiler.java:372)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildSources(JDTBasedSpoonCompiler.java:335)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:116)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:99)
	at spoon.Launcher.buildModel(Launcher.java:772)
	at main.app.main(app.java:625)
```

Occured for Apache Camel@aa9aa3575e1

**Comment by andrewbwogi** [comment]
Hi @djaekim, I can't reproduce this problem. Can you share how you set up the `Launcher` before you build the model?

**Comment by djaekim** [comment]
> Hi @djaekim, I can't reproduce this problem. Can you share how you set up the `Launcher` before you build the model?

Hi, it is shown below: 

```
		Launcher launcher_test = new Launcher();
		launcher_test.getEnvironment().setCommentEnabled(false);
		launcher_test.getEnvironment().setIgnoreDuplicateDeclarations(true);
		launcher_test.getEnvironment().setComplianceLevel(9);

		launcher_test.addInputResource(directoryOfProjectToAnalyze);
```

I was able to reproduce this now: `Exception in thread "main" java.lang.RuntimeException: Invalid package name $`

**Comment by andrewbwogi** [comment]
I get the same error. I'll check out why it happens.

**Comment by andrewbwogi** [comment]
The problem comes from a resource file with a .java extension but containing some non-Java syntax:

https://github.com/apache/camel/blob/eacc108d2702ffecc3316dfc4fb8fbac4b760d69/archetypes/camel-archetype-api-component/src/main/resources/archetype-resources/__artifactId__-component/src/main/java/__name__Component.java#L23

It is perhaps a template from which syntactically correct programs are generated. You can use a `CompilationUnitFilter` to exclude files from the model:
```java
launcher_test.getModelBuilder().addCompilationUnitFilter(
        new CompilationUnitFilter() {
            @Override
            public boolean exclude(final String path) {
                return path.contains("main/resources");
            }
        });
```

**Comment by slarse** [comment]
@andrewbwogi nice find!

@djaekim This highlights a general problem: adding the root of a source code repository as an input resource to Spoon is pretty error prone. It will try to parse _anything_ with a `.java` extension, regardless of where it finds it. Spoon will do everything it can to make sense of the situation, but sometimes the underlying JDT compiler just comes back with absolute nonsense, and so Spoon produces nonsense or outright crashes.

Here are some situations where that has caused headaches for me:

* It's a multi-module project with class duplication across modules
    - Especially common in test suites
    - Allowing duplicate declarations is not very stable, as type resolution becomes somewhat unpredictable
* There are resources with Java code that's syntactically invalid
    - For example the case with the template here
    - Can also be as test resources
* There are code examples somewhere with Java code that no one ever even tried to compile
    - There can also be example projects in a repo, where the projects are near-duplicates of each other, that may not even compile on their own

It's far less error prone to _just_ add the actual source code, and in my experience it's even more stable to only include production source code (i.e. exclude test source code).

If it's a Maven project, you can use the `MavenLauncher`.

**Comment by slarse** [comment]
To be clear, this isn't something that we can really fix.

We should however try to provide a better error message, pinpointing the location (at the very least the source file) of where the bad name occurs.

**Comment by djaekim** [comment]
> To be clear, this isn't something that we can really fix.
> 
> We should however try to provide a better error message, pinpointing the location (at the very least the source file) of where the bad name occurs. @andrewbwogi wdyt?

Thank you

> @andrewbwogi nice find!
> 
> @djaekim This highlights a general problem: adding the root of a source code repository as an input resource to Spoon is pretty error prone. It will try to parse _anything_ with a `.java` extension, regardless of where it finds it. Spoon will do everything it can to make sense of the situation, but sometimes the underlying JDT compiler just comes back with absolute nonsense, and so Spoon produces nonsense or outright crashes.
> 
> Here are some situations where that has caused headaches for me:
> 
> * It's a multi-module project with class duplication across modules
>   
>   * Especially common in test suites
>   * Allowing duplicate declarations is not very stable, as type resolution becomes somewhat unpredictable
> * There are resources with Java code that's syntactically invalid
>   
>   * For example the case with the template here
>   * Can also be as test resources
> * There are code examples somewhere with Java code that no one ever even tried to compile
>   
>   * There can also be example projects in a repo, where the projects are near-duplicates of each other, that may not even compile on their own
> 
> It's far less error prone to _just_ add the actual source code, and in my experience it's even more stable to only include production source code (i.e. exclude test source code).
> 
> If it's a Maven project, you can use the `MavenLauncher`.



> @andrewbwogi nice find!
> 
> @djaekim This highlights a general problem: adding the root of a source code repository as an input resource to Spoon is pretty error prone. It will try to parse _anything_ with a `.java` extension, regardless of where it finds it. Spoon will do everything it can to make sense of the situation, but sometimes the underlying JDT compiler just comes back with absolute nonsense, and so Spoon produces nonsense or outright crashes.
> 
> Here are some situations where that has caused headaches for me:
> 
> * It's a multi-module project with class duplication across modules
>   
>   * Especially common in test suites
>   * Allowing duplicate declarations is not very stable, as type resolution becomes somewhat unpredictable
> * There are resources with Java code that's syntactically invalid
>   
>   * For example the case with the template here
>   * Can also be as test resources
> * There are code examples somewhere with Java code that no one ever even tried to compile
>   
>   * There can also be example projects in a repo, where the projects are near-duplicates of each other, that may not even compile on their own
> 
> It's far less error prone to _just_ add the actual source code, and in my experience it's even more stable to only include production source code (i.e. exclude test source code).
> 
> If it's a Maven project, you can use the `MavenLauncher`.

Thank you the suggestions and time in investigating this issue. Yes, it's impossible to do anything in this case. I am trying to analyze the entire repository to recursively obtain all source code called within test code, so functionality such as "setIgnoreDuplicateDeclarations" is definitely helpful in my case

**Comment by slarse** [comment]
> I am trying to analyze the entire repository to recursively obtain all source code called within test code, so functionality such as "setIgnoreDuplicateDeclarations" is definitely helpful in my case.

One thing that comes to mind here is that we could add some form of "ignore errors mode", where Spoon will just drop any compilation units that it can't parse. That is to say, encounter a crash when parsing some file? Don't include anything from that compilation unit in the model.

@monperrus Any thoughts on adding such a liberal parsing mode to Spoon? It would sure help e.g. Sorald as well, as in experiments we've been affected by parsing crashes (completely unrelated to what we actually want to look at) as we just add the root of the repository.

**Comment by monperrus** [comment]
> Any thoughts on adding such a liberal parsing mode to Spoon?

To some extent, this was the core design idea when we introduced noclasspath. So it may be a bug of the noclasspath lenient try/catch block. 

Otherwise, if we stretch too much the concept of `noclasspath`, we can introduce and document a new mode `allow_invalid`.

**Comment by slarse** [comment]
I've had a look and it seems to me like all we need to do for allowing errors is to wrap these unit compilation traversals in try/catches (perhaps even just the first one is sufficient):

https://github.com/INRIA/spoon/blob/10959bf91f014961be75dc5ef301fe9b41f602e8/src/main/java/spoon/support/compiler/jdt/JDTBasedSpoonCompiler.java#L435-L442

We'll catch any exception, log a warning, and then keep on going.

Doing so can however build a severely wonky model containing partially built compilation units. Note that the idea is to ignore all kinds of errors, including bugs in Spoon (e.g. NPEs and other unhandled runtime exceptions that frequently occur in noclasspath mode). The idea would simply be to provide as robust a mode as possible, that in no way guarantees a reasonable model (but you'll get _something_).

I don't think that's a good default mode for Spoon, as we'll likely get far fewer bug reports from users as problems will be less evident. It seems to me like something that should be opt-in. Thoughts?

I think that would be stretching `noclasspath` beyond what's reasonable, both because the name does not indicate such liberal parsing, and because `noclasspath` is Spoon's default mode.

**Comment by monperrus** [comment]
> I think that would be stretching noclasspath beyond what's reasonable, both because the name does not indicate such liberal parsing, and because noclasspath is Spoon's default mode.

Agree.

**Comment by andrewbwogi** [comment]
There are two tasks then:

1. Print the file name of the failing compilation unit in an error message.
2. Create a new non-default mode `allow_invalid` that catches any exception and resumes modeling.

It would be good to have an exception specific to syntax problems so that other exceptions can be handled separately. I can investigte this further.

**Comment by slarse** [comment]
> 1. Print the file name of the failing compilation unit in an error message.

Yes, with the logger.

> 2. Create a new non-default mode `allow_invalid` that catches any exception and resumes modeling.

I've already done the implementation but I don't think we want to add this as a classpath-related mode. It's not a a mutually exclusive concept to either `classpath` or `noclasspath` modes, rather it's orthogonal to them, and so shoving it into those classpath-related modes doesn't really make sense. For example, you can have a fully resolved classpath and still have a parsing error in some random resource file.

Regardless, for users we'll just have a new flag to set in the environment (e.g. `Environment.setIgnoreParsingErrors(boolean)` or something like that). And probably, we'll want that to actually be a flag in the environment.

_However_, I think we need to consider what other flags should be implied by ignoring parsing errors. For example, it seems like we should also enable `ignoreDuplicateDeclarations`, because they _will_ be ignored if we ignore parsing errors, they'll just be ignored less granularly if `ignoreDuplicateDeclarations` is not active.

> It would be good to have an exception specific to syntax problems so that other exceptions can be handled separately. I can investigte this further.

There are only a few select places where we actually raise for syntax. The only one I can think of is when checking that identifiers comply with JLS specs. All other parsing-related failures are due to Spoon failing to adapt to some crazy stuff given by JDT, and crashing (very often with an NPE).

Feel free to look into it further, but just as far as I know, most stynax-related crashes are unhandled on our part.
