### ISSUE TITLE
Bug: Exception in thread "main" java.lang.IllegalStateException: Module should be known

### ISSUE THREAD

**Issue by djaekim** [INRIA/spoon#3954]
```
Exception in thread "main" java.lang.IllegalStateException: Module should be known
	at org.eclipse.jdt.internal.compiler.batch.CompilationUnit.module(CompilationUnit.java:138)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.module(CompilationUnitDeclaration.java:843)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.buildTypeBindings(LookupEnvironment.java:471)
	at org.eclipse.jdt.internal.compiler.Compiler.internalBeginToCompile(Compiler.java:855)
	at org.eclipse.jdt.internal.compiler.Compiler.beginToCompile(Compiler.java:394)
	at spoon.support.compiler.jdt.TreeBuilderCompiler.buildUnits(TreeBuilderCompiler.java:60)
	at spoon.support.compiler.jdt.JDTBatchCompiler.getUnits(JDTBatchCompiler.java:256)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildUnits(JDTBasedSpoonCompiler.java:417)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildUnitsAndModel(JDTBasedSpoonCompiler.java:369)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildSources(JDTBasedSpoonCompiler.java:335)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:116)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:99)
	at spoon.Launcher.buildModel(Launcher.java:772)
	at main.app.main(app.java:595)
```

This occurs for https://github.com/facebook/buck/commit/b3b2934165, when use `launcher.getEnvironment().setComplianceLevel(9); // Java 9`

**Comment by andrewbwogi** [comment]
The same exception occurs for me. Thanks for the bug report @djaekim!

**Comment by andrewbwogi** [comment]
The problem may be in JDT. I'm checking it out.

**Comment by andrewbwogi** [comment]
The problem is caused by [module-info.java](https://github.com/facebook/buck/blob/b3b2934165b0851279e29f6d6d4d2447bbe1de99/.idea/fileTemplates/internal/module-info.java). As in #3952, this file is a template that contains non-Java syntax. 

The exception occurs in JDT, so we can't process the file without duplicating JDT code.

One option is to make a syntax check with the JDT parser of all files before passing them to the JDT compiler. Here, the user can be warned if there are any syntax errors, and incorrect files can be filtered out, as discussed in #3952. This would imply an extra parsing step, but it would not be in the default mode. I can prepare a PR for this.
