### ISSUE TITLE
bug: ConcurrentModificationException in CtPackageImpl ModelSet

### ISSUE THREAD

**Issue by I-Al-Istannen** [INRIA/spoon#4071]
## Problem statement
I wrote a trimmed down Scanner that processes the model in parallel, but sadly it *sometimes* fails with a concurrent modification in the CtPackageImpl / ModelSet code.
```
15:13:57.239 [Thread-6] WARN spoon.Launcher - cannot create shadow class: [Ljavax.sound.midi.VoiceStatus;
java.util.ConcurrentModificationException: null
	at java.base/java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1480)
	at java.base/java.util.TreeMap$KeyIterator.next(TreeMap.java:1534)
	at spoon.support.util.ModelSet$Itr.next(ModelSet.java:146)
	at spoon.support.util.ModelSet$Itr.next(ModelSet.java:134)
	at spoon.support.reflect.declaration.CtPackageImpl.getType(CtPackageImpl.java:158)
	at spoon.support.visitor.java.JavaReflectionTreeBuilder.scan(JavaReflectionTreeBuilder.java:112)
	at spoon.reflect.factory.TypeFactory.get(TypeFactory.java:564)
	at spoon.support.reflect.reference.CtTypeReferenceImpl.getTypeDeclaration(CtTypeReferenceImpl.java:203)
	at de.ialistannen.javadocapi.spoon.JavadocElementExtractor.getPossiblyGenericType(JavadocElementExtractor.java:327)
	at de.ialistannen.javadocapi.spoon.JavadocElementExtractor.handleExecutable(JavadocElementExtractor.java:152)
	at de.ialistannen.javadocapi.spoon.JavadocElementExtractor.visitCtMethod(JavadocElementExtractor.java:113)
	at spoon.support.reflect.declaration.CtMethodImpl.accept(CtMethodImpl.java:58)
	at de.ialistannen.javadocapi.indexing.Indexer.lambda$main$0(Indexer.java:59)
	at de.ialistannen.javadocapi.spoon.filtering.ParallelProcessor.lambda$process$1(ParallelProcessor.java:48)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
```

## Cause
The CtPackageImpl iterates over the set:
```java
	@Override
	@SuppressWarnings("unchecked")
	public <T extends CtType<?>> T getType(String simpleName) {
		for (CtType<?> t : types) {
			if (t.getSimpleName().equals(simpleName)) {
				return (T) t;
			}
		}
		return null;
	}
```
This is problematic, as the `iterator` method delegates to the underlying set's iterator, which is a `Collections#synchronizedSet` instance. The Javadoc for that method states:
> It is imperative that the user manually synchronize on the returned collection when traversing it via [Iterator](https://docs.oracle.com/en/java/javase/16/docs/api/java.base/java/util/Iterator.html), [Spliterator](https://docs.oracle.com/en/java/javase/16/docs/api/java.base/java/util/Spliterator.html) or [Stream](https://docs.oracle.com/en/java/javase/16/docs/api/java.base/java/util/stream/Stream.html):
> 
> ``` java
> Set s = Collections.synchronizedSet(new HashSet());
> synchronized (s) {
>     Iterator i = s.iterator(); // Must be in the synchronized block
>     while (i.hasNext())
>         foo(i.next());
> }
> ```
> 
> Failure to follow this advice may result in non-deterministic behavior..

## Possible mitigations
The Java standard library doesn't offer a concurrent *ordered* set, so we can't simply transition to that. This sadly forces us to actually do what the javadoc states and synchronize on the returned set. Unfortunately, that would require us to leak a reference to the set to the caller and ensure they use it properly. I see the following easy options:

1. Leak the set in an `Object getLock()` getter and hope all clients use it (it is just CtPackage so we can adjust it easily). However, every caller must now take care to not misuse our set.
2. Make the iterator method violate the set contract and throw an exception upon invocation. Offer a callback based method like `<R> R acceptSynchronized(Function<Set<T>, R> action)` which can properly lock around the critical section.

## PRs
I have implemented 2) as I liked it a bit more and could PR it. The tests don't like it, so we'd probably end up with an iterator method that might throw a CME and an `acceptSynchronized` method that actually works.

I'd also be fine with implementing another option.

**Comment by andrewbwogi** [comment]
How about using `java.util.concurrent.ConcurrentSkipListSet` instead of `Collections.synchronizedSet`?

**Comment by I-Al-Istannen** [comment]
I looked at it but missed that it implements SortedSet. We could probably switch to it. I will have a go and see what spoon's test have to say about it.
