### ISSUE TITLE
bug: Qualified generic classes with incomplete classpath crash spoon

### ISSUE THREAD

**Issue by I-Al-Istannen** [INRIA/spoon#4077]
## Description
Explicitly qualified references for types Spoon doesn't know crashes it. If the reference uses an import, all is fine though.

## Crashing example
```java
import foo.A;
import foo.B;

class Test {
    public static void main(String args[]) {
        java.util.AbstractMap.SimpleEntry<A, B> entry = new java.util.AbstractMap.SimpleEntry<>(A.a, B.b);
    }
}
```

## Working example
```java
import foo.A;
import foo.B;
import java.util.AbstractMap.SimpleEntry;

class Test {
    public static void main(String args[]) {
        SimpleEntry<A, B> entry = new SimpleEntry<>(A.a, B.b);
    }
}
```

## Stacktrace
```
==== Building spoon model ====
Starting phase COMPILE
Phase COMPILE done! Discovered Classes: 1
Starting phase COMMENT
Phase COMMENT done! Discovered Classes: 1
Starting phase MODEL
Exception in thread "main" spoon.SpoonException: Unexpected QualifiedNameReference tokens java.util.AbstractMap.SimpleEntry<> for typeRef: java.util.AbstractMap.SimpleEntry
	at spoon.support.compiler.jdt.JDTTreeBuilderHelper.handleImplicit(JDTTreeBuilderHelper.java:557)
	at spoon.support.compiler.jdt.JDTTreeBuilderHelper.handleImplicit(JDTTreeBuilderHelper.java:488)
	at spoon.support.compiler.jdt.ReferenceBuilder.getTypeReference(ReferenceBuilder.java:518)
	at spoon.support.compiler.jdt.ReferenceBuilder.getExecutableReference(ReferenceBuilder.java:451)
	at spoon.support.compiler.jdt.JDTTreeBuilder.visit(JDTTreeBuilder.java:874)
	at org.eclipse.jdt.internal.compiler.ast.AllocationExpression.traverse(AllocationExpression.java:716)
	at org.eclipse.jdt.internal.compiler.ast.LocalDeclaration.traverse(LocalDeclaration.java:484)
	at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.traverse(MethodDeclaration.java:411)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.traverse(TypeDeclaration.java:1708)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.traverse(CompilationUnitDeclaration.java:827)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.traverse(CompilationUnitDeclaration.java:788)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.traverseUnitDeclaration(JDTBasedSpoonCompiler.java:480)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.lambda$buildModel$0(JDTBasedSpoonCompiler.java:437)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.forEachCompilationUnit(JDTBasedSpoonCompiler.java:464)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildModel(JDTBasedSpoonCompiler.java:435)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildUnitsAndModel(JDTBasedSpoonCompiler.java:372)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildSources(JDTBasedSpoonCompiler.java:335)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:116)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:99)
	at spoon.Launcher.buildModel(Launcher.java:772)
	at de.ialistannen.javadocapi.indexing.Indexer.main(Indexer.java:62)

Process finished with exit code 1
```

**Comment by andrewbwogi** [comment]
Thanks @I-Al-Istannen , I get the same error. I think a compiling Java program is a good candidate for minimum Spoon input.

**Comment by I-Al-Istannen** [comment]
I am not quite sure what you mean by your second sentence @andrewbwogi. The programs in the off post crash spoon with the given error. It is necessary that Spoon doesn't know what `A` and `B` refer to (hence the incomplete classpath). So if you create three files:

```java
// foo/A.java:
package foo;

public class A {
    public static A a;
}

// foo/B.java:
package foo;

public class B {
    public static B b;
}

// Test.java:
import foo.A;
import foo.B;

class Test {
    public static void main(String args[]) {
        java.util.AbstractMap.SimpleEntry<A, B> entry = new java.util.AbstractMap.SimpleEntry<>(A.a, B.b);
    }
}
```

And only add the `Test.java` as a spoon resource, spoon will crash - it will survive if it only receives an imported SimpleEntry, as shown in the offpost. 

The program will compile with A and B present and won't crash spoon if you supply all three as resources as spoon can resolve all types then.

You can probably minimize it further by using a `SimpleEntry<A, A>` but I haven't tested that.

**Comment by slarse** [comment]
I'm not sure if it's the entire cause, but Spoon creates a package reference out of `java.util.AbstractMap`, even though that's a type that's available on the classpath. Will have a closer look when I get the chance to.

**Comment by wang422403** [comment]
Hi, chiming in from a production use case — this bug is still reproducible on **spoon-core 11.4.0** (latest release as of now).
We run Spoon in **no-classpath** mode (`Environment.setNoClasspath(true)`) to build call graphs for large multi-module Java services. When analyzing real business code (e.g. stream/lambda patterns), we hit the exact same crash:
spoon.SpoonException: Unexpected QualifiedNameReference tokens java.util.AbstractMap.SimpleEntry<> for typeRef: java.util.AbstractMap.SimpleEntry at spoon.support.compiler.jdt.JDTTreeBuilderHelper.handleImplicit(JDTTreeBuilderHelper.java:652) ... at spoon.Launcher.buildModel(Launcher.java:781)

Typical triggering pattern in our codebase:
```java
// fully-qualified inner class + diamond operator, generic args not on classpath
new java.util.AbstractMap.SimpleEntry<>(key, value)
As noted in the original report, switching to import java.util.AbstractMap.SimpleEntry + short name works, but we cannot ask every team to rewrite their code for the analyzer.

Impact: a single file with this pattern causes buildModel() to fail for the entire project, blocking static call-graph indexing.

Current workaround: we probe files individually and skip unparseable ones, but that means methods in those files are missing from the call graph.

Would a PR that strips <> from QualifiedNameReference tokens in handleImplicit (when they don't match typeRef.getSimpleName()) be acceptable? Happy to contribute if there's guidance on the preferred fix direction.

Thanks for maintaining Spoon 🙏
