### ISSUE TITLE
StackOverflowError in JDTTreeBuilder.ReferenceBuilder.getTypeReference()

### ISSUE THREAD

**Issue by Andy1605** [INRIA/spoon#408]
Hi there,

I was recently experiencing a strange behavior of the ReferenceBuilder in JDTTreeBuilder when i tried to convert this class:

```java
public class EnumValue  {
    
    public EnumValue() 
    {
    }
    
    //...

    public <T extends Enum<T>> T asEnum() //StackOverflow when referenced
    {        
        return null;
    }

    public Object unwrap()
    {
      return asEnum();
    }
}
```
As soon as i have a reference to the method `public <T extends Enum<T>> T asEnum()` as seen in the unwrap() method, i get a StackOverflow error in getTypeReference() due to a infinite recursion.
I am using the stable Version 4.4.0 of spoon.

Here is the stack trace (which wont be very useful i suppose):
Exception in thread "main" java.lang.StackOverflowError
	at spoon.reflect.factory.FactoryImpl.dedup(FactoryImpl.java:310)
	at spoon.support.reflect.reference.CtReferenceImpl.setSimpleName(CtReferenceImpl.java:75)
	at spoon.support.compiler.jdt.JDTTreeBuilder$ReferenceBuilder.getTypeReference(JDTTreeBuilder.java:486)
	at spoon.support.compiler.jdt.JDTTreeBuilder$ReferenceBuilder.getTypeReference(JDTTreeBuilder.java:562)
	at spoon.support.compiler.jdt.JDTTreeBuilder$ReferenceBuilder.getTypeReference(JDTTreeBuilder.java:501)
	at spoon.support.compiler.jdt.JDTTreeBuilder$ReferenceBuilder.getTypeReference(JDTTreeBuilder.java:562)
	at spoon.support.compiler.jdt.JDTTreeBuilder$ReferenceBuilder.getTypeReference(JDTTreeBuilder.java:501)
	at spoon.support.compiler.jdt.JDTTreeBuilder$ReferenceBuilder.getTypeReference(JDTTreeBuilder.java:562)
	at spoon.support.compiler.jdt.JDTTreeBuilder$ReferenceBuilder.getTypeReference(JDTTreeBuilder.java:501)
	at spoon.support.compiler.jdt.JDTTreeBuilder$ReferenceBuilder.getTypeReference(JDTTreeBuilder.java:562)
	at spoon.support.compiler.jdt.JDTTreeBuilder$ReferenceBuilder.getTypeReference(JDTTreeBuilder.java:501)
	at spoon.support.compiler.jdt.JDTTreeBuilder$ReferenceBuilder.getTypeReference(JDTTreeBuilder.java:562)
	at spoon.support.compiler.jdt.JDTTreeBuilder$ReferenceBuilder.getTypeReference(JDTTreeBuilder.java:501)
	at spoon.support.compiler.jdt.JDTTreeBuilder$ReferenceBuilder.getTypeReference(JDTTreeBuilder.java:562)
	at spoon.support.compiler.jdt.JDTTreeBuilder$ReferenceBuilder.getTypeReference(JDTTreeBuilder.java:501)
	at spoon.support.compiler.jdt.JDTTreeBuilder$ReferenceBuilder.getTypeReference(JDTTreeBuilder.java:562)
....

Sincerely,
Andreas

**Comment by GerardPaligot** [comment]
Hi @Andy1605,

Thanks for your report. It is weird because we have already encountered this problem and we have a test case about it [here](https://github.com/INRIA/spoon/blob/master/src/test/java/spoon/test/reference/TypeReferenceTest.java#L199).

I'll check your issue soon and I'll come back to you to give you a feedback!

**Comment by GerardPaligot** [comment]
The bug is confirmed and the PR is done [here](https://github.com/INRIA/spoon/pull/410).

**Comment by GerardPaligot** [comment]
The version 4.4.1 is on the way for Maven Central and contains this bug fix.
