### ISSUE TITLE
MavenLauncher ModelBuildingException 

### ISSUE THREAD

**Issue by PeterFan89** [INRIA/spoon#4245]
The exception is :
spoon.compiler.ModelBuildingException: BaseMapper cannot be resolved to a type at /tmp/git-2988291472111792531/phx-ugc-base-app/src/main/java/com/sankuai/ia/ugc/base/mapper/CommentProductMapper.java:7
        at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.report(JDTBasedSpoonCompiler.java:649) ~[spoon-core-9.2.0-beta-3.jar!/:?]
        at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.reportProblems(JDTBasedSpoonCompiler.java:631) ~[spoon-core-9.2.0-beta-3.jar!/:?]
        at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:118) ~[spoon-core-9.2.0-beta-3.jar!/:?]
        at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:99) ~[spoon-core-9.2.0-beta-3.jar!/:?]
        at spoon.Launcher.buildModel(Launcher.java:781) ~[spoon-core-9.2.0-beta-3.jar!/:?]

"BaseMapper" is the class been extends

**Comment by slarse** [comment]
@PeterFan89 I'm glad you found the problem, we're happy to help :)
