### ISSUE TITLE
spoon-maven-plugin doesn't support `--add-opens` (problem with Java 16+)

### ISSUE THREAD

**Issue by vmassol** [INRIA/spoon#4251]
```
[INFO] --- spoon-maven-plugin:3.5:check (spoon-main) @ xwiki-platform-distribution-ui-base ---
java.lang.reflect.InaccessibleObjectException: Unable to make protected void java.net.URLClassLoader.addURL(java.net.URL) accessible: module java.base does not "opens java.net" to unnamed module @6b3c15eb
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
	at fr.inria.gforge.spoon.util.ClasspathHacker.addURL(ClasspathHacker.java:19)
	at fr.inria.gforge.spoon.SpoonMojoGenerate.addArtifactsInClasspathOfTargetClassLoader(SpoonMojoGenerate.java:265)
	at fr.inria.gforge.spoon.SpoonMojoGenerate.initMojo(SpoonMojoGenerate.java:199)
	at fr.inria.gforge.spoon.SpoonMojoGenerate.execute(SpoonMojoGenerate.java:222)
	at com.gradle.maven.a.a.e.c.a(SourceFile:26)
	at com.gradle.maven.a.a.e.n.a(SourceFile:23)
	at com.gradle.maven.a.a.e.h.a(SourceFile:28)
	at com.gradle.maven.a.a.e.m.a(SourceFile:27)
	at com.gradle.maven.a.a.e.a.c(SourceFile:114)
	at com.gradle.maven.a.a.e.a.a(SourceFile:60)
	at com.gradle.maven.a.a.e.e.a(SourceFile:27)
	at com.gradle.maven.a.a.e.l.a(SourceFile:17)
	at com.gradle.maven.a.a.e.d.a(SourceFile:42)
	at com.gradle.maven.a.a.e.b.a(SourceFile:26)
	at com.gradle.maven.a.a.e.f$1.a(SourceFile:34)
	at org.a.c.e.r$1.a(SourceFile:29)
	at org.a.c.e.r$1.a(SourceFile:26)
	at org.a.c.e.r$2.a(SourceFile:75)
	at org.a.c.e.r$2.b(SourceFile:68)
	at org.a.c.e.r.a(SourceFile:153)
	at org.a.c.e.r.a(SourceFile:68)
	at org.a.c.e.r.a(SourceFile:56)
	at com.gradle.maven.a.a.e.f.a(SourceFile:30)
	at com.gradle.maven.a.a.e.k.a(SourceFile:61)
	at com.gradle.maven.a.a.i.b.a(SourceFile:52)
	at jdk.proxy12/jdk.proxy12.$Proxy46.execute(Unknown Source)
	at com.gradle.maven.scan.extension.internal.e.a.executeMojo(SourceFile:135)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:972)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:293)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:196)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
```

Note: On Java 17 you cannot ignore anymore with `illegal-access=permit`. However you can make it work probably with some `--add-opens`. However ideally it needs to be fixed.

As a workaround the following should work: `--add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.util.concurrent=ALL-UNNAMED`

**Comment by vmassol** [comment]
Note that passing the `add-opens` to Maven doesn't make the Spoon plugin work. Could it be forking a JVM?

**Comment by vmassol** [comment]
Just noticed that spoon maven plugin v3.5 doesn't work on Java 16, even with Spoon 10.0.0.

**Comment by monperrus** [comment]
thanks for the update

cc/ @algomaster99 we may have to look at this one soon

**Comment by jtaub** [comment]
Still getting this error with plugin version 3.5 and Spoon 10.4.0-beta-4, and I haven't had any luck in getting `--add-opens` to work. Anyone able to share a minimal working example of using `--add-opens` with the plugin?

**Comment by monperrus** [comment]
cc/ @yogyagamage

**Comment by yogyagamage** [comment]
This should be fixed with the release of spoon-maven-plugin version 3.7.

**Comment by vmassol** [comment]
Thanks! Just tested with java 17 on XWiki and it doesn't fail anymore. Good job!
