### ISSUE TITLE
[Bug] Failure on comments inside enum values

### ISSUE THREAD

**Issue by plcarmel** [INRIA/spoon#4332]
When there are comments inside enum values, Spoon fails to perform a transformation on the type.

```java
package org.example;

enum Example {

    ENGLISH( /* boom */
            "Hello",
            "World"
    ),
    FRENCH(
            "Bonjour",
            "l'univers"
    );

    String hello;
    String world;

    public Example(
            String hello,
            String world
    ) {
        this.hello = hello;
        this.world = world;
    }
}
```

```
Exception in thread "main" spoon.SpoonException: Cannot compare this: [46, 115] with other: ["55", "185"]
        at spoon.support.sniper.internal.ElementSourceFragment.compare(ElementSourceFragment.java:371)
        at spoon.support.sniper.internal.ElementSourceFragment.add(ElementSourceFragment.java:285)
        at spoon.support.sniper.internal.ElementSourceFragment.addChild(ElementSourceFragment.java:317)
        at spoon.support.sniper.internal.ElementSourceFragment.addChild(ElementSourceFragment.java:243)
        at spoon.support.sniper.internal.ElementSourceFragment$1.enter(ElementSourceFragment.java:200)
        at spoon.reflect.visitor.CtScanner.visitCtEnumValue(CtScanner.java:442)
        at spoon.support.reflect.declaration.CtEnumValueImpl.accept(CtEnumValueImpl.java:18)
        at spoon.reflect.visitor.EarlyTerminatingScanner.doScan(EarlyTerminatingScanner.java:145)
        at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:121)
        at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:184)
        at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:106)
        at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:83)
        at spoon.reflect.visitor.CtScanner.visitCtEnum(CtScanner.java:415)
        at spoon.support.reflect.declaration.CtEnumImpl.accept(CtEnumImpl.java:45)
        at spoon.reflect.visitor.EarlyTerminatingScanner.doScan(EarlyTerminatingScanner.java:145)
        at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:121)
        at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:184)
        at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:106)
        at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:83)
        at spoon.reflect.visitor.EarlyTerminatingScanner.visitCtCompilationUnit(EarlyTerminatingScanner.java:160)
        at spoon.support.reflect.declaration.CtCompilationUnitImpl.accept(CtCompilationUnitImpl.java:407)
        at spoon.reflect.visitor.EarlyTerminatingScanner.doScan(EarlyTerminatingScanner.java:145)
        at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:121)
        at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:184)
        at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:106)
        at spoon.support.sniper.internal.ElementSourceFragment.createSourceFragmentsFrom(ElementSourceFragment.java:228)
        at spoon.support.reflect.declaration.CtCompilationUnitImpl.getOriginalSourceFragment(CtCompilationUnitImpl.java:359)
        at spoon.support.modelobs.SourceFragmentCreator.onChange(SourceFragmentCreator.java:32)
        at spoon.support.modelobs.ChangeCollector$ChangeListener.onObjectUpdate(ChangeCollector.java:175)
        at spoon.support.reflect.declaration.CtNamedElementImpl.setSimpleName(CtNamedElementImpl.java:45)
        at org.example.MainKt.main(Main.kt:15)
        at org.example.MainKt.main(Main.kt)
```

Code to reproduce the issue is available on GitHub:
https://github.com/plcarmel/spoon-enum-bug

```
java -version
java version "11.0.13" 2021-10-19 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.13+10-LTS-370)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.13+10-LTS-370, mixed mode)
```

**Comment by slarse** [comment]
Hi, thanks for the bug report.

The transformation itself isn't the problem here, the crash occurs in the sniper printer. I edited the title to make it more apparent.

**Comment by kl0u** [comment]
Are there any plans to fix this issue soon?

**Comment by slarse** [comment]
@kl0u It seems like no one has taken it upon themselves to do this yet, so the sincere answer to your question would be no. If you would like to give it a shot, go ahead :)

**Comment by kl0u** [comment]
Thanks @slarse ! I cannot commit that I will work on that but if I have something I will create a PR.

**Comment by OlivierCavadenti** [comment]
Hi,
@kl0u did you find how to fix ?
By the way I made some debugging and it's seems that when you add comment, the source code of CtFieldImpl object contains the comment as we can see here (and so change start and end values):

![image](https://user-images.githubusercontent.com/10152806/158053520-41db05b5-4241-4f58-86df-eae11e5c3b88.png)

Without the comment, in yellow: 

![image](https://user-images.githubusercontent.com/10152806/158053572-99baf069-484c-4615-9549-9fdaaabb3bb0.png)

I am new in the project so I need some extra time to find a fix.

**Comment by kl0u** [comment]
@OlivierCavadenti I have not worked on it, so feel free to take over. The only thing I found some time ago was that it seems that in the `ContextBuilder.enter()`,  the `ASTNode` seems to have correct sourceStart and sourceEnd but the `modifiersSourceStart`, `declarationSourceStart` and `declarationSourceEnd` are wrong when there is a comment. So it may be an eclipse issue. But I am not sure yet.

**Comment by kl0u** [comment]
BTW for the above, I am wondering if the solution is simply one more if-clause that fixes the problem for this case by resetting the offsets, or there is a more principled solution. The problem with this if-clause solution is that it seems very targeted to this specific case. Any suggestions @slarse or anyone who knows the codebase better?
