### ISSUE TITLE
[Bug] Bug descriptionspoon.SpoonException: Maven invocation failed to build a classpath.

### ISSUE THREAD

**Issue by soneyahossain** [INRIA/spoon#4658]
**Describe the bug**
when running the test that uses MavenLauncher it throws this error. This is an example 
https://github.com/SpoonLabs/spoon-examples/blob/master/src/main/java/fr/inria/gforge/spoon/analysis/MavenLauncherExampleTest.java

**To Reproduce**

Input:
```java
/*Code being processed by spoon and leading to the bug.*/
```

Processing with Spoon:
```java
/*Code calling spoon on the input and triggering the bug.*/
```

Output:
```java

spoon.SpoonException: Maven invocation failed to build a classpath.

	at spoon.support.compiler.SpoonPom.generateClassPathFile(SpoonPom.java:367)
	at spoon.support.compiler.SpoonPom.buildClassPath(SpoonPom.java:449)
	at spoon.MavenLauncher.init(MavenLauncher.java:139)
	at spoon.MavenLauncher.<init>(MavenLauncher.java:94)
	at spoon.MavenLauncher.<init>(MavenLauncher.java:60)
	at fr.inria.gforge.spoon.transformation.BigTransfoScenarioTest.main(BigTransfoScenarioTest.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)


Process finished with exit code 255



```

Note that you can also open a pull request reproducing the issue and reference that, instead of writing additional information here.

**Operating system, JDK and Spoon version used**

* OS: ubuntu
* JDK: 1.8
* Spoon version: 9.1.0

**Comment by slarse** [comment]
I'm sorry to say that we do not have the capacity to support JDK 1.8 anymore, all the work we do now is for JDK 11+. You should try running with an up-to-date version of Spoon and see if that works out. We fixed a problem with the MavenLauncher not too long ago, see #4298. That might be the solution you need.

I'm going to close this as it's not actionable for us, we don't support JDK 1.8. Feel free to reopen if you encounter the same problem with JDK 11+.
