### ISSUE TITLE
[ERROR] ERROR MutationSupporter - Pb(324) The type javax.annotation.Nullable cannot be resolved.

### ISSUE THREAD

**Issue by juliamanfrindias** [INRIA/spoon#4735]
i ran astor command but got this error: ERROR MutationSupporter - Pb(324) The type javax.annotation.Nullable cannot be resolved.

This is the astor command:
```java
java  -cp /home/julia/mestrado/teste/astor_bkp/target/astor-2.0.0-jar-with-dependencies.jar fr.inria.main.evolution.AstorMain -mode jKali -location /home/julia/mestrado/teste/Bugs/Closure-10 -maxtime 120 -mode statement -package  org.apache.commons -jvm4testexecution /usr/lib/jvm/java-8-openjdk-amd64/bin/ -srcjavafolder /src/java/ -srctestfolder /src/test/ -binjavafolder /target/classes -bintestfolder /target/test-classes -flthreshold 0.5 -stopfirst true -faultlocalization CoCoSpoon -javacompliancelevel 8 -allpoints true -dependencies /home/julia/mestrado/teste/astor_bkp/astor/examples/libs/junit-4.4.jar
```

This is what I got in my output:
```java
$ java  -cp /home/julia/mestrado/teste/astor_bkp/target/astor-2.0.0-jar-with-dependencies.jar fr.inria.main.evolution.AstorMain -mode jKali -location /home/julia/mestrado/teste/Bugs/Closure-10 -maxtime 120 -mode statement -package  org.apache.commons -jvm4testexecution /usr/lib/jvm/java-8-openjdk-amd64/bin/ -srcjavafolder /src/java/ -srctestfolder /src/test/ -binjavafolder /target/classes -bintestfolder /target/test-classes -flthreshold 0.5 -stopfirst true -faultlocalization CoCoSpoon -javacompliancelevel 8 -allpoints true -dependencies /home/julia/mestrado/teste/astor_bkp/astor/examples/libs/junit-4.4.jar
[0] INFO ProjectConfiguration - Version of the JVM used: 1.8.0_312
[1] INFO main - Java version of the JDK used to run tests: 1.8.0_312
[1] INFO main - The compliance of the JVM is:  8
[4] INFO main - command line arguments: [-mode  jKali  -location  /home/julia/mestrado/teste/Bugs/Closure-10  -maxtime  120  -mode  statement  -package  org.apache.commons  -jvm4testexecution  /usr/lib/jvm/java-8-openjdk-amd64/bin/  -srcjavafolder  /src/java/  -srctestfolder  /src/test/  -binjavafolder  /target/classes  -bintestfolder  /target/test-classes  -flthreshold  0.5  -stopfirst  true  -faultlocalization  CoCoSpoon  -javacompliancelevel  8  -allpoints  true  -dependencies  /home/julia/mestrado/teste/astor_bkp/astor/examples/libs/junit-4.4.jar]
[6] INFO AstorMain - Running Astor on a JDK at /usr/lib/jvm/java-8-openjdk-amd64/jre
[13] INFO main - Source folders: [/home/julia/mestrado/teste/Bugs/Closure-10/src]
[14] INFO main - Source Test folders: [/home/julia/mestrado/teste/Bugs/Closure-10/test]
[454] INFO AstorCoreEngine - ---- Creating spoon model
[485] INFO MutationSupporter - Creating model,  Code location from working folder: /home/julia/mestrado/teste/Bugs/Closure-10/src
[485] INFO MutationSupporter - building model: /home/julia/mestrado/teste/Bugs/Closure-10/src, compliance level: 8
[537] INFO MutationSupporter - Classpath (Dependencies) for building SpoonModel: null
[2128] ERROR MutationSupporter - Problem compiling the model with compliance level 8
[2128] ERROR MutationSupporter - Pb(324) The type javax.annotation.Nullable cannot be resolved. It is indirectly referenced from required .class files
org.eclipse.jdt.internal.compiler.problem.AbortCompilation: Pb(324) The type javax.annotation.Nullable cannot be resolved. It is indirectly referenced from required .class files
	at org.eclipse.jdt.internal.compiler.problem.ProblemHandler.handle(ProblemHandler.java:162)
	at org.eclipse.jdt.internal.compiler.problem.ProblemHandler.handle(ProblemHandler.java:229)
	at org.eclipse.jdt.internal.compiler.problem.ProblemReporter.handle(ProblemReporter.java:2646)
	at org.eclipse.jdt.internal.compiler.problem.ProblemReporter.isClassPathCorrect(ProblemReporter.java:5117)
	at org.eclipse.jdt.internal.compiler.lookup.UnresolvedReferenceBinding.resolve(UnresolvedReferenceBinding.java:123)
	at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.resolveType(BinaryTypeBinding.java:248)
	at org.eclipse.jdt.internal.compiler.lookup.PackageBinding.getTypeOrPackage(PackageBinding.java:252)
	at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.findImport(CompilationUnitScope.java:551)
	at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.findSingleImport(CompilationUnitScope.java:623)
	at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.resolveSingleImport(CompilationUnitScope.java:846)
	at org.eclipse.jdt.internal.compiler.lookup.Scope.getTypeOrPackage(Scope.java:3452)
	at org.eclipse.jdt.internal.compiler.lookup.Scope.getType(Scope.java:3177)
	at org.eclipse.jdt.internal.compiler.ast.SingleTypeReference.getTypeBinding(SingleTypeReference.java:57)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.internalResolveType(TypeReference.java:536)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.resolveType(TypeReference.java:639)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.resolveType(TypeReference.java:635)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.resolveType(TypeReference.java:631)
	at org.eclipse.jdt.internal.compiler.ast.Annotation.handleNonNullByDefault(Annotation.java:1121)
	at org.eclipse.jdt.internal.compiler.ast.ASTNode.handleNonNullByDefault(ASTNode.java:1058)
	at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.resolveTypesWithSuspendedTempErrorHandlingPolicy(SourceTypeBinding.java:2746)
	at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.resolveTypesFor(SourceTypeBinding.java:2649)
	at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.getExactConstructor(SourceTypeBinding.java:1669)
	at org.eclipse.jdt.internal.compiler.lookup.Scope.getConstructor0(Scope.java:2465)
	at org.eclipse.jdt.internal.compiler.lookup.Scope.getConstructor(Scope.java:2446)
	at org.eclipse.jdt.internal.compiler.ast.Statement.findConstructorBinding(Statement.java:588)
	at org.eclipse.jdt.internal.compiler.ast.AllocationExpression.resolveType(AllocationExpression.java:491)
	at org.eclipse.jdt.internal.compiler.ast.LocalDeclaration.resolve(LocalDeclaration.java:390)
	at org.eclipse.jdt.internal.compiler.ast.LocalDeclaration.resolve(LocalDeclaration.java:259)
	at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.resolveStatements(AbstractMethodDeclaration.java:661)
	at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.resolveStatements(MethodDeclaration.java:362)
	at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.resolve(AbstractMethodDeclaration.java:570)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1512)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1612)
	at org.eclipse.jdt.internal.compiler.ast.QualifiedAllocationExpression.getAnonymousConstructorBinding(QualifiedAllocationExpression.java:666)
	at org.eclipse.jdt.internal.compiler.ast.QualifiedAllocationExpression.resolveTypeForQualifiedAllocationExpression(QualifiedAllocationExpression.java:557)
	at org.eclipse.jdt.internal.compiler.ast.QualifiedAllocationExpression.resolveType(QualifiedAllocationExpression.java:304)
	at org.eclipse.jdt.internal.compiler.ast.FieldDeclaration.resolve(FieldDeclaration.java:294)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1448)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1637)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.resolve(CompilationUnitDeclaration.java:667)
	at spoon.support.compiler.jdt.TreeBuilderCompiler.buildUnits(TreeBuilderCompiler.java:105)
	at spoon.support.compiler.jdt.JDTBatchCompiler.getUnits(JDTBatchCompiler.java:283)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildUnits(JDTBasedSpoonCompiler.java:417)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildUnitsAndModel(JDTBasedSpoonCompiler.java:369)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildSources(JDTBasedSpoonCompiler.java:335)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:116)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:99)
	at fr.inria.astor.core.manipulation.MutationSupporter.buildModel(MutationSupporter.java:85)
	at fr.inria.astor.core.manipulation.MutationSupporter.buildSpoonModel(MutationSupporter.java:240)
	at fr.inria.astor.core.solutionsearch.AstorCoreEngine.initModel(AstorCoreEngine.java:776)
	at fr.inria.main.evolution.AstorMain.createEngine(AstorMain.java:113)
	at fr.inria.main.evolution.AstorMain.run(AstorMain.java:173)
	at fr.inria.main.evolution.AstorMain.execute(AstorMain.java:233)
	at fr.inria.main.evolution.AstorMain.main(AstorMain.java:204)
[2132] INFO MutationSupporter - Recompiling with compliance level 8
[2132] INFO MutationSupporter - building model: /home/julia/mestrado/teste/Bugs/Closure-10/src, compliance level: 8
[2156] INFO MutationSupporter - Classpath (Dependencies) for building SpoonModel: null
org.eclipse.jdt.internal.compiler.problem.AbortCompilation: Pb(324) The type javax.annotation.Nullable cannot be resolved. It is indirectly referenced from required .class files
	at org.eclipse.jdt.internal.compiler.problem.ProblemHandler.handle(ProblemHandler.java:162)
	at org.eclipse.jdt.internal.compiler.problem.ProblemHandler.handle(ProblemHandler.java:229)
	at org.eclipse.jdt.internal.compiler.problem.ProblemReporter.handle(ProblemReporter.java:2646)
	at org.eclipse.jdt.internal.compiler.problem.ProblemReporter.isClassPathCorrect(ProblemReporter.java:5117)
	at org.eclipse.jdt.internal.compiler.lookup.UnresolvedReferenceBinding.resolve(UnresolvedReferenceBinding.java:123)
	at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.resolveType(BinaryTypeBinding.java:248)
	at org.eclipse.jdt.internal.compiler.lookup.PackageBinding.getTypeOrPackage(PackageBinding.java:252)
	at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.findImport(CompilationUnitScope.java:551)
	at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.findSingleImport(CompilationUnitScope.java:623)
	at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.resolveSingleImport(CompilationUnitScope.java:846)
	at org.eclipse.jdt.internal.compiler.lookup.Scope.getTypeOrPackage(Scope.java:3452)
	at org.eclipse.jdt.internal.compiler.lookup.Scope.getType(Scope.java:3177)
	at org.eclipse.jdt.internal.compiler.ast.SingleTypeReference.getTypeBinding(SingleTypeReference.java:57)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.internalResolveType(TypeReference.java:536)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.resolveType(TypeReference.java:639)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.resolveType(TypeReference.java:635)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.resolveType(TypeReference.java:631)
	at org.eclipse.jdt.internal.compiler.ast.Annotation.handleNonNullByDefault(Annotation.java:1121)
	at org.eclipse.jdt.internal.compiler.ast.ASTNode.handleNonNullByDefault(ASTNode.java:1058)
	at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.resolveTypesWithSuspendedTempErrorHandlingPolicy(SourceTypeBinding.java:2746)
	at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.resolveTypesFor(SourceTypeBinding.java:2649)
	at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.getExactConstructor(SourceTypeBinding.java:1669)
	at org.eclipse.jdt.internal.compiler.lookup.Scope.getConstructor0(Scope.java:2465)
	at org.eclipse.jdt.internal.compiler.lookup.Scope.getConstructor(Scope.java:2446)
	at org.eclipse.jdt.internal.compiler.ast.Statement.findConstructorBinding(Statement.java:588)
	at org.eclipse.jdt.internal.compiler.ast.AllocationExpression.resolveType(AllocationExpression.java:491)
	at org.eclipse.jdt.internal.compiler.ast.LocalDeclaration.resolve(LocalDeclaration.java:390)
	at org.eclipse.jdt.internal.compiler.ast.LocalDeclaration.resolve(LocalDeclaration.java:259)
	at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.resolveStatements(AbstractMethodDeclaration.java:661)
	at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.resolveStatements(MethodDeclaration.java:362)
	at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.resolve(AbstractMethodDeclaration.java:570)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1512)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1612)
	at org.eclipse.jdt.internal.compiler.ast.QualifiedAllocationExpression.getAnonymousConstructorBinding(QualifiedAllocationExpression.java:666)
	at org.eclipse.jdt.internal.compiler.ast.QualifiedAllocationExpression.resolveTypeForQualifiedAllocationExpression(QualifiedAllocationExpression.java:557)
	at org.eclipse.jdt.internal.compiler.ast.QualifiedAllocationExpression.resolveType(QualifiedAllocationExpression.java:304)
	at org.eclipse.jdt.internal.compiler.ast.FieldDeclaration.resolve(FieldDeclaration.java:294)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1448)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1637)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.resolve(CompilationUnitDeclaration.java:667)
	at spoon.support.compiler.jdt.TreeBuilderCompiler.buildUnits(TreeBuilderCompiler.java:105)
	at spoon.support.compiler.jdt.JDTBatchCompiler.getUnits(JDTBatchCompiler.java:283)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildUnits(JDTBasedSpoonCompiler.java:417)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildUnitsAndModel(JDTBasedSpoonCompiler.java:369)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildSources(JDTBasedSpoonCompiler.java:335)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:116)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:99)
	at fr.inria.astor.core.manipulation.MutationSupporter.buildModel(MutationSupporter.java:85)
	at fr.inria.astor.core.manipulation.MutationSupporter.buildSpoonModel(MutationSupporter.java:253)
	at fr.inria.astor.core.solutionsearch.AstorCoreEngine.initModel(AstorCoreEngine.java:776)
	at fr.inria.main.evolution.AstorMain.createEngine(AstorMain.java:113)
	at fr.inria.main.evolution.AstorMain.run(AstorMain.java:173)
	at fr.inria.main.evolution.AstorMain.execute(AstorMain.java:233)
	at fr.inria.main.evolution.AstorMain.main(AstorMain.java:204)
[2714] ERROR MutationSupporter - Error compiling: Pb(324) The type javax.annotation.Nullable cannot be resolved. It is indirectly referenced from required .class files
[2715] ERROR MutationSupporter - Astor continues when model build fails. Classes created: 0
[2715] INFO AstorCoreEngine - Number of CtTypes created: 0
[2722] INFO AstorCoreEngine - Test retrieved from classes: 0
[2722] INFO MutationSupporter - Creating model,  Code location from working folder: /home/julia/mestrado/teste/Bugs/Closure-10/src
[2722] INFO MutationSupporter - building model: /home/julia/mestrado/teste/Bugs/Closure-10/src, compliance level: 8
[2744] INFO MutationSupporter - Classpath (Dependencies) for building SpoonModel: null
[3110] ERROR MutationSupporter - Problem compiling the model with compliance level 8
[3110] ERROR MutationSupporter - Pb(324) The type javax.annotation.Nullable cannot be resolved. It is indirectly referenced from required .class files
org.eclipse.jdt.internal.compiler.problem.AbortCompilation: Pb(324) The type javax.annotation.Nullable cannot be resolved. It is indirectly referenced from required .class files
	at org.eclipse.jdt.internal.compiler.problem.ProblemHandler.handle(ProblemHandler.java:162)
	at org.eclipse.jdt.internal.compiler.problem.ProblemHandler.handle(ProblemHandler.java:229)
	at org.eclipse.jdt.internal.compiler.problem.ProblemReporter.handle(ProblemReporter.java:2646)
	at org.eclipse.jdt.internal.compiler.problem.ProblemReporter.isClassPathCorrect(ProblemReporter.java:5117)
	at org.eclipse.jdt.internal.compiler.lookup.UnresolvedReferenceBinding.resolve(UnresolvedReferenceBinding.java:123)
	at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.resolveType(BinaryTypeBinding.java:248)
	at org.eclipse.jdt.internal.compiler.lookup.PackageBinding.getTypeOrPackage(PackageBinding.java:252)
	at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.findImport(CompilationUnitScope.java:551)
	at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.findSingleImport(CompilationUnitScope.java:623)
	at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.resolveSingleImport(CompilationUnitScope.java:846)
	at org.eclipse.jdt.internal.compiler.lookup.Scope.getTypeOrPackage(Scope.java:3452)
	at org.eclipse.jdt.internal.compiler.lookup.Scope.getType(Scope.java:3177)
	at org.eclipse.jdt.internal.compiler.ast.SingleTypeReference.getTypeBinding(SingleTypeReference.java:57)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.internalResolveType(TypeReference.java:536)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.resolveType(TypeReference.java:639)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.resolveType(TypeReference.java:635)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.resolveType(TypeReference.java:631)
	at org.eclipse.jdt.internal.compiler.ast.Annotation.handleNonNullByDefault(Annotation.java:1121)
	at org.eclipse.jdt.internal.compiler.ast.ASTNode.handleNonNullByDefault(ASTNode.java:1058)
	at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.resolveTypesWithSuspendedTempErrorHandlingPolicy(SourceTypeBinding.java:2746)
	at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.resolveTypesFor(SourceTypeBinding.java:2649)
	at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.getExactConstructor(SourceTypeBinding.java:1669)
	at org.eclipse.jdt.internal.compiler.lookup.Scope.getConstructor0(Scope.java:2465)
	at org.eclipse.jdt.internal.compiler.lookup.Scope.getConstructor(Scope.java:2446)
	at org.eclipse.jdt.internal.compiler.ast.Statement.findConstructorBinding(Statement.java:588)
	at org.eclipse.jdt.internal.compiler.ast.AllocationExpression.resolveType(AllocationExpression.java:491)
	at org.eclipse.jdt.internal.compiler.ast.LocalDeclaration.resolve(LocalDeclaration.java:390)
	at org.eclipse.jdt.internal.compiler.ast.LocalDeclaration.resolve(LocalDeclaration.java:259)
	at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.resolveStatements(AbstractMethodDeclaration.java:661)
	at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.resolveStatements(MethodDeclaration.java:362)
	at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.resolve(AbstractMethodDeclaration.java:570)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1512)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1612)
	at org.eclipse.jdt.internal.compiler.ast.QualifiedAllocationExpression.getAnonymousConstructorBinding(QualifiedAllocationExpression.java:666)
	at org.eclipse.jdt.internal.compiler.ast.QualifiedAllocationExpression.resolveTypeForQualifiedAllocationExpression(QualifiedAllocationExpression.java:557)
	at org.eclipse.jdt.internal.compiler.ast.QualifiedAllocationExpression.resolveType(QualifiedAllocationExpression.java:304)
	at org.eclipse.jdt.internal.compiler.ast.FieldDeclaration.resolve(FieldDeclaration.java:294)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1448)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1637)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.resolve(CompilationUnitDeclaration.java:667)
	at spoon.support.compiler.jdt.TreeBuilderCompiler.buildUnits(TreeBuilderCompiler.java:105)
	at spoon.support.compiler.jdt.JDTBatchCompiler.getUnits(JDTBatchCompiler.java:283)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildUnits(JDTBasedSpoonCompiler.java:417)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildUnitsAndModel(JDTBasedSpoonCompiler.java:369)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildSources(JDTBasedSpoonCompiler.java:335)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:116)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:99)
	at fr.inria.astor.core.manipulation.MutationSupporter.buildModel(MutationSupporter.java:85)
	at fr.inria.astor.core.manipulation.MutationSupporter.buildSpoonModel(MutationSupporter.java:240)
	at fr.inria.astor.core.faultlocalization.cocospoon.CocoFaultLocalization.initModel(CocoFaultLocalization.java:162)
	at fr.inria.astor.core.faultlocalization.cocospoon.CocoFaultLocalization.searchSuspicious(CocoFaultLocalization.java:51)
	at fr.inria.astor.core.solutionsearch.AstorCoreEngine.calculateSuspicious(AstorCoreEngine.java:903)
	at fr.inria.main.evolution.AstorMain.createEngine(AstorMain.java:119)
	at fr.inria.main.evolution.AstorMain.run(AstorMain.java:173)
	at fr.inria.main.evolution.AstorMain.execute(AstorMain.java:233)
	at fr.inria.main.evolution.AstorMain.main(AstorMain.java:204)
[3113] INFO MutationSupporter - Recompiling with compliance level 8
[3113] INFO MutationSupporter - building model: /home/julia/mestrado/teste/Bugs/Closure-10/src, compliance level: 8
[3133] INFO MutationSupporter - Classpath (Dependencies) for building SpoonModel: null
org.eclipse.jdt.internal.compiler.problem.AbortCompilation: Pb(324) The type javax.annotation.Nullable cannot be resolved. It is indirectly referenced from required .class files
	at org.eclipse.jdt.internal.compiler.problem.ProblemHandler.handle(ProblemHandler.java:162)
	at org.eclipse.jdt.internal.compiler.problem.ProblemHandler.handle(ProblemHandler.java:229)
	at org.eclipse.jdt.internal.compiler.problem.ProblemReporter.handle(ProblemReporter.java:2646)
	at org.eclipse.jdt.internal.compiler.problem.ProblemReporter.isClassPathCorrect(ProblemReporter.java:5117)
	at org.eclipse.jdt.internal.compiler.lookup.UnresolvedReferenceBinding.resolve(UnresolvedReferenceBinding.java:123)
	at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.resolveType(BinaryTypeBinding.java:248)
	at org.eclipse.jdt.internal.compiler.lookup.PackageBinding.getTypeOrPackage(PackageBinding.java:252)
	at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.findImport(CompilationUnitScope.java:551)
	at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.findSingleImport(CompilationUnitScope.java:623)
	at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.resolveSingleImport(CompilationUnitScope.java:846)
	at org.eclipse.jdt.internal.compiler.lookup.Scope.getTypeOrPackage(Scope.java:3452)
	at org.eclipse.jdt.internal.compiler.lookup.Scope.getType(Scope.java:3177)
	at org.eclipse.jdt.internal.compiler.ast.SingleTypeReference.getTypeBinding(SingleTypeReference.java:57)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.internalResolveType(TypeReference.java:536)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.resolveType(TypeReference.java:639)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.resolveType(TypeReference.java:635)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.resolveType(TypeReference.java:631)
	at org.eclipse.jdt.internal.compiler.ast.Annotation.handleNonNullByDefault(Annotation.java:1121)
	at org.eclipse.jdt.internal.compiler.ast.ASTNode.handleNonNullByDefault(ASTNode.java:1058)
	at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.resolveTypesWithSuspendedTempErrorHandlingPolicy(SourceTypeBinding.java:2746)
	at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.resolveTypesFor(SourceTypeBinding.java:2649)
	at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.getExactConstructor(SourceTypeBinding.java:1669)
	at org.eclipse.jdt.internal.compiler.lookup.Scope.getConstructor0(Scope.java:2465)
	at org.eclipse.jdt.internal.compiler.lookup.Scope.getConstructor(Scope.java:2446)
	at org.eclipse.jdt.internal.compiler.ast.Statement.findConstructorBinding(Statement.java:588)
	at org.eclipse.jdt.internal.compiler.ast.AllocationExpression.resolveType(AllocationExpression.java:491)
	at org.eclipse.jdt.internal.compiler.ast.LocalDeclaration.resolve(LocalDeclaration.java:390)
	at org.eclipse.jdt.internal.compiler.ast.LocalDeclaration.resolve(LocalDeclaration.java:259)
	at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.resolveStatements(AbstractMethodDeclaration.java:661)
	at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.resolveStatements(MethodDeclaration.java:362)
	at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.resolve(AbstractMethodDeclaration.java:570)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1512)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1612)
	at org.eclipse.jdt.internal.compiler.ast.QualifiedAllocationExpression.getAnonymousConstructorBinding(QualifiedAllocationExpression.java:666)
	at org.eclipse.jdt.internal.compiler.ast.QualifiedAllocationExpression.resolveTypeForQualifiedAllocationExpression(QualifiedAllocationExpression.java:557)
	at org.eclipse.jdt.internal.compiler.ast.QualifiedAllocationExpression.resolveType(QualifiedAllocationExpression.java:304)
	at org.eclipse.jdt.internal.compiler.ast.FieldDeclaration.resolve(FieldDeclaration.java:294)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1448)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1637)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.resolve(CompilationUnitDeclaration.java:667)
	at spoon.support.compiler.jdt.TreeBuilderCompiler.buildUnits(TreeBuilderCompiler.java:105)
	at spoon.support.compiler.jdt.JDTBatchCompiler.getUnits(JDTBatchCompiler.java:283)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildUnits(JDTBasedSpoonCompiler.java:417)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildUnitsAndModel(JDTBasedSpoonCompiler.java:369)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildSources(JDTBasedSpoonCompiler.java:335)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:116)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:99)
	at fr.inria.astor.core.manipulation.MutationSupporter.buildModel(MutationSupporter.java:85)
	at fr.inria.astor.core.manipulation.MutationSupporter.buildSpoonModel(MutationSupporter.java:253)
	at fr.inria.astor.core.faultlocalization.cocospoon.CocoFaultLocalization.initModel(CocoFaultLocalization.java:162)
	at fr.inria.astor.core.faultlocalization.cocospoon.CocoFaultLocalization.searchSuspicious(CocoFaultLocalization.java:51)
	at fr.inria.astor.core.solutionsearch.AstorCoreEngine.calculateSuspicious(AstorCoreEngine.java:903)
	at fr.inria.main.evolution.AstorMain.createEngine(AstorMain.java:119)
	at fr.inria.main.evolution.AstorMain.run(AstorMain.java:173)
	at fr.inria.main.evolution.AstorMain.execute(AstorMain.java:233)
	at fr.inria.main.evolution.AstorMain.main(AstorMain.java:204)
[3450] ERROR MutationSupporter - Error compiling: Pb(324) The type javax.annotation.Nullable cannot be resolved. It is indirectly referenced from required .class files
[3451] ERROR MutationSupporter - Astor continues when model build fails. Classes created: 0
Classpath [, /home/julia/mestrado/teste/astor_bkp/target/astor-2.0.0-jar-with-dependencies.jar, /home/julia/mestrado/teste/Bugs/Chart-5/target/./output_astor/AstorMain-Closure-10//bin//default]
[3489] ERROR SpoonClassCompiler - Problem compiling
Exception in thread "main" java.lang.IllegalStateException: no source files
	at com.sun.tools.javac.main.Main.error(Main.java:186)
	at com.sun.tools.javac.main.Main.compile(Main.java:428)
	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
	at fr.inria.astor.core.manipulation.bytecode.compiler.tools.JavaXToolsCompiler.runCompilationTask(JavaXToolsCompiler.java:83)
	at fr.inria.astor.core.manipulation.bytecode.compiler.tools.JavaXToolsCompiler.javaBytecodeFor(JavaXToolsCompiler.java:47)
	at fr.inria.astor.core.manipulation.bytecode.compiler.SpoonClassCompiler.compile(SpoonClassCompiler.java:99)
	at fr.inria.astor.core.manipulation.bytecode.compiler.SpoonClassCompiler.compile(SpoonClassCompiler.java:76)
	at fr.inria.astor.core.faultlocalization.cocospoon.CocoFaultLocalization.compile(CocoFaultLocalization.java:127)
	at fr.inria.astor.core.faultlocalization.cocospoon.CocoFaultLocalization.searchSuspicious(CocoFaultLocalization.java:58)
	at fr.inria.astor.core.solutionsearch.AstorCoreEngine.calculateSuspicious(AstorCoreEngine.java:903)
	at fr.inria.main.evolution.AstorMain.createEngine(AstorMain.java:119)
	at fr.inria.main.evolution.AstorMain.run(AstorMain.java:173)
	at fr.inria.main.evolution.AstorMain.execute(AstorMain.java:233)
	at fr.inria.main.evolution.AstorMain.main(AstorMain.java:204)

```

How to solve this?

**Comment by slarse** [comment]
Hi @juliamanfrindias,

This seems like a question for Astor's issue tracker, please see https://github.com/SpoonLabs/astor/issues

**Comment by MartinWitt** [comment]
Closed because unrelated to spoon.
