### ISSUE TITLE
[Bug?] Abstract Methods don't have Bodies

### ISSUE THREAD

**Issue by lapplislazuli** [INRIA/spoon#4752]
**Describe the bug**
When an abstract class has an abstract method, asking for the abstract's methods body returns null. 

I am not sure if this is intended behaviour, but for me it was definetely suprising. If that is intended, I would be happy with a more precise error message / more graceful behaviour. 

**To Reproduce**

Input:
```java17
    @Test
    public void testAbstractMethods_DoesNotHaveABody(){
        String code = """
                public abstract class example_abstract_class {
                    
                    public abstract void abstract_method() {
                        int variable = 1;
                        System.out.println("Hello Abstract World");
                    }
                }
                """;
        CtElement testObject = Launcher.parseClass(code);

        List<CtMethod> allMethodsWithBody = testObject
                .filterChildren(c -> c instanceof CtMethod)
                .list()
                .stream()
                .map(o -> (CtMethod) o)
                // Next line throws an error, as "getBody()" returns null!
                .filter(c -> ! c.getBody().getStatements().isEmpty())
                .collect(Collectors.toList());
    }
```

Output:
```java
java.lang.NullPointerException: Cannot invoke "spoon.reflect.code.CtBlock.getStatements()" because the return value of "spoon.reflect.declaration.CtMethod.getBody()" is null
	at com.github.ciselab.lampion.core/com.github.ciselab.lampion.core.exploration.SpoonTests.lambda$testAbstractMethods_DoesNotHaveABody$34(SpoonTests.java:861)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at [...]
```

**Operating system, JDK and Spoon version used**

* OS: Windows
* JDK: 17
* Spoon version: 10.0.0

**Comment by SirYwell** [comment]
Your example code wouldn't compile.
According to the [JLS § 8.4.1](https://docs.oracle.com/javase/specs/jls/se18/html/jls-8.html#jls-8.4.7), an `abstract` method has only a `;` as its body. As semicolons aren't modelled in spoon in any way and the `getBody()` method returns a `CtBlock`, returning `null` is a sensible value in such case. 
We could probably outline that behavior in the javadocs.

**Comment by lapplislazuli** [comment]
@SirYwell Thanks for your quick response! 
I learn new things about java every day 😅 

I then fully understand the behaviour, however I think it could be worth to throw a SpoonException when an abstract methods' `getBody` is called.
Something along "SpoonException: Abstract Methods do not have a method body"

But I am fine with the given explanation, so feel free to close the issue :)

**Comment by slarse** [comment]
Closing then, thanks for answering @SirYwell !
