### ISSUE TITLE
NullPointerException in JDTTreeBuilder

### ISSUE THREAD

**Issue by worblehat** [INRIA/spoon#479]
I am getting the following exception when building a model (with `setNoClasspath(true)`) for a project of mine, using the current master branch at 58b6a5d2ce557d779b3cb9f350c3ba603f4e255c : 

```
Exception in thread "main" java.lang.NullPointerException
	at spoon.support.compiler.jdt.JDTTreeBuilder.insertGenericTypesInNoClasspathFromJDTInSpoon(JDTTreeBuilder.java:1126)
	at spoon.support.compiler.jdt.JDTTreeBuilder.createType(JDTTreeBuilder.java:1095)
	at spoon.support.compiler.jdt.JDTTreeBuilder.visit(JDTTreeBuilder.java:3239)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.traverse(TypeDeclaration.java:1430)
	at spoon.support.compiler.jdt.JDTTreeBuilder.visit(JDTTreeBuilder.java:3281)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.traverse(TypeDeclaration.java:1319)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.traverse(CompilationUnitDeclaration.java:748)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.traverse(CompilationUnitDeclaration.java:709)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildSources(JDTBasedSpoonCompiler.java:228)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:481)
...
```

**Comment by GerardPaligot** [comment]
Can you give us a snippet which throws this exception?

**Comment by worblehat** [comment]
I figured out that I get that exception when analysing a class that implements an interface which is a nested **and** generic type.

For example:

```
import example.Foo;

public class Demo implements Foo.Bar<String> {

}
```

where "example.Foo" is not in the class path.

**Comment by GerardPaligot** [comment]
Well, we have a problem here but not from Spoon, from JDT.

Where we iterate on all super interfaces of `Demo`, JDT give us `Foo` and not `Foo.Bar<String>`. So, we can't produce a correct AST and print it.

@monperrus @tdurieux Any idea what we can do here?

**Comment by tdurieux** [comment]
We can detect that JDT does not produce a correct AST by comparing the ```ref.resolvedType.compoundName``` with the value in the last index of ```ref.tokens```.

**Comment by GerardPaligot** [comment]
Bad solution but certainly the better one...
