### ISSUE TITLE
[Bug]: Raising a SpoonException when parsing a module-info.java file

### ISSUE THREAD

**Issue by gustavopintozup** [INRIA/spoon#4812]
### Describe the bug

If the project I'm analyzing has a module-info.java file, spoon raises the following exception

```java
Exception in thread "main" spoon.SpoonException: Modules are only available since Java 9. Please set appropriate compliance level.
        at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.forEachCompilationUnit(JDTBasedSpoonCompiler.java:460)
        at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildModel(JDTBasedSpoonCompiler.java:436)
        at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildUnitsAndModel(JDTBasedSpoonCompiler.java:373)
        at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildSources(JDTBasedSpoonCompiler.java:336)
        at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:117)
        at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:100)
        at spoon.Launcher.buildModel(Launcher.java:782)
        at spoon.Launcher.run(Launcher.java:733)
        at br.com.stackedu.cdd.Minerador.main(Minerador.java:110)
```

I tried to compile spoon with Java 11 and 17, but it keeps raising the same exception. Any pointers?

### Source code you are trying to analyze/transform

```Java
module ex {}
```

### Spoon Version

10.2.0-beta-11

### JVM Version

17

### What operating system are you using?

Ubuntu

**Comment by gustavopintozup** [comment]
Nevermind, I just found `setComplianceLevel`, and it solved the problem. 

Thanks for building spoon!

**Comment by slarse** [comment]
Hi @gustavopintozup,

As it wasn't clear to you that the error was on your part, I think we should try to improve the error message. What do you think about something like:

```
Modules are only available since Java 9. Please set the appropriate compliance level in Spoon's environment. Example: launcher.getEnvironment().setComplianceLevel(9)
```

Or something like that?

**Comment by gustavopintozup** [comment]
Hello @slarse ! 

This improved error message sounds great to me! It'd saved me some good minutes :-)
