### ISSUE TITLE
[Bug]: Attempting to build model of Dubbo (3.1.1)

### ISSUE THREAD

**Issue by QifanWang** [INRIA/spoon#4952]
### Describe the bug

I try to analyze Dubbo source code, but Spoon throws a ModelBuildingException. Shall I use Spoon to analyze such multi-pom.xml projects? Or I need to set some properties of maven laucher?

### Source code you are trying to analyze/transform

```Java
Source code are downloaded from https://github.com/apache/dubbo/archive/refs/tags/dubbo-3.1.1.zip
```

### Source code for your Spoon processing

```Java
MavenLauncher launcher = new MavenLauncher(
               "/home/cstar/Downloads/dubbo-dubbo-3.1.1",
                MavenLauncher.SOURCE_TYPE.APP_SOURCE);
launcher.buildModel();
```

### Actual output

```Java
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" spoon.compiler.ModelBuildingException: The type Application is already defined
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.reportProblem(JDTBasedSpoonCompiler.java:598)
	at spoon.support.compiler.jdt.TreeBuilderRequestor.acceptResult(TreeBuilderRequestor.java:29)
	at spoon.support.compiler.jdt.TreeBuilderCompiler.buildUnits(TreeBuilderCompiler.java:110)
	at spoon.support.compiler.jdt.JDTBatchCompiler.getUnits(JDTBatchCompiler.java:283)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildUnits(JDTBasedSpoonCompiler.java:416)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildUnitsAndModel(JDTBasedSpoonCompiler.java:368)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildSources(JDTBasedSpoonCompiler.java:334)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:115)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:98)
	at spoon.Launcher.buildModel(Launcher.java:782)
	at Main.main(Main.java:9)

Process finished with exit code 1
```

### Expected output

```Java
build model successfully.
```

### Spoon Version

10.1.1

### JVM Version

11

### What operating system are you using?

Ubuntu 20.04.3 LTS

**Comment by SirYwell** [comment]
> I do not understand as the documentation states:
> 
> > The Spoon MavenLauncher ([JavaDoc](http://spoon.gforge.inria.fr/mvnsites/spoon-core/apidocs/spoon/MavenLauncher.html)) is used to create the AST model of a Maven project. It automatically infers the list of source folders and the dependencies from the pom.xml file. This launcher handles multi-module Maven projects.

Yes, the issue here is the vague usage of "handles multi-module Maven projects". What that (currently) actually means it can find all the modules, it can find the dependencies of all the modules, but all the modules are on the source classpath for JDT, so JDT will try to compile all at once. I assume this can't be simply fixed in a non-breaking way in the current MavenLauncher,

> I may be mistaken, the documentation talks about Maven modules, not Jigsaw modules?
> 
> This bug seems related to #4751.

Yes, the documentation of the MavenLauncher talks about Maven modules. The given project also doesn't seem to be based on Jigsaw modules, so that shouldn't be an issue here.

**Comment by dhmoclex** [comment]
> Yes, the documentation of the MavenLauncher talks about Maven modules. The given project also doesn't seem to be based on Jigsaw modules, so that shouldn't be an issue here.

To what correspond the [CtModule](https://spoon.gforge.inria.fr/mvnsites/spoon-core/apidocs/spoon/reflect/declaration/CtModule.html) in Spoon?

Is it ever used when building a model?
