### ISSUE TITLE
[Bug]: spoon.support.SpoonClassNotFoundException: cannot load class  

### ISSUE THREAD

**Issue by jungleTail** [INRIA/spoon#5100]
### Describe the bug

When I use the `partiallyEvaluate()` method to evaluate a expression, the exception occurs. 
The test code is project arthas from [https://github.com/alibaba/arthas].
 
When the expression is `(obj.getClass() != com.taobao.arthas.core.env.convert.ConvertiblePair.class)`, spoon can not load the class `com.taobao.arthas.core.env.convert.ConvertiblePair`.

### Source code you are trying to analyze/transform

```Java
(obj.getClass() != com.taobao.arthas.core.env.convert.ConvertiblePair.class)
```

### Source code for your Spoon processing

```Java
expr.partiallyEvaluate();
```

### Actual output

```Java
spoon.support.SpoonClassNotFoundException: cannot load class: com.taobao.arthas.core.env.convert.ConvertiblePair
	at spoon.support.reflect.reference.CtTypeReferenceImpl.loadClassWithQName(CtTypeReferenceImpl.java:190)
	at spoon.support.reflect.reference.CtTypeReferenceImpl.lambda$getClassFromThreadLocalCacheOrLoad$1(CtTypeReferenceImpl.java:172)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
	at spoon.support.reflect.reference.CtTypeReferenceImpl.getClassFromThreadLocalCacheOrLoad(CtTypeReferenceImpl.java:172)
	at spoon.support.reflect.reference.CtTypeReferenceImpl.findClass(CtTypeReferenceImpl.java:163)
	at java.base/java.util.Optional.orElseGet(Optional.java:369)
	at spoon.support.reflect.reference.CtTypeReferenceImpl.getActualClass(CtTypeReferenceImpl.java:119)
	at spoon.support.reflect.eval.VisitorPartialEvaluator.visitFieldAccess(VisitorPartialEvaluator.java:306)
	at spoon.support.reflect.eval.VisitorPartialEvaluator.visitCtFieldRead(VisitorPartialEvaluator.java:296)
	at spoon.support.reflect.code.CtFieldReadImpl.accept(CtFieldReadImpl.java:18)
	at spoon.support.reflect.eval.VisitorPartialEvaluator.evaluate
```

### Spoon Version

10.2.1

### JVM Version

11

### What operating system are you using?

windows 11

**Comment by I-Al-Istannen** [comment]
It looks like the class is not available in the classpath of the classloader/JVM running your spoon code. You can try setting the `sourceClassPath` of the environment to something including your projects's class files.

Alternatively you can also set the source classpath to include the binary output directory (e.g. `getEnvironment().setSourceClasspath(new String[]{getEnvironment().getBinaryOutputDirectory()});`) and ensure you call `modelBuilder.compile()` before evaluating it. This can, for example, be achieved using `launcher.getModelBuilder().compile(InputType.CTTYPES`.
