### ISSUE TITLE
[Bug]: Usage of type parameters in "throws" clause yields NPE

### ISSUE THREAD

**Issue by JTurcotti** [INRIA/spoon#5115]
### Describe the bug

It seems that fun when type parameters are mentioned in a "throws" clause, Spoon can throw an NPE

### Source code you are trying to analyze/transform

```Java
package bug;

public abstract class Bug {
    public abstract <E extends Throwable> T orElseThrow(E throwable) throws E;
}

class Bug2 extends Bug {
    @Override
    public <E extends Throwable> T orElseThrow(E throwable) throws E {
        throw throwable;
    }
}
```

### Source code for your Spoon processing

```Java
Launcher launcher = new Launcher();
        launcher.addInputResource(sourcePath);
        launcher.getEnvironment().setComplianceLevel(18);
        launcher.buildModel();
        model = launcher.getModel();
        var methods = model.getElements(new TypeFilter<>(CtMethod.class));
        model.getElements(new OverriddenMethodFilter(methods.get(1))).contains(methods.get(0));
        model.getElements(new OverridingMethodFilter(methods.get(1))).contains(methods.get(0));
```

### Actual output

```Java
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "spoon.reflect.declaration.CtType.getQualifiedName()" because "end" is null
	at spoon.support.adaption.TypeAdaptor.buildDeclarationHierarchyFrom(TypeAdaptor.java:629)
	at spoon.support.adaption.TypeAdaptor.buildHierarchyFrom(TypeAdaptor.java:567)
	at spoon.support.adaption.TypeAdaptor.adaptType(TypeAdaptor.java:467)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at spoon.support.adaption.TypeAdaptor.adaptMethod(TypeAdaptor.java:246)
	at spoon.support.adaption.TypeAdaptor.isOverriding(TypeAdaptor.java:411)
	at spoon.reflect.visitor.filter.OverriddenMethodFilter.matches(OverriddenMethodFilter.java:47)
	at spoon.reflect.visitor.filter.OverriddenMethodFilter.matches(OverriddenMethodFilter.java:17)
	at spoon.reflect.visitor.chain.CtQueryImpl$1.apply(CtQueryImpl.java:171)
	at spoon.reflect.visitor.chain.CtQueryImpl$1.apply(CtQueryImpl.java:168)
	at spoon.reflect.visitor.chain.CtQueryImpl$FunctionWrapper._accept(CtQueryImpl.java:510)
	at spoon.reflect.visitor.chain.CtQueryImpl$AbstractStep.accept(CtQueryImpl.java:305)
	at spoon.reflect.visitor.filter.CtScannerFunction$Scanner.onElement(CtScannerFunction.java:78)
	at spoon.reflect.visitor.EarlyTerminatingScanner.doScan(EarlyTerminatingScanner.java:141)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:121)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:184)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:106)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:83)
	at spoon.reflect.visitor.CtScanner.visitCtClass(CtScanner.java:357)
	at spoon.support.reflect.declaration.CtClassImpl.accept(CtClassImpl.java:63)
	at spoon.reflect.visitor.EarlyTerminatingScanner.doScan(EarlyTerminatingScanner.java:145)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:121)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:184)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:106)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:83)
	at spoon.reflect.visitor.CtScanner.visitCtPackage(CtScanner.java:679)
	at spoon.support.reflect.declaration.CtPackageImpl.accept(CtPackageImpl.java:82)
	at spoon.reflect.visitor.EarlyTerminatingScanner.doScan(EarlyTerminatingScanner.java:145)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:121)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:184)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:106)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:83)
	at spoon.reflect.visitor.CtScanner.visitCtPackage(CtScanner.java:678)
	at spoon.support.reflect.declaration.CtPackageImpl.accept(CtPackageImpl.java:82)
	at spoon.reflect.visitor.EarlyTerminatingScanner.doScan(EarlyTerminatingScanner.java:145)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:121)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:184)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:106)
	at spoon.reflect.visitor.CtScanner.visitCtModule(CtScanner.java:964)
	at spoon.reflect.factory.ModuleFactory$CtUnnamedModule.accept(ModuleFactory.java:96)
	at spoon.reflect.visitor.EarlyTerminatingScanner.doScan(EarlyTerminatingScanner.java:145)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:121)
	at spoon.reflect.visitor.filter.CtScannerFunction.apply(CtScannerFunction.java:57)
	at spoon.reflect.visitor.filter.CtScannerFunction.apply(CtScannerFunction.java:27)
	at spoon.reflect.visitor.chain.CtQueryImpl$LazyFunctionWrapper._accept(CtQueryImpl.java:490)
	at spoon.reflect.visitor.chain.CtQueryImpl$AbstractStep.accept(CtQueryImpl.java:305)
	at spoon.reflect.visitor.chain.CtQueryImpl.forEach(CtQueryImpl.java:97)
	at spoon.reflect.visitor.chain.CtQueryImpl.list(CtQueryImpl.java:110)
	at spoon.reflect.visitor.chain.CtQueryImpl.list(CtQueryImpl.java:104)
	at spoon.reflect.CtModelImpl.getElements(CtModelImpl.java:131)
	at analyzer.ProgramAnalyzer.<init>(ProgramAnalyzer.java:42)
	at main.Main.main(Main.java:8)
```

### Expected output

```Java
just not an NPE
```

### Spoon Version

10.2.0

### JVM Version

18

### What operating system are you using?

Mac OSX

**Comment by I-Al-Istannen** [comment]
Should be fixed in the linked PR (#5117), you can give it a try if you want (or wait a week until it hopefully is in the new snapshot) :)
