### ISSUE TITLE
[Bug]: Crash when calling `CtFieldReference#getActualField` on a reference to the array's length: The field `int#length` not found

### ISSUE THREAD

**Issue by Luro02** [INRIA/spoon#5199]
### Describe the bug

A crash occurs when you try to execute the code below.

The `getActualField` method is not used by our code, but indirectly called through `getModifiers`.
This is the code in spoon that causes the crash:
https://github.com/INRIA/spoon/blob/194f91a7e963901a7034fbe1bd18c682a461e766/src/main/java/spoon/support/reflect/reference/CtFieldReferenceImpl.java#L56-L80

The `declaringType` for the field reference to the array's `length` attribute is set to `int`, which seems to be the root cause for this issue?

As a side-note: The inlined instantiation of the array is not the reason for the crash. This code will produce the same exception:
```java
String[] array = new String[1];
int value = array.length;
```

### Source code you are trying to analyze/transform

```Java
public class Example {
    public static void main(String[] args) {
        int value = ((new String[1])).length;
    }
}
```

### Source code for your Spoon processing

```Java
Launcher launcher = new Launcher();

launcher.getEnvironment().setComplianceLevel(17);
launcher.addInputResource(new VirtualFile("""
    public class Example {
        public static void main(String[] args) {
            int value = ((new String[1])).length;
        }
    }
    """));

    CtModel ctModel = launcher.buildModel();

    ctModel.processWith(new AbstractProcessor<CtVariableAccess<?>>() {
        @Override
        public void process(CtVariableAccess<?> element) {
            if (!(element.getVariable() instanceof CtFieldReference<?> ctFieldReference)) {
                return;
            }

            ctFieldReference.getActualField(); // <- this crashes
        }
    });
```

### Actual output

```Java
Exception in thread "main" spoon.SpoonException: The field int#length not found
	at spoon.support.reflect.reference.CtFieldReferenceImpl.getActualField(CtFieldReferenceImpl.java:78)
	at org.example.playground.App$1.process(App.java:78)
	at org.example.playground.App$1.process(App.java:70)
	at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:72)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:184)
	at spoon.reflect.visitor.CtScanner.visitCtLocalVariable(CtScanner.java:555)
	at spoon.support.reflect.code.CtLocalVariableImpl.accept(CtLocalVariableImpl.java:51)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:194)
	at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:68)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:184)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:149)
	at spoon.reflect.visitor.CtScanner.visitCtBlock(CtScanner.java:321)
	at spoon.support.reflect.code.CtBlockImpl.accept(CtBlockImpl.java:58)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:194)
	at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:68)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:184)
	at spoon.reflect.visitor.CtScanner.visitCtMethod(CtScanner.java:589)
	at spoon.support.reflect.declaration.CtMethodImpl.accept(CtMethodImpl.java:59)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:194)
	at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:68)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:184)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:149)
	at spoon.reflect.visitor.CtScanner.visitCtClass(CtScanner.java:357)
	at spoon.support.reflect.declaration.CtClassImpl.accept(CtClassImpl.java:63)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:194)
	at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:68)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:184)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:149)
	at spoon.reflect.visitor.CtScanner.visitCtPackage(CtScanner.java:679)
	at spoon.support.reflect.declaration.CtPackageImpl.accept(CtPackageImpl.java:82)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:194)
	at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:68)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:184)
	at spoon.reflect.visitor.CtScanner.visitCtModule(CtScanner.java:964)
	at spoon.reflect.factory.ModuleFactory$CtUnnamedModule.accept(ModuleFactory.java:96)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:194)
	at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:68)
	at spoon.support.QueueProcessingManager.process(QueueProcessingManager.java:118)
	at spoon.reflect.CtModelImpl.processWith(CtModelImpl.java:126)
	at org.example.playground.App.executeSpoon(App.java:70)
	at org.example.playground.App.main(App.java:53)
Caused by: java.lang.NoSuchFieldException: length
	at java.base/java.lang.Class.getDeclaredField(Class.java:2610)
	at spoon.support.reflect.reference.CtFieldReferenceImpl.getActualField(CtFieldReferenceImpl.java:75)
	... 40 more
Disconnected from the target VM, address: '127.0.0.1:53463', transport: 'socket'

Process finished with exit code 1
```

### Spoon Version

10.3.0

### JVM Version

openjdk version "17.0.1" 2021-10-19 OpenJDK Runtime Environment Temurin-17.0.1+12 (build 17.0.1+12) OpenJDK 64-Bit Server VM Temurin-17.0.1+12 (build 17.0.1+12, mixed mode, sharing)

### What operating system are you using?

Windows 10

**Comment by SirYwell** [comment]
While #5206 fixed an obvious bug, the rest of this isn't as clear. 
The `length` field from arrays can't be represented as `Field` object via reflection:
> [If this Class object represents an array type, then this method does not find the length field of the array type.](https://docs.oracle.com/en/java/javase/20/docs/api/java.base/java/lang/Class.html#getField(java.lang.String))

As `getActualField` returns a [`Member`](https://docs.oracle.com/en/java/javase/20/docs/api/java.base/java/lang/reflect/Member.html), we could still return a custom `Member` implementation representing the field as good as possible, but I'm not sure if that's something we actually want to do.

Alternatively, we could special-case the `getModifiers` method to return the proper modifiers for the length field, and keep the behavior of `getActualField` close to the reflection API (this would probably require more workarounds specific to that field, depending on the current usage of `getActualField` in spoon). We could expand the javadoc to clearify the behavior for users.

Before going forward with one solution, I'd like to know if you have any opinion on this @monperrus @MartinWitt @slarse @I-Al-Istannen. The first idea is pretty simple, but might be surprising for users, the second requires more effort I assume, but might be surprising for users too...

**Comment by I-Al-Istannen** [comment]
I guess that depends on how people use `getActualField` (if at all). The first one is nice if you use get the field to query some modifiers or a name, but for everything else it sounds pretty surprising.

I think I would be for the second one. It already throws an exception so that wouldn't be a real behaviour change and makes some sense IMHO.

**Comment by Luro02** [comment]
The bug is not fixed:
```java
import spoon.Launcher;
import spoon.reflect.code.CtFieldAccess;
import spoon.reflect.declaration.CtClass;
import spoon.reflect.visitor.filter.TypeFilter;

public class Example {
    public static void main(String[] args) {
        CtClass<?> ctClass = Launcher.parseClass("""
            public class Example {
                public static void main(String[] args) {
                    Other other = new Other();
                    System.out.println(other.array.length);
                }
                
                static class Other { public String[] array = new String[4]; }
            }""");

        // get the other.array.length access
        CtFieldAccess<?> ctFieldAccess = ctClass.getFactory().getModel().getElements(new TypeFilter<>(CtFieldAccess.class)).get(1);

        System.out.println(ctFieldAccess);
        System.out.println(ctFieldAccess.getVariable().getModifiers());
    }
}
```
