### ISSUE TITLE
NPE in `JDTTreeBuilder.isContainsInTypeAnnotation`

### ISSUE THREAD

**Issue by worblehat** [INRIA/spoon#529]
I found another `NullPointerException` to be thrown by JDTTreeBuilder in noclassepath-mode:

```
Exception in thread "main" java.lang.NullPointerException
	at spoon.support.compiler.jdt.JDTTreeBuilder.isContainsInTypeAnnotation(JDTTreeBuilder.java:2733)
	at spoon.support.compiler.jdt.JDTTreeBuilder.visit(JDTTreeBuilder.java:2706)
	at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.traverse(MethodDeclaration.java:327)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.traverse(TypeDeclaration.java:1415)
	at spoon.support.compiler.jdt.JDTTreeBuilder.visit(JDTTreeBuilder.java:2848)
	at org.eclipse.jdt.internal.compiler.ast.QualifiedAllocationExpression.traverse(QualifiedAllocationExpression.java:604)
	at spoon.support.compiler.jdt.JDTTreeBuilder.visit(JDTTreeBuilder.java:2122)
	at org.eclipse.jdt.internal.compiler.ast.Assignment.traverse(Assignment.java:262)
	at org.eclipse.jdt.internal.compiler.ast.Block.traverse(Block.java:139)
	at org.eclipse.jdt.internal.compiler.ast.SynchronizedStatement.traverse(SynchronizedStatement.java:212)
	at spoon.support.compiler.jdt.JDTTreeBuilder.visit(JDTTreeBuilder.java:2726)
	at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.traverse(MethodDeclaration.java:327)
	at spoon.support.compiler.jdt.JDTTreeBuilder.visit(JDTTreeBuilder.java:3459)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.traverse(TypeDeclaration.java:1319)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.traverse(CompilationUnitDeclaration.java:748)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.traverse(CompilationUnitDeclaration.java:709)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildSources(JDTBasedSpoonCompiler.java:228)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:481)
```

This code triggers the exception (I don't know which part exactly):

```Java
import example.B;

class A extends B {

    private Runnable runnable;

    public void foo() {
        synchronized (lock) {
           runnable = new Runnable() {

                @Override
                public void run() {

                }
            };
        }
    }
}
```

I tested it with Spoon 5.0.1 and 5.0.2.

**Comment by GerardPaligot** [comment]
Hi @worblehat,

Thanks for your report. PR done here: https://github.com/INRIA/spoon/pull/530.

**Comment by worblehat** [comment]
Thank you @GerardPaligot, this fix is crucial for me.

Building the model works with your PR. Unfortunately when calling `getReferencedTypes()` on the `CtType` of class `A` afterwards I get this:

```
Exception in thread "main" java.lang.NullPointerException
	at spoon.support.reflect.reference.CtReferenceImpl.setSimpleName(CtReferenceImpl.java:58)
	at spoon.reflect.factory.TypeFactory.createReference(TypeFactory.java:153)
	at spoon.support.reflect.declaration.CtTypeImpl.getReference(CtTypeImpl.java:268)
	at spoon.support.visitor.TypeReferenceScanner.visitCtClass(TypeReferenceScanner.java:167)
	at spoon.support.reflect.declaration.CtClassImpl.accept(CtClassImpl.java:58)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:147)
	at spoon.reflect.visitor.CtScanner.visitCtNewClass(CtScanner.java:543)
	at spoon.support.reflect.code.CtNewClassImpl.accept(CtNewClassImpl.java:30)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:147)
	at spoon.reflect.visitor.CtScanner.visitCtAssignment(CtScanner.java:258)
	at spoon.support.reflect.code.CtAssignmentImpl.accept(CtAssignmentImpl.java:48)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:147)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:136)
	at spoon.reflect.visitor.CtScanner.visitCtBlock(CtScanner.java:275)
	at spoon.support.reflect.code.CtBlockImpl.accept(CtBlockImpl.java:46)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:147)
	at spoon.reflect.visitor.CtScanner.visitCtSynchronized(CtScanner.java:634)
	at spoon.support.reflect.code.CtSynchronizedImpl.accept(CtSynchronizedImpl.java:33)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:147)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:136)
	at spoon.reflect.visitor.CtScanner.visitCtBlock(CtScanner.java:275)
	at spoon.support.reflect.code.CtBlockImpl.accept(CtBlockImpl.java:46)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:147)
	at spoon.reflect.visitor.CtScanner.visitCtMethod(CtScanner.java:510)
	at spoon.support.reflect.declaration.CtMethodImpl.accept(CtMethodImpl.java:58)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:147)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:136)
	at spoon.reflect.visitor.CtScanner.visitCtClass(CtScanner.java:311)
	at spoon.support.visitor.TypeReferenceScanner.visitCtClass(TypeReferenceScanner.java:171)
	at spoon.support.reflect.declaration.CtClassImpl.accept(CtClassImpl.java:58)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:147)
	at spoon.support.reflect.declaration.CtElementImpl.getReferencedTypes(CtElementImpl.java:293)
```

**Comment by GerardPaligot** [comment]
PR updated for this second error linked.

**Comment by worblehat** [comment]
Again: Thank you!

I just got a question here:
When running an `AbstractProcessor<CtMethod<?>>` on the example, it gets the method `run()`. Now I call `getDeclaringType().getQualifiedName()` on the `CtMethod`-object which returns `"A$"`. Is this correct? I would have expected something like `"A$1"`...

**Comment by GerardPaligot** [comment]
Yeah. Unfortunately, in no classpath, we don't have any data from JDT.

**Comment by worblehat** [comment]
Alright, I see.

**Comment by GerardPaligot** [comment]
@worblehat Note that I updated my PR to return `A$<unknown>` when we don't have the information.

**Comment by worblehat** [comment]
Okay, good to know :)
