### ISSUE TITLE
[Bug]: package-info incorrect processing

### ISSUE THREAD

**Issue by embraceddd** [INRIA/spoon#5357]
### Describe the bug

Attaching demo-project https://github.com/embraceddd/spoonpckinfobug
Quickstart for it:
[spoonpckinfobug](https://github.com/embraceddd/spoonpckinfobug/tree/master)/[src](https://github.com/embraceddd/spoonpckinfobug/tree/master/src)/[main](https://github.com/embraceddd/spoonpckinfobug/tree/master/src/main)/[resources](https://github.com/embraceddd/spoonpckinfobug/tree/master/src/main/resources)/[buggedProject](https://github.com/embraceddd/spoonpckinfobug/tree/master/src/main/resources/buggedProject)/[src](https://github.com/embraceddd/spoonpckinfobug/tree/master/src/main/resources/buggedProject/src)/[main](https://github.com/embraceddd/spoonpckinfobug/tree/master/src/main/resources/buggedProject/src/main)/[java](https://github.com/embraceddd/spoonpckinfobug/tree/master/src/main/resources/buggedProject/src/main/java)/[demo](https://github.com/embraceddd/spoonpckinfobug/tree/master/src/main/resources/buggedProject/src/main/java/demo)

There are two packages [notwork](https://github.com/embraceddd/spoonpckinfobug/tree/master/src/main/resources/buggedProject/src/main/java/demo/notwork) and [work](https://github.com/embraceddd/spoonpckinfobug/tree/master/src/main/resources/buggedProject/src/main/java/demo/work) that contains package-info files. Package-info file in package [work](https://github.com/embraceddd/spoonpckinfobug/tree/master/src/main/resources/buggedProject/src/main/java/demo/work) proccesing fine in all ways. 
For package-info file in package [notwork](https://github.com/embraceddd/spoonpckinfobug/tree/master/src/main/resources/buggedProject/src/main/java/demo/notwork) we can get different result depends on app dependencies and application startup method

1) If we **HAVE** jakarta-xml-bind dependency in our project and we will start app with shorten-command-line **_JARManifest_** method, app will fall down with JLSViolation.

2) If we **DON'T** have jakarta-xml-bind dependency in our project and we will start app with shorten-command-line **_JARManifest_** method, app will fall down with JLSViolation.

3) If we **HAVE** jakarta-xml-bind dependency in our project and we will start app with shorten-command-line **_ARGFILE_** method, app will successflyy process package-info file.

4) If we **DON'T** have jakarta-xml-bind dependency in our project and we will start app with shorten-command-line **_ARGFILE_** method, app will fall down with JLSViolation.

Difference at those two package-info files is how their importing XmlNsForm class. In not working package-info file we are importing it like `import javax.xml.bind.annotations.XmlNsForm`, in working package-info file we are inlineing import

How to start it on your machihe:
1)  Download repo https://github.com/embraceddd/spoonpckinfobug
2) Download dependencies via gradle
3) In [classpath](https://github.com/embraceddd/spoonpckinfobug/tree/master/classpathfile) directory we need to change ${PROJECT_PATH} and ${HOME} variables
Example for Windows: 
${HOME}\${PROJECT_PATH}\spoonpckinfobug\bin\main
${HOME} = C:\Users\user
${PROJECT_PATH} = ${HOME}\IdeaProjects
4) At [root directory](https://github.com/embraceddd/spoonpckinfobug/tree/master) there are 4 files named like start{Type}WithJakarta or start{Type}NoJakarta. Those file are command lines to start application from console, I used gitbash for example.

### Source code you are trying to analyze/transform

```Java
@javax.xml.bind.annotation.XmlSchema(namespace = "n", elementFormDefault = XmlNsForm.QUALIFIED)
package demo.notwork;

import javax.xml.bind.annotation.XmlNsForm;
```

### Source code for your Spoon processing

```Java
Launcher launcher = new Launcher();
            launcher.addInputResource(sourcePath);
            launcher.setSourceOutputDirectory(localPath.getAbsolutePath());
            launcher.getEnvironment().setNoClasspath(true);
            launcher.getEnvironment().setCopyResources(false);
            launcher.run();
```

### Actual output

```Java
Exception in thread "main" spoon.JLSViolation: Not allowed javaletter or keyword in identifier found. See JLS for correct identifier. Identifier: package-info
	at spoon.JLSViolation.throwIfSyntaxErrorsAreNotIgnored(JLSViolation.java:38)
	at spoon.support.reflect.reference.CtReferenceImpl.checkIdentifierForJLSCorrectness(CtReferenceImpl.java:114)
	at spoon.support.reflect.reference.CtReferenceImpl.setSimpleName(CtReferenceImpl.java:57)
	at spoon.support.compiler.jdt.ReferenceBuilder.getTypeReferenceFromSourceTypeBinding(ReferenceBuilder.java:1127)
	at spoon.support.compiler.jdt.ReferenceBuilder.getTypeReference(ReferenceBuilder.java:860)
	at spoon.support.compiler.jdt.ReferenceBuilder.getTypeReference(ReferenceBuilder.java:831)
	at spoon.support.compiler.jdt.ReferenceBuilder.getVariableReference(ReferenceBuilder.java:1261)
	at spoon.support.compiler.jdt.JDTTreeBuilderHelper.createFieldAccessNoClasspath(JDTTreeBuilderHelper.java:463)
	at spoon.support.compiler.jdt.JDTTreeBuilder.visit(JDTTreeBuilder.java:1529)
	at org.eclipse.jdt.internal.compiler.ast.QualifiedNameReference.traverse(QualifiedNameReference.java:1172)
	at org.eclipse.jdt.internal.compiler.ast.MemberValuePair.traverse(MemberValuePair.java:260)
	at org.eclipse.jdt.internal.compiler.ast.NormalAnnotation.traverse(NormalAnnotation.java:76)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.traverse(CompilationUnitDeclaration.java:810)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.traverse(CompilationUnitDeclaration.java:788)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.traverseUnitDeclaration(JDTBasedSpoonCompiler.java:481)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.lambda$buildModel$0(JDTBasedSpoonCompiler.java:438)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.forEachCompilationUnit(JDTBasedSpoonCompiler.java:465)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildModel(JDTBasedSpoonCompiler.java:436)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildUnitsAndModel(JDTBasedSpoonCompiler.java:373)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildSources(JDTBasedSpoonCompiler.java:336)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:117)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:100)
	at spoon.Launcher.buildModel(Launcher.java:782)
	at spoon.Launcher.run(Launcher.java:733)
	at ru.embraceddx.spoonpckinfobug.SpoonPreparator.buildModel(SpoonPreparator.java:21)
	at ru.embraceddx.spoonpckinfobug.SpoonpckinfobugApplication.main(SpoonpckinfobugApplication.java:13)
```

### Expected output

```Java
Success in all ways
```

### Spoon Version

10.4.0

### JVM Version

17.0.6

### What operating system are you using?

Windows 10
Also tried at MacOs Ventura and Linux Ubuntu and get same results

**Comment by hongxuchen** [comment]
We have recently encountered quite a few similar issues when using spoon. We sincerely hope this can be fixed as package-info is so widely used.

**Comment by axelrindle** [comment]
Did you figure this out?

**Comment by rishivijayv** [comment]
I was working on this issue and trying to recreate it locally using a unit-test (Spoon version was `11.2.1-SNAPSHOT` I believe), but I was unable to do so. I will document some of the steps I tried below.

Since `javax.xml.bind` was not a package available with the current set of dependencies in the project, I tried using package annotations that are already available in a `package-info.java` file. For example, I used the following: 

```java
@DefaultQualifier(NonNull.class)
package spoon.support.compiler.jdt.temptest;

import org.checkerframework.framework.qual.DefaultQualifier;
import org.jspecify.annotations.NonNull;
```
Note that here, for both the annotation and the argument passed to the annotation, I am _not_ using the fully qualified name -- the `imports` are separate.

I created a test case that then read the file in the specified path, launched it using the `Launcher`, and then retrieved the `CtModel`

```java
    @Test
    public void testSomething() {
        Launcher launcher = new Launcher();
        launcher.addInputResource("src/test/java/spoon/support/compiler/jdt/temptest/package-info.java");
        // Not specifying an output-directory using setSourceOutputDirectory, is that essential? 
        launcher.getEnvironment().setNoClasspath(true);
        launcher.getEnvironment().setCopyResources(false);
        launcher.run();
        CtModel model = launcher.getModel();
    }
```
Running `testSomething` then passes/does not throw any exception (tried both with/without `package-info.java` explicitly at the end of the source path). I tried using the `javax.xml.bind` annotation specified in the original post as well for good measure by explicitly adding a maven dependency -- `jaxb-api (v2.3.1)`, and changing my `package-info.java` file to the following:

```java
@javax.xml.bind.annotation.XmlSchema(namespace = "n", elementFormDefault = XmlNsForm.QUALIFIED)
package spoon.support.compiler.jdt.temptest;

import javax.xml.bind.annotation.XmlNsForm;
```
But still no exception is thrown. 


Based on this, a few questions/notes:

- **Is something incorrect with my setup here?** The `model` I receive at the end has quite a few `unnamed ...` in it (example below for `package-info.java` with the `javax.xml.bind` annotation, the other ones were similar IIRC), which makes me think I might be doing something wrong. Or has the issue been resolved? 
<img width="624" alt="Image" src="https://github.com/user-attachments/assets/d421ffa0-5d1b-4a96-aba1-3a6273d1b46c" />

- **I didn't try and clone and run the [example repository](https://github.com/embraceddd/spoonpckinfobug) mentioned in the original description to recreate the issue**. Instead using a unit-test that could be used to isolate the issue and verify that a fix works. I do see that the example-code uses [Spring boot](https://github.com/embraceddd/spoonpckinfobug/blob/master/src/main/java/ru/embraceddx/spoonpckinfobug/SpoonpckinfobugApplication.java) and some more involved ways of invoking the code (`ARGFILE`, `JARFILE`, etc). Could the interplay between these (Spring boot and Spoon) be the cause? If so, **is there a way to recreate this issue in the Spoon repo which allows for a unit test?**

Would appreciate your thoughts/help here whenever you get a chance 🙏🏽 ! @algomaster99 @I-Al-Istannen

**Comment by algomaster99** [comment]
@rishivijayv  I did not look deeply into this so I am replying to your highlighted question

> is there a way to recreate this issue in the Spoon repo which allows for a unit test?

A good start would be to have the above source code as a resource you could include the code for processing in the unit test. If the test passes, this bug is resolved. Else, there is still some work needed.

**Comment by rishivijayv** [comment]
@algomaster99 Hmm I _think_ that what I tried to do but failed to recreate the issue. I created a separate resource (a new package called `spoon.support.compiler.jdt.temptest` and a `package-info.java` file for it with annotations), and then tried to load the resource using the following code snippet: 
```java
    @Test
    public void testSomething() {
        Launcher launcher = new Launcher();
        // This is what I believe you mean by "including" a resource?
        launcher.addInputResource("src/test/java/spoon/support/compiler/jdt/temptest/package-info.java");
        // Not specifying an output-directory using setSourceOutputDirectory, is that essential? 
        launcher.getEnvironment().setNoClasspath(true);
        launcher.getEnvironment().setCopyResources(false);
        launcher.run();
        CtModel model = launcher.getModel();
    }
```
And **in this scenario I get no exceptions**, albeit with the `unknown ...` result in the final `model` object. Unless my understanding of a resource is wrong here? If not, is that enough for us to say that this issue isn't re-creatable/has been resolved? 🤔 

I did, however, observe one peculiar thing. I tried making the path to the resource garbage (to make sure it is loading something). 

When I have something like `src/test/java/spoon/support/compiler/jdt/vfvfdgfgdf/` (**no `package-info.java`), I still get no exceptions. But when I use something like `src/test/java/spoon/support/compiler/jdt/vfvfdgfgdf/package-info.java` I get a `FileNotFoundException`. Not sure if that means anything relevant here.

**Comment by monperrus** [comment]
closing per https://github.com/INRIA/spoon/pull/6183
