### ISSUE TITLE
[QUESTION]: How to include the jdk source code together with another applications src

### ISSUE THREAD

**Issue by Onter4791** [INRIA/spoon#5359]
Currently I'm using the Maven Launcher.

I currently use spoon to interproceduraly analyze pdfboxs issues describing null pointer exceptions to find their cause.
To do this I analze the dataflow along the stacktrace.
I also move into methods along this path in case they could be the cause for the null pointer exceptions.
Quite often I come along Collections from java.utils which i cannot analyze.

I included openjdk src as I got told by spoon by
"Type java.lang.StringBuffer is indirectly referenced from"
now I'm getting:
"The type java.lang.String is ambiguous at"
public GeneralPath getPath(String name) throws IOException

Anyone got an idea how to fix this?

**Spoon Version**
10.4.0

**JVM Version**
19
Src is 11

**What operating system are you using?**
Windows

**Comment by I-Al-Istannen** [comment]
Hey, can you share your setup? I can not reproduce any errors. I use a `launcher.addInputResource(new ZipFolder(new File(path)));` to add the JDK `src.zip` file and then `launcher.addInputResource("pdfbox/pdfbox/src/main/java")` to add the pdfbox sources.

**Comment by Onter4791** [comment]
I'm trying to anaylze jdk 11.19 because the maven build of pdfbox told me that it cannot use versions beyond 11

First it looked like this:

```
Launcher l = new MavenLauncher(pathToMavenProject, MavenLauncher.SOURCE_TYPE.ALL_SOURCE);
l.getEnvironment().setComplianceLevel(complianceLevel);
l.getEnvironment().setShouldCompile(false);
l.addInputResource(pathToMavenRepository);
l.addInputResource(pathToJDK_src)
```

pathToMavenProject := Top folder of pdfbox
pathToJDK_src := Top folder of openjdk src


Than i tried your suggestion and changed it to this:

```
Launcher l = new Launcher();
l.addInputResource(new ZipFolder(new File(pathToJDK_src)));
l.addInputResource(pathToMavenProject);
```

pathToJDK_src := zip file of jdk 11.19
pathToMavenProject := "../pdfbox/src/main/java"

Currently I'm getting the error:
```
Exception in thread "main" spoon.compiler.ModelBuildingException: The type C is already defined
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.reportProblem(JDTBasedSpoonCompiler.java:591)
	at spoon.support.compiler.jdt.TreeBuilderRequestor.acceptResult(TreeBuilderRequestor.java:29)
	at spoon.support.compiler.jdt.TreeBuilderCompiler.buildUnits(TreeBuilderCompiler.java:110)
	at spoon.support.compiler.jdt.JDTBatchCompiler.getUnits(JDTBatchCompiler.java:282)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildUnits(JDTBasedSpoonCompiler.java:418)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildUnitsAndModel(JDTBasedSpoonCompiler.java:370)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildSources(JDTBasedSpoonCompiler.java:336)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:117)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:100)
	at spoon.Launcher.buildModel(Launcher.java:782)
	at de.mydevtime.masterthesis.interproceduralnullanalyser.NullabilityChecker.main(NullabilityChecker.java:96)
```

**Comment by Onter4791** [comment]
OK I know now what i did wrong I used the github code.
But I should have used the src.zip from the platform specific build.
Could you guys maybe add this to the wiki under something like "How to add JDK src to your Spoon input ressources?"

**Comment by I-Al-Istannen** [comment]
I tried
```java
	@Test
	void foo() throws Exception {
		Launcher launcher = new Launcher();
		launcher.getEnvironment().setComplianceLevel(19);
		launcher.getEnvironment().setCommentEnabled(false);

		launcher.addInputResource(new ZipFolder(new File("/usr/lib/jvm/java-20-openjdk/lib/src.zip")));
		launcher.addInputResource("/tmp/pdfbox/pdfbox/src/main/java");

		launcher.buildModel();
		System.out.println(launcher.getFactory().Type().get("org.apache.pdfbox.util.Hex").toString().substring(0, 1000));
		System.out.println();
		System.out.println("==============================");
		System.out.println();
		System.out.println(launcher.getFactory().Type().get("java.lang.Integer").toString().substring(0, 1000));
	}

```
and that prints what I expect. Can you share a failing code sample?

**Comment by Onter4791** [comment]
Sry for the late reply.
It is working now for me as well as long as I don't try to import everything of the JDK src.
I was getting the jigsaw puzzle error.
Sadly I'm probably not allowed to use a not matching JDK cause it's my master thesis.

NullabilityChecker.java:81 -> l.buildModel();

### MyCode:
**Normal Launcher:**
```
Launcher l = new Launcher();
l.getEnvironment().setComplianceLevel(complianceLevel);
//l.addInputResource(new ZipFolder(new File(pathToJDK_src + ".zip")));
l.addInputResource(pathToJDK_src + "/java.base");
l.addInputResource(pathToJDK_src + "/java.desktop");
l.addInputResource(pathToJDK_src + "/java.xml");
l.addInputResource(pathToJDK_src + "/jdk.crypto.mscapi");
```

**Maven Launcher:**
```
Launcher l = new MavenLauncher(pathToMavenProject, MavenLauncher.SOURCE_TYPE.ALL_SOURCE);
l.getEnvironment().setComplianceLevel(complianceLevel);
//l.addInputResource(new ZipFolder(new File("C:\\Users\\Benedikt Papiorek\\Downloads\\src.zip")));
l.addInputResource(pathToJDK_src + "/java.base");
l.addInputResource(pathToJDK_src + "/java.desktop");
l.addInputResource(pathToJDK_src + "/java.xml");
l.addInputResource(pathToJDK_src + "/jdk.crypto.mscapi");
```

### Errors with MavenLauncher:
- If i'm only importing the **folders I need**:
```
Exception in thread "main" spoon.compiler.ModelBuildingException: The method orElse(Class<capture#397-of ?>) in the type Optional<Class<capture#397-of ?>> is not applicable for the arguments (Class<Void>) at C:\Users\Benedikt Papiorek\Downloads\src\java.base\java\lang\invoke\MethodHandles.java:4875
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.report(JDTBasedSpoonCompiler.java:640)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.reportProblems(JDTBasedSpoonCompiler.java:622)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:119)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:100)
	at spoon.Launcher.buildModel(Launcher.java:782)
	at de.mydevtime.masterthesis.interproceduralnullanalyser.NullabilityChecker.main(NullabilityChecker.java:81)
```
- If I'm trying to import the **src.zip**:
```
Exception in thread "main" spoon.compiler.ModelBuildingException: The package jdk.swing.interop does not exist or is empty at C:\Users\BENEDI~1\AppData\Local\Temp\spoon-zip-file-proxy833507772777571221\jdk.unsupported.desktop\module-info.java:35
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.report(JDTBasedSpoonCompiler.java:640)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.reportProblems(JDTBasedSpoonCompiler.java:622)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:119)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:100)
	at spoon.Launcher.buildModel(Launcher.java:782)
	at de.mydevtime.masterthesis.interproceduralnullanalyser.NullabilityChecker.main(NullabilityChecker.java:81)
```
### Error with normal Launcher:
Importing the src.zip:
```
Exception in thread "main" spoon.SpoonException: Ambiguous package name detected. If you believe the code you analyzed is correct, please file an issue and reference https://github.com/INRIA/spoon/issues/4051. Error details: Found 2 non-empty packages with name 'org.graalvm.compiler.hotspot.replacements'
	at spoon.reflect.factory.PackageFactory.get(PackageFactory.java:188)
	at spoon.support.reflect.reference.CtPackageReferenceImpl.getDeclaration(CtPackageReferenceImpl.java:24)
	at spoon.support.reflect.declaration.CtCompilationUnitImpl.getDeclaredPackage(CtCompilationUnitImpl.java:230)
	at spoon.support.compiler.jdt.ReferenceBuilder.setPackageOrDeclaringType(ReferenceBuilder.java:1293)
	at spoon.support.compiler.jdt.ReferenceBuilder.getTypeReference(ReferenceBuilder.java:790)
	at spoon.support.compiler.jdt.ReferenceBuilder.getTypeReference(ReferenceBuilder.java:723)
	at spoon.support.compiler.jdt.ReferenceBuilder.getTypeReference(ReferenceBuilder.java:602)
	at spoon.support.compiler.jdt.ReferenceBuilder.getExecutableReference(ReferenceBuilder.java:490)
	at spoon.support.compiler.jdt.JDTTreeBuilder.visit(JDTTreeBuilder.java:880)
	at org.eclipse.jdt.internal.compiler.ast.AllocationExpression.traverse(AllocationExpression.java:716)
	at org.eclipse.jdt.internal.compiler.ast.FieldDeclaration.traverse(FieldDeclaration.java:381)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.traverse(TypeDeclaration.java:1693)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.traverse(CompilationUnitDeclaration.java:827)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.traverse(CompilationUnitDeclaration.java:788)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.traverseUnitDeclaration(JDTBasedSpoonCompiler.java:481)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.lambda$buildModel$0(JDTBasedSpoonCompiler.java:438)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.forEachCompilationUnit(JDTBasedSpoonCompiler.java:465)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildModel(JDTBasedSpoonCompiler.java:436)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildUnitsAndModel(JDTBasedSpoonCompiler.java:373)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildSources(JDTBasedSpoonCompiler.java:336)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:117)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:100)
	at spoon.Launcher.buildModel(Launcher.java:782)
	at de.mydevtime.masterthesis.interproceduralnullanalyser.NullabilityChecker.main(NullabilityChecker.java:81)
```
