### ISSUE TITLE
Processor<CtClass> does not work when analyzing the source code under "java.awt" in JDK

### ISSUE THREAD

**Issue by giphon** [INRIA/spoon#546]
When I analyze the source code of JDK under packages like "java.math" or "java.io", Spoon works well. 
But when I try the source code under the package "java.awt", a Null Pointer exception is thrown (see the bottom). 

The processor is an empty processor, which can be found below. 
It seems the exception is thrown before analyzing any class (before running isToBeProcessed(), if any). 
The source code of "java.awt.*" can be found in "src.zip" under the path of JDK.  

The versions that I used: Debian 7.5, Oracle JDK 1.7.0_80, spoon spoon-core-4.4.1-jar-with-dependencies.jar, from Linux shell. 

Thanks. 

======
/* Processor */
package cn.edu;
import spoon.processing.AbstractProcessor;
import spoon.reflect.declaration.CtClass;

public class SqmProcessor extends AbstractProcessor<CtClass> 
{
  @Override
  public void process(CtClass ctClass) 
  {  }
}
======
java.lang.NullPointerException
	at spoon.support.compiler.jdt.JDTTreeBuilder.createType(JDTTreeBuilder.java:972)
	at spoon.support.compiler.jdt.JDTTreeBuilder.visit(JDTTreeBuilder.java:3035)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.traverse(TypeDeclaration.java:1430)
	at spoon.support.compiler.jdt.JDTTreeBuilder.visit(JDTTreeBuilder.java:3078)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.traverse(TypeDeclaration.java:1319)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.traverse(CompilationUnitDeclaration.java:748)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.traverse(CompilationUnitDeclaration.java:709)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildSources(JDTBasedSpoonCompiler.java:227)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:480)
	at spoon.Launcher.buildModel(Launcher.java:664)
	at spoon.Launcher.run(Launcher.java:616)
	...

**Comment by GerardPaligot** [comment]
Hi @giphon,

Can you give us a snippet with your awt package usage? And/Or test it with the latest version of Spoon 5.0.2? (snapshot 5.1.0 is even better!)

**Comment by monperrus** [comment]
Hi Jjifeng,

Seems fixed in the latest SNAPSHOT version, could you try again with
http://spoon.gforge.inria.fr/repositories/snapshots/fr/inria/gforge/spoon/spoon-core/5.1.0-SNAPSHOT/spoon-core-5.1.0-20160229.005436-14-jar-with-dependencies.jar
?

--Martin

**Comment by GerardPaligot** [comment]
Spoon 5.1.0 can be applied to the src.zip file. So I close this issue.
