### ISSUE TITLE
[Bug]: A null pointer exception occurred in build model

### ISSUE THREAD

**Issue by honghao12** [INRIA/spoon#5579]
### Describe the bug

A null pointer exception occurred in build model

### Source code you are trying to analyze/transform

```Java
.
```

### Source code for your Spoon processing

```Java
Launcher launcher = new Launcher();
        launcher.getEnvironment().setComplianceLevel(11);
        launcher.getEnvironment().setAutoImports(true);
        launcher.getEnvironment().setIgnoreDuplicateDeclarations(true);
        launcher.addInputResource(filteringFolder);
        launcher.run();
```

### Actual output

```Java
null
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: java.lang.NullPointerException
	at spoon.support.compiler.jdt.ReferenceBuilder.isIncorrectlyBoundExecutableInNoClasspath(ReferenceBuilder.java:527)
	at spoon.support.compiler.jdt.ReferenceBuilder.getExecutableReference(ReferenceBuilder.java:495)
	at spoon.support.compiler.jdt.JDTTreeBuilder.visit(JDTTreeBuilder.java:880)
	at org.eclipse.jdt.internal.compiler.ast.AllocationExpression.traverse(AllocationExpression.java:716)
	at org.eclipse.jdt.internal.compiler.ast.Assignment.traverse(Assignment.java:274)
	at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.traverse(MethodDeclaration.java:437)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.traverse(TypeDeclaration.java:1702)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.traverse(CompilationUnitDeclaration.java:827)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.traverse(CompilationUnitDeclaration.java:788)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.traverseUnitDeclaration(JDTBasedSpoonCompiler.java:481)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.lambda$buildModel$0(JDTBasedSpoonCompiler.java:438)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.forEachCompilationUnit(JDTBasedSpoonCompiler.java:465)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildModel(JDTBasedSpoonCompiler.java:436)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildUnitsAndModel(JDTBasedSpoonCompiler.java:373)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildSources(JDTBasedSpoonCompiler.java:336)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:117)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:100)
	at spoon.Launcher.buildModel(Launcher.java:781)
	at com.huawei.tenet.jymbol.spoon.service.SpoonParser.buildModel(SpoonParser.java:33)
	at com.huawei.tenet.jymbol.spoon.service.AbstractSpoonParser.parse(AbstractSpoonParser.java:51)
	at com.huawei.tenet.jymbol.console.Jymbol.run(Jymbol.java:172)
	at com.huawei.tenet.jymbol.console.Main.main(Main.java:45)
	... 8 more
```

### Expected output

```Java
.
```

### Spoon Version

10.4.3-beta-2

### JVM Version

11

### What operating system are you using?

linux

**Comment by tenax66** [comment]
Can you provide more information about `filteringFolder`? 
I would like to see an example of a target code that reproduces the problem.

**Comment by ganeshs** [comment]
I'm seeing a similar issue in setNoClasspath(true) mode.

Sample code for which it fails. 

`public enum BureauDetailFields {

    CREDIT_DETAILS((bureauDetailBuilder, attributeValue) -> {
        CreditScoreAttributeEntry creditScoreAttributeEntry = (CreditScoreAttributeEntry) attributeValue;
        bureauDetailBuilder.aggregatedScore(creditScoreAttributeEntry.getAggregatedScore());
        bureauDetailBuilder.creditScores(creditScoreAttributeEntry.getCreditScores());
        return bureauDetailBuilder;
    }),

    private BiFunction<BureauDetail.BureauDetailBuilder, AttributeValue, BureauDetail.BureauDetailBuilder> bureauDetailBuilderInstance;

    BureauDetailFields(BiFunction<BureauDetail.BureauDetailBuilder, AttributeValue, BureauDetail.BureauDetailBuilder> bureauDetailBuilderInstance) {
        this.bureauDetailBuilderInstance = bureauDetailBuilderInstance;
    }

    public BiFunction<BureauDetail.BureauDetailBuilder, AttributeValue, BureauDetail.BureauDetailBuilder> getBureauDetailBuilderInstance() {
        return bureauDetailBuilderInstance;
    }
}`
