### ISSUE TITLE
Error when importing `spoon.reflect.declaration.CtTypeParameter` with v5.1.0

### ISSUE THREAD

**Issue by lepieru** [INRIA/spoon#567]
When I import `spoon.reflect.declaration.CtTypeParameter` with Spoon version 5.1.0 like below:

```java
import spoon.reflect.internal.CtCircularTypeReference;
```

It fails with:

```
Exception in thread "main" spoon.compiler.ModelBuildingException: The import spoon.reflect.declaration.CtTypeParameter cannot be resolved at /path/to/source.java:line
        at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.report(JDTBasedSpoonCompiler.java:650)
        at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.reportProblems(JDTBasedSpoonCompiler.java:631)
        at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:126)
        at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:107)
        at spoon.Launcher.buildModel(Launcher.java:682)
        at spoon.Launcher.run(Launcher.java:634)
        at spoon.Launcher.run(Launcher.java:100)
        at spoon.Launcher.main(Launcher.java:93)
```

I am using the `spoon-core-5.1.0-jar-with-dependencies.jar` and using `spoon-core-5.0.2-jar-with-dependencies.jar` instead solved my problem.

**Comment by GerardPaligot** [comment]
`CtTypeParameter` has been deleted in the version 5.1.0. and replaced by `CtTypeParameterReference`.
