### ISSUE TITLE
Error in FieldAccessFilter

### ISSUE THREAD

**Issue by mehdijk** [INRIA/spoon#639]
Hi
I work on HSQLDB 1.8.0.9 and make a Spoon model. When I try to get elements by a field filter, it makes `NullPointerException` error.
I use this command: `List<CtFieldAccess<?>>  fieldAccessList = rootPack.getElements(new FieldAccessFilter(ctField.getReference()));`
and the trace of stack is as follows:
`java.lang.NullPointerException
	at spoon.reflect.visitor.filter.VariableAccessFilter.matches(VariableAccessFilter.java:41)
	at spoon.reflect.visitor.filter.VariableAccessFilter.matches(VariableAccessFilter.java:26)
	at spoon.reflect.visitor.QueryVisitor.scan(QueryVisitor.java:58)
	at spoon.reflect.visitor.CtScanner.visitCtInvocation(CtScanner.java:483)
	at spoon.support.reflect.code.CtInvocationImpl.accept(CtInvocationImpl.java:48)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:146)
	at spoon.reflect.visitor.QueryVisitor.scan(QueryVisitor.java:67)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:135)
	at spoon.reflect.visitor.CtScanner.visitCtBlock(CtScanner.java:280)
	at spoon.support.reflect.code.CtBlockImpl.accept(CtBlockImpl.java:46)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:146)
	at spoon.reflect.visitor.QueryVisitor.scan(QueryVisitor.java:67)
	at spoon.reflect.visitor.CtScanner.visitCtMethod(CtScanner.java:539)
	at spoon.support.reflect.declaration.CtMethodImpl.accept(CtMethodImpl.java:60)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:146)
	at spoon.reflect.visitor.QueryVisitor.scan(QueryVisitor.java:67)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:135)
	at spoon.reflect.visitor.CtScanner.visitCtClass(CtScanner.java:320)
	at spoon.support.reflect.declaration.CtClassImpl.accept(CtClassImpl.java:58)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:146)
	at spoon.reflect.visitor.QueryVisitor.scan(QueryVisitor.java:67)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:135)
	at spoon.reflect.visitor.CtScanner.visitCtPackage(CtScanner.java:620)
	at spoon.support.reflect.declaration.CtPackageImpl.accept(CtPackageImpl.java:48)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:146)
	at spoon.reflect.visitor.QueryVisitor.scan(QueryVisitor.java:67)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:135)
	at spoon.reflect.visitor.CtScanner.visitCtPackage(CtScanner.java:619)
	at spoon.support.reflect.declaration.CtPackageImpl.accept(CtPackageImpl.java:48)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:146)
	at spoon.reflect.visitor.QueryVisitor.scan(QueryVisitor.java:67)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:135)
	at spoon.reflect.visitor.CtScanner.visitCtPackage(CtScanner.java:619)
	at spoon.support.reflect.declaration.CtPackageImpl.accept(CtPackageImpl.java:48)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:146)
	at spoon.reflect.visitor.QueryVisitor.scan(QueryVisitor.java:67)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:135)
	at spoon.reflect.visitor.CtScanner.visitCtPackage(CtScanner.java:619)
	at spoon.support.reflect.declaration.CtPackageImpl.accept(CtPackageImpl.java:48)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:146)
	at spoon.reflect.visitor.QueryVisitor.scan(QueryVisitor.java:67)
	at spoon.reflect.visitor.Query.getElements(Query.java:70)
	at spoon.support.reflect.declaration.CtElementImpl.getElements(CtElementImpl.java:345)`

**Comment by tdurieux** [comment]
Did you check: `ctField.getReference() != null` ?

**Comment by mehdijk** [comment]
Yes, I check. It is not `null`
