### ISSUE TITLE
Add statement and import

### ISSUE THREAD

**Issue by dima74** [INRIA/spoon#663]
Hello, thank you for Spoon! I have a problem, could you help me, please. There are two files in my project, Main.java and Test.java:
```
package com.example;

public class Test {
	public Test() {
		System.out.println("Test");
	}
}
```
```
public class Main {
	public static void main(String[] args) {
		System.out.println("Hello!");
		// I want to add this line and import
		// new Test();
		// I don't want line like this:
		// new com.example.Test();
	}
}
```
I tried several processors.
1) With `compileAndReplaceSnippets()` method in CtClass
```
import spoon.processing.AbstractManualProcessor;
import spoon.reflect.code.CtCodeSnippetStatement;
import spoon.reflect.declaration.CtClass;

public class Processor extends AbstractManualProcessor {
    public void process() {
        CtClass<Object> ctClass = getFactory().Class().get("Main");
        CtCodeSnippetStatement ctStatement = getFactory().Code().createCodeSnippetStatement("new com.example.Test()");
        ctClass.getMethodsByName("main").get(0).getBody().addStatement(ctStatement);
        ctClass.compileAndReplaceSnippets(); // !!!
    }
}
```
This gives me a `spoon.compiler.ModelBuildingException`
```
Exception in thread "main" spoon.compiler.ModelBuildingException: snippet compilation error while compiling: class Main {
    public static void main(java.lang.String[] args) {
        java.lang.System.out.println("Hello!");
        new com.example.Test();
    }
}
	at spoon.support.compiler.SnippetCompilationHelper.build(SnippetCompilationHelper.java:109)
	at spoon.support.compiler.SnippetCompilationHelper.compileAndReplaceSnippetsIn(SnippetCompilationHelper.java:54)
	at spoon.support.reflect.declaration.CtTypeImpl.compileAndReplaceSnippets(CtTypeImpl.java:295)
	at Processor.process(Processor.java:10)
	at spoon.support.QueueProcessingManager.process(QueueProcessingManager.java:131)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.instantiateAndProcess(JDTBasedSpoonCompiler.java:224)
	at spoon.Launcher.process(Launcher.java:689)
	at spoon.Launcher.run(Launcher.java:636)
	at spoon.Launcher.run(Launcher.java:100)
	at spoon.Launcher.main(Launcher.java:93)
Caused by: spoon.support.compiler.SnippetCompilationError
	at spoon.support.compiler.jdt.JDTSnippetCompiler.report(JDTSnippetCompiler.java:105)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.reportProblems(JDTBasedSpoonCompiler.java:631)
	at spoon.support.compiler.jdt.JDTSnippetCompiler.build(JDTSnippetCompiler.java:59)
	at spoon.support.compiler.jdt.JDTSnippetCompiler.build(JDTSnippetCompiler.java:45)
	at spoon.support.compiler.SnippetCompilationHelper.build(SnippetCompilationHelper.java:107)
	... 9 more
```
2) Then I tried `compile()` method in CtStatement:
```
import spoon.processing.AbstractManualProcessor;
import spoon.reflect.code.CtCodeSnippetStatement;
import spoon.reflect.declaration.CtClass;

public class Processor extends AbstractManualProcessor {
    public void process() {
        CtClass<Object> ctClass = getFactory().Class().get("Main");
        CtCodeSnippetStatement ctStatement = getFactory().Code().createCodeSnippetStatement("new com.example.Test()");
        ctStatement = ctStatement.compile(); // !!!
        ctClass.getMethodsByName("main").get(0).getBody().addStatement(ctStatement);
    }
}
```
This also gives me a `spoon.compiler.ModelBuildingException`
```
Exception in thread "main" spoon.compiler.ModelBuildingException: snippet compilation error while compiling: class Wrapper {
    void wrap() {
        new com.example.Test();
    }
}
	at spoon.support.compiler.SnippetCompilationHelper.build(SnippetCompilationHelper.java:109)
	at spoon.support.compiler.SnippetCompilationHelper.build(SnippetCompilationHelper.java:100)
	at spoon.support.compiler.SnippetCompilationHelper.internalCompileStatement(SnippetCompilationHelper.java:71)
	at spoon.support.compiler.SnippetCompilationHelper.compileStatement(SnippetCompilationHelper.java:63)
	at spoon.support.reflect.code.CtCodeSnippetStatementImpl.compile(CtCodeSnippetStatementImpl.java:48)
	at Processor.process(Processor.java:9)
	at spoon.support.QueueProcessingManager.process(QueueProcessingManager.java:131)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.instantiateAndProcess(JDTBasedSpoonCompiler.java:224)
	at spoon.Launcher.process(Launcher.java:689)
	at spoon.Launcher.run(Launcher.java:636)
	at spoon.Launcher.run(Launcher.java:100)
	at spoon.Launcher.main(Launcher.java:93)
Caused by: spoon.support.compiler.SnippetCompilationError
	at spoon.support.compiler.jdt.JDTSnippetCompiler.report(JDTSnippetCompiler.java:105)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.reportProblems(JDTBasedSpoonCompiler.java:631)
	at spoon.support.compiler.jdt.JDTSnippetCompiler.build(JDTSnippetCompiler.java:59)
	at spoon.support.compiler.jdt.JDTSnippetCompiler.build(JDTSnippetCompiler.java:45)
	at spoon.support.compiler.SnippetCompilationHelper.build(SnippetCompilationHelper.java:107)
	... 11 more
```
3) Also I tried to add imports manually with `setManualImports` method in CompilationUnitImpl:
```
import com.example.Test;
import spoon.processing.AbstractManualProcessor;
import spoon.reflect.code.CtCodeSnippetStatement;
import spoon.reflect.cu.CompilationUnit;
import spoon.reflect.cu.Import;
import spoon.reflect.declaration.CtClass;
import spoon.reflect.reference.CtTypeReference;
import spoon.support.reflect.cu.CompilationUnitImpl;

import java.util.Arrays;
import java.util.HashSet;

public class Processor3 extends AbstractManualProcessor {
    public void process() {
        CtClass<Object> ctClass = getFactory().Class().get("Main");
        CtCodeSnippetStatement ctStatement = getFactory().Code().createCodeSnippetStatement("new Test()"); // without com.example.
        ctClass.getMethodsByName("main").get(0).getBody().addStatement(ctStatement);
        
        // !!!
        CompilationUnit compilationUnit = getFactory().CompilationUnit().getMap().get("/home/dima/IdeaProjects/SpoonTestConsole new/src/Main.java");
        CtTypeReference ctTypeReference = getFactory().Code().createCtTypeReference(Test.class);
        HashSet<Import> imports = new HashSet<>(Arrays.asList(getFactory().CompilationUnit().createImport(ctTypeReference)));
        ((CompilationUnitImpl) compilationUnit).setManualImports(imports);
    }
}
```
This gived me no error, but import didn't add, so javac can't compile resulting code.
I also tried to add --precompile option but there were many errors, it looks like that when I used --precompile option spoon precomplies all java files in all subfolders, not only in folder given with -i argument. So my general question is how to change third processor to get that I want? Thank you!

**Comment by GerardPaligot** [comment]
Hi @dima74,

When you got this kind of error: `spoon.compiler.ModelBuildingException`, it means that you don't have all classes in your Spoon source path. In your case, `Test` isn't in your Spoon source path.

Can you give us your `Launcher` usage?

**Comment by dima74** [comment]
Hi @GerardPaligot,

My project structure is this:
![image](https://cloud.githubusercontent.com/assets/6505554/15321573/0d3b4772-1c40-11e6-8f01-41767f1dc2ee.png)
Here is my script:
```
javac -d bin-processors -cp spoon-core-5.1.0-jar-with-dependencies.jar ./src-processors/Processor1.java
java -classpath bin-processors:spoon-core-5.1.0-jar-with-dependencies.jar spoon.Launcher -i src -p Processor1
```

All files:
[SpoonTestConsole.zip](https://github.com/INRIA/spoon/files/268087/SpoonTestConsole.zip)

**Comment by tdurieux** [comment]
The JDTSnippetCompiler does not seem to add the classes of the parent factory (here all classes available in src) into the classpath:
https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/support/compiler/jdt/JDTSnippetCompiler.java#L74

**Comment by GerardPaligot** [comment]
Yes, `JDTSnippetCompiler` hasn't been designed to compile sources with dependencies. We should have a mechanism to add a "context" in a snippet compilation but this is a big work.

**Comment by dima74** [comment]
OK, maybe it is possible to somehow change third variant to working version? (With adding imports manually)

**Comment by GerardPaligot** [comment]
You can add imports in Spoon but the compilation is made by JDT (eclipse compiler). If JDT doesn't have a complete source classpath, it detects compilation errors.

I'm working on a workflow.

**Comment by tdurieux** [comment]
I easiest way is compile the content of `src` and adds the class to the classpath.

ex:
``` bash
javac -d bin-source -cp ? ./src/**/*.java
java -classpath bin-source:bin-processors:spoon-core-5.1.0-jar-with-dependencies.jar spoon.Launcher -i src -p Processor1
```

**Comment by dima74** [comment]
@GerardPaligot,
If i want to add imports (i.e. simple line `import com.example.Test;` to transformed file Main.java), without compilation, how can i do it?

**Comment by tdurieux** [comment]
The imports are automatically handled by Spoon, there is no list of import in spoon.

`factory.getEnvironment().setAutoImports(true);` this command will ask spoon to use imports instead of full qualified name.

This code snippet can help you to create a constructor call instead of using the snippets.
```java
CtTypeReference reference = factory.Type().get("class.name.A").getReference();
CtConstructorCall constructorCall = factory.Code().createConstructorCall(reference);
constructorCall.toString() // new class.name.A();
factory.getEnvironment().setAutoImports(true);
constructorCall.toString() // import class.name; new A();
```

**Comment by dima74** [comment]
@tdurieux,
Thank you, in this case it is the best solution, but in real cases I usually want to add something with if statement: 
```
if (<condition>) {
    Test test = new Test();
    ...
}
```
I couldn't find how I can add if statement, maybe I missing something?

**Comment by tdurieux** [comment]
It's really painful to create an if manually,
```java
CtIf anIf = factory.Core().createIf();

CtExpression left = factory.Code().createVariableRead(null, false);
CtExpression right = factory.Code().createLiteral(null);
CtBinaryOperator binaryOperator = factory.Code().createBinaryOperator(left, right, BinaryOperatorKind.EQ);
anIf.setCondition(binaryOperator);

CtBlock block = factory.Core().createBlock();
anIf.setThenStatement(block);
block.addStatement(constructorCall);
```

**Comment by dima74** [comment]
That is exactly what I wanted! Thank you, now it is no need to add imports manually.

**Comment by GerardPaligot** [comment]
@dima74 We can close?

**Comment by dima74** [comment]
Yes, I'm just a newbie on github))
