### ISSUE TITLE
Bug on build : "Build failed (argumentTypes)"

### ISSUE THREAD

**Issue by MehdiAit** [INRIA/spoon#732]
Hi,
I'm trying to use Spoon with an Android project. I correctly set up my build.gradle with my spoon processor and all the necessary dependency. However, I can't build my project. When I get my gradle stack trace I have this :
<pre>
Caused by: java.lang.NoSuchFieldError: argumentTypes
	at spoon.support.compiler.jdt.JDTTreeBuilder.buildCommonPartForCtNewClassAndCtConstructorCall(JDTTreeBuilder.java:2202)
	at spoon.support.compiler.jdt.JDTTreeBuilder.visit(JDTTreeBuilder.java:2187)
	at org.eclipse.jdt.internal.compiler.ast.AllocationExpression.traverse(AllocationExpression.java:657)
	at spoon.support.compiler.jdt.JDTTreeBuilder.visit(JDTTreeBuilder.java:2447)
	at org.eclipse.jdt.internal.compiler.ast.Assignment.traverse(Assignment.java:258)
	at spoon.support.compiler.jdt.JDTTreeBuilder.visit(JDTTreeBuilder.java:3129)
	at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.traverse(MethodDeclaration.java:317)
	at spoon.support.compiler.jdt.JDTTreeBuilder.visit(JDTTreeBuilder.java:3855)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.traverse(TypeDeclaration.java:1338)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.traverse(CompilationUnitDeclaration.java:748)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.traverse(CompilationUnitDeclaration.java:709)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildSources(JDTBasedSpoonCompiler.java:436)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:124)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:107)
	at spoon.SpoonModelBuilder$build$2.call(Unknown Source)
	at fr.inria.gforge.spoon.SpoonAndroidTask.run(SpoonAndroidTask.groovy:49)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:226)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:219)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:208)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:589)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:572)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
</pre>

Thank you beforehand.

**Comment by GerardPaligot** [comment]
Your error is weird... Can you confirm me that you use the last version of the Gradle plugin with the latest release version of Spoon?

**Comment by MehdiAit** [comment]
Hi,
I'm using Spoon 5.1.1 version and for Spoon-gradle-plugin I'm using the version 1.0-SNAPSHOT

**Comment by GerardPaligot** [comment]
Can you test with the last release Spoon 5.2.0?

**Comment by MehdiAit** [comment]
Hi @GerardPaligot ,

Sorry for my late reply, currently I'm using Spoon 5.2 version. I also have the same erreur. However, for the moment I'm using spoon locally without gradle to run my processor (urgent). It work correctly but I have noticed some bugs so I think I will open another issue to repot them all.
I will certainly retry to use Spoon with gradle in the next months.

Thank you for your help.
