### ISSUE TITLE
java.lang.ClassCastException: spoon.support.reflect.declaration.CtAnonymousExecutableImpl cannot be cast to spoon.reflect.declaration.CtConstructor

### ISSUE THREAD

**Issue by arnobl** [INRIA/spoon#739]
Me, again.

Using 5.2.0, I got a:
```
Caused by: java.lang.ClassCastException: spoon.support.reflect.declaration.CtAnonymousExecutableImpl cannot be cast to spoon.reflect.declaration.CtConstructor
	at spoon.reflect.factory.ExecutableFactory.createReference(ExecutableFactory.java:109)
	at spoon.support.reflect.declaration.CtExecutableImpl.getReference(CtExecutableImpl.java:145)
```

when parsing the following code:

```
class Foo {
	static {
		System.out.println("fooo");
	}
}
```

A test case to reproduce the exception:

```
public void testSpoon() {
		final spoon.Launcher launcher = new spoon.Launcher();
		launcher.addInputResource("src/test/resources/java/Foo.java");
		launcher.getEnvironment().setNoClasspath(true);
		launcher.getEnvironment().setComplianceLevel(8);
		launcher.buildModel();

		launcher.getModel().getElements(new TypeFilter<CtExecutable<?>>(CtExecutable.class) {
			@Override
			public boolean matches(final CtExecutable<?> exec) {
				try {
					System.out.println(exec.getReference());
				}catch(ClassCastException ex) {
					fail();
				}

				return super.matches(exec);
			}
		});
	}
```

**Comment by GerardPaligot** [comment]
Thanks for the report. PR done.
