### ISSUE TITLE
ClassCastException when replacing CtBlock

### ISSUE THREAD

**Issue by fedorov-s-n** [INRIA/spoon#792]
Stacktrace:

	java.lang.ClassCastException: spoon.support.reflect.code.CtTryImpl cannot be cast to spoon.reflect.code.CtStatementList
		at spoon.support.reflect.code.CtStatementImpl.replace(CtStatementImpl.java:50)
		at spoon.support.reflect.code.CtStatementImpl.replace(CtStatementImpl.java:275)
		at spoon.support.reflect.code.CtBlockImpl.replace(CtBlockImpl.java:217)

How to reproduce:
Create try-catch and then

    ctTry.getBody().replace(<smth>)

Spoon version is 5.2.0

**Comment by monperrus** [comment]
seems related to #683
