### ISSUE TITLE
spoon.compiler.ModelBuildingException: The type $ is already defined for DropWizard project

### ISSUE THREAD

**Issue by rajithd-aurea** [INRIA/spoon#869]
I'm getting following error when try to analyze dropwizard (https://github.com/dropwizard/dropwizard) code in spoon.
``` 
Exception in thread "main" spoon.compiler.ModelBuildingException: The type $ is already defined
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.reportProblem(JDTBasedSpoonCompiler.java:391)
	at spoon.support.compiler.jdt.TreeBuilderRequestor.acceptResult(TreeBuilderRequestor.java:21)
	at spoon.support.compiler.jdt.TreeBuilderCompiler.buildUnits(TreeBuilderCompiler.java:56)
	at spoon.support.compiler.jdt.JDTBatchCompiler.getUnits(JDTBatchCompiler.java:121)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildSources(JDTBasedSpoonCompiler.java:222)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:480)
	at spoon.Launcher.buildModel(Launcher.java:664)
	at spoon.Launcher.run(Launcher.java:616)
	at com.devfactory.runner.SpoonClassLoader.load(SpoonClassLoader.java:24)
	at com.devfactory.runner.WeakTestRunner.main(WeakTestRunner.java:164) 
```

This is the class loader code
```java
SpoonAPI spoon = new Launcher();
spoon.addInputResource(sourceDirectory);
spoon.getEnvironment().setNoClasspath(true);
spoon.run();
```
Is this  a bug or am I doing something wrong ?

**Comment by monperrus** [comment]
Could you attach the  files in sourceDirectory?

**Comment by rajithd-aurea** [comment]
@monperrus 
I clone this repo - https://github.com/dropwizard/dropwizard
and gave /path/to/dropwizard/ as the sourceDirectory

**Comment by rajithd-aurea** [comment]
Additional Information
--------------------------
O/S - Macos
Java version - 8
spoon core version - 5.3.0
```
<dependency>
            <groupId>fr.inria.gforge.spoon</groupId>
            <artifactId>spoon-core</artifactId>
            <version>5.3.0</version>
            <exclusions>
                <exclusion>
                    <artifactId>commons-io</artifactId>
                    <groupId>commons-io</groupId>
                </exclusion>
            </exclusions>
        </dependency>
```

**Comment by danglotb** [comment]
Hello @rajithd-aurea 

It seems like you are trying to spoon some template files.
In the project dropwizard, there is some of this kind of file:
```java
package ${package};

import io.dropwizard.Configuration;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.hibernate.validator.constraints.*;
import javax.validation.constraints.*;

public class ${name}Configuration extends Configuration {
    // TODO: implement service configuration
}
```
We can not spoon such files because they are not valid java files until they are processed properly (replace ${package} and ${name} by real values)

If you want to Spoon dropwizard, you have to avoid resources folders, which contain such template files.

Benjamin.
